LibUnicode: Upgrade to Unicode version 14.0.0
SerenityOS/serenity pull request #10039
Opened 2021-09-15 13:40 UTC by trflynn89

This functionalizes some of the work in `unicode_data.cmake` for clarity and adds support for re-downloading the UCD and CLDR when their versions change. Then changes the UCD version to 14.0.0 :)

2021-09-15 14:02 UTC, trflynn89 commented
Marking as a draft because this will cause test262 failures until https://github.com/tc39/test262/pull/3199 is merged.

2021-09-24 19:39 UTC, ADKaster commented on Meta/CMake/unicode_data.cmake
> +set(CLDR_PATH "${CMAKE_BINARY_DIR}/CLDR" CACHE PATH "Download location for CLDR files")
Fwiw the CI scripts and Superbuild.cmake were setting the path for these cached artifacts using the old name (for when you get back to this :) )

2021-09-25 11:12 UTC, friendlyanon requested changes
As a general rule when touching CMake code, please consider quoting every variable substitution *unless* it's intended to be a list expansion.

2021-09-25 11:12 UTC, friendlyanon commented on Meta/CMake/unicode_data.cmake
> +    if (${version_differs})
Prefer to just name the variable alone if the [documentation](https://cmake.org/cmake/help/latest/command/if.html) indicates `<variable|string>`:

```suggestion
    if (version_differs)
```

An unquoted variable substitution (aka list expansion) into an `if()` command *can* do some unintended things.

2021-09-30 16:05 UTC, trflynn89 commented
This should be good to go now, the test262 PR has been merged.

2021-09-30 16:37 UTC, merged