Ports: Improve OpenSSL compilation
SerenityOS/serenity pull request #10207
Opened 2021-09-25 16:59 UTC by rtobar

By defining our own target platform in the OpenSSL compilation configuration we can now compile an OpenSSL shared library. We need to avoid symbol versioning though, as serenity's LibELF doesn't support this yet.

We are now also compiling with threading support to allow using the ssl module (to some extent) in Python. I have the Python changes ready, but since it depends on this PR I'd rather submit this one first and then Python's.

2021-09-25 23:01 UTC, rtobar commented
The CI failure seems like a completely unrelated test timeout issue to my eyes.

2021-09-28 12:33 UTC, rtobar commented
Now that #10241 has been fixed I can confirm that with these changes the OpenSSL port finally allows the `ssl` python module to be not only loaded but also used to create an `SSLContext` object.

2021-10-05 03:13 UTC, rtobar commented
Again, Azure CI failures seem unrelated.

2021-10-05 08:02 UTC, linusg requested changes
Please reword the first commit message to something more meaningful.

2021-10-05 13:26 UTC, rtobar commented
> Please reword the first commit message to something more meaningful.

@linusg do you mean the subject? I tried to make the commit message itself descriptive enough without needing to go into much detail (to avoid repeating what's in the actual code), while listing all the changes that are going in. Maye "Ports: Compile OpenSSL with threads and as a shared library" is better? I try to avoid long subject lines, and I'm not sure if that would break any of the lintings.

For reference, the full commit message:
```
Ports: Improve OpenSSL compilation 

By defining our own target platform in the OpenSSL compilation
configuration we can now compile an OpenSSL shared library. We need to
avoid symbol versioning though, as serenity's LibELF doesn't support
this yet.

We are now also compiling with threading support to allow using this
from Python.
```

2021-10-05 13:31 UTC, linusg commented
yep, the subject. From https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md:

> Use weasel-words like "refactor" or "fix" to avoid explaining what's being changed.

I'd consider "improve" to fall under the same category.

> Maybe "Ports: Compile OpenSSL with threads and as a shared library" is better?

Much better!

> I try to avoid long subject lines, and I'm not sure if that would break any of the lintings.

Up to 72 chars is fine.

> I tried to make the commit message itself descriptive enough

That's good! :^)

2021-10-05 14:34 UTC, rtobar commented
> > Maybe "Ports: Compile OpenSSL with threads and as a shared library" is better?
> 
> Much better!

Done! :)

2021-10-05 14:35 UTC, merged