LibGUI+Applications: Add intrinsic margins to Widgets + ScrollableContainerWidget Improvements
SerenityOS/serenity pull request #10246
Opened 2021-09-28 15:41 UTC by frhun

Before, content margins (as specified as a property of the layout) were measured relative to the outer most edge of the container widget, which lead to the awkward workaround of always including the border width of Frame or GroupBox in the margins. The worst problem with this approach becomes apparent when you consider that the title of GroupBoxes was also included in these margins.
![Bildschirmfoto von 2021-09-28 17-19-19](https://user-images.githubusercontent.com/28605587/135117486-a85ca901-70c9-4e39-b8f9-0b5a5501a35f.png)

This also improves the AbstractScrollableWidget using the content margin interface, in order to not consider the area obscured by the scrollbars as visible. This mainly is to the benefit of ScrollableContainerWidget usability, as a general purpose container. Because of that I also added ScrollableContainerWidget to be usable from GML. It still has it's problems (specifically when `should_hide_unnecessary_scrollbars: true` is set), but should now be solid enough to iterate upon.
With a widget that tries to fill the entire visible area of the ScrollableContainerWidget, which is something that has only become easily achievable now, there are some problems when downsizing while `should_hide_unnecessary_scrollbars: true`. But that is a problem to solve separately, as it also seems to appear before, in the Browser for example.

All this functionality will come in really handy, when implementing more dynamic layouts, that don't rely so heavily on manually set sizes. That is already something I'm working on, and it already somewhat works, but I wanted to get this merged first, so it doesn't turn into an unmanageable monster PR. This is also the reason why the `preferred_size` method of Layout is a bit awkward now, because it will most likely shortly be moved into Widget. (if I have it my way)

2021-09-28 15:44 UTC, frhun commented on Userland/Libraries/LibGUI/GroupBox.cpp
> +        2 };
These magic numbers are already gone in my working branch, where I make a lot of changes to GroupBox, but are just here as a stop-gap solution, for now.

2021-11-03 10:05 UTC, awesomekling requested changes
Very cool work!

Please make sure to write commit subjects in the imperative mood, and wrap commit messages at 72 characters.

2021-11-03 10:05 UTC, awesomekling commented on Userland/Libraries/LibGUI/GroupBox.cpp
> +    invalidate_layout();
The commit message mentions `GroupBoxLayout` which is not a thing.

2021-11-03 10:05 UTC, awesomekling commented on Userland/Libraries/LibGUI/Frame.h
> +    virtual Margins content_margins() const { return { frame_thickness() }; }
Missing `override`.

2021-11-03 10:05 UTC, awesomekling commented on Userland/Libraries/LibGUI/ScrollableContainerWidget.cpp
> +            AK::max(inner_size.height(), min_size.height())
Do we really need to qualify `AK::` here?

2021-11-03 15:13 UTC, merged