LibAudio(+SoundPlayer): Implement seeking in FLAC using seektables :^)
SerenityOS/serenity pull request #10273
Opened 2021-09-30 13:03 UTC by krkk

- **LibAudio: Implement seeking in FLAC using seektables :^)**

- **SoundPlayer: Set m_last_seek after seeking**

  Prior this change, the manager didn't pay attention whether a loader sought exactly to the given position. So if a loader couldn't do that (just like flacs right now), then the slider progress stopped showing the correct position anymore.

2021-09-30 13:20 UTC, krkk commented
ci is failing, i’ll check it in the evening.
converting to draft for now.

2021-09-30 20:25 UTC, kleinesfilmroellchen requested changes
Once again, I am outmatched in speed of implementing my own todos.

2021-09-30 20:25 UTC, kleinesfilmroellchen commented on Userland/Libraries/LibAudio/FlacLoader.cpp
> -    // TODO: For a simple first implementation, all other blocks are skipped as allowed by the FLAC specification.
Please change this to a new TODO comment that notes how we skip all block types *except* SEEKTABLE and STREAMINFO.

2021-09-30 20:25 UTC, kleinesfilmroellchen commented on Userland/Libraries/LibAudio/FlacLoader.cpp
> +                // <64> Sample number of first sample in the target frame, or 0xFFFFFFFFFFFFFFFF for a placeholder point.
(not a complaint) nicely copying the spec here :^)

2021-09-30 20:25 UTC, kleinesfilmroellchen commented on Userland/Libraries/LibAudio/FlacLoader.cpp
> +    if (!m_stream->seek(m_data_start_location + (last_seek_point_or_none.has_value() ? last_seek_point_or_none->offset : 0))) {
Please use Optional's `value_or` for the Optional shenanigans.

2021-09-30 20:25 UTC, kleinesfilmroellchen commented on Userland/Libraries/LibAudio/FlacLoader.cpp
> +    m_loaded_samples = last_seek_point_or_none.has_value() ? last_seek_point_or_none->sample_index : 0;
(see above)

2021-09-30 20:27 UTC, Granddave commented on Userland/Libraries/LibAudio/FlacLoader.cpp
> +                if (sample_index == 0xFFFFFFFFFFFFFFFF)
Consider adding separators to make the literal clearer :)
```suggestion
                if (sample_index == 0xFFFF'FFFF'FFFF'FFFF)
```

2021-10-01 03:58 UTC, alimpfard commented on Userland/Libraries/LibAudio/FlacLoader.cpp
> +    });
I assume these are ordered, so please use a binary search instead.

2021-10-01 03:58 UTC, alimpfard commented on Userland/Libraries/LibAudio/FlacLoader.cpp
> +                m_seektable.append({
Since there is an upper bound, I'd suggest calling `m_seektable.ensure_capacity(block.length / 18)` before this loop to avoid reallocations here.

2021-10-01 17:56 UTC, krkk commented on Userland/Libraries/LibAudio/FlacLoader.cpp
> +    if (!m_stream->seek(m_data_start_location + m_seektable[nearby_index].offset)) {
this will crash if m_seektable is empty..

yeah

2021-10-01 18:51 UTC, krkk commented
A few extra changes that sneaked between pushes:
* Removed `if (position < 0 || (unsigned)position >= m_total_samples)` from the beginning of the `seek()` function, as it:
  1. wasn’t there before, I just copy-pasted it from the wav loader when I was implementing it
  1. doesn't seem needed, as the binary search will just give the nearest seekpoint anyway
  1. would cancel the seek when trying to seek to the very end, instead of seeking to the last seekpoint in Sound Player (because `position == m_total_samples`, slider clamps to `max()`)
* `m_error_string` will now also show the calculated seek position on fail
* Don’t update `m_loaded_samples` if seek failed

2021-10-03 18:29 UTC, kleinesfilmroellchen approved these changes

2021-10-31 22:30 UTC, closed without merging