LibC+Toolchain: Implement _aligned_malloc and _aligned_free
SerenityOS/serenity pull request #10817
Opened 2021-11-06 11:21 UTC by BertalanD

### LibC: Implement _aligned_malloc and _aligned_free

C++17 introduced aligned versions of `new` and `delete`, which are
automatically called by the compiler when allocating over-aligned
objects. As with the regular allocator functions, these are generally
thin wrappers around LibC.

We did not have support for aligned allocations in LibC, so this was not
possible. While libstdc++ has a fallback implementation, libc++ does
not, so the aligned allocation function was disabled internally. This
made building the LLVM port with Clang impossible.

I chose not to implement the more Unix-y `memalign`, `posix_memalign`,
or the C11 `aligned_alloc`, because that would require us to
significantly alter the memory allocator's internals. See the comment in
malloc.cpp.

### Toolchain: Add aligned allocation support to libc++ 

Now that we have `_aligned_malloc` and `_aligned_free`, we can finally
enable C++17 aligned allocation support.

--- 
If Qt can be patched to use `_aligned_malloc` instead of `memalign`, this would tick one item in the to-do list of #9362.

2021-11-07 23:00 UTC, BertalanD commented
Changes since last push:
- Reworded comments to make the reason for not going with `aligned_alloc()` clearer
- Fixed logic error when rounding down the aligned pointer (`&` with the complement of `alignment - 1`)

2021-11-14 10:37 UTC, timschumi approved these changes
Looks reasonable, although I haven't tested it yet. Do we have anything to test this with?

2021-11-14 11:36 UTC, linusg requested changes

2021-11-14 11:36 UTC, linusg commented on Userland/Libraries/LibC/malloc.cpp
> +// Both Unix-y aliternatives to _aligned_malloc(), the C11 aligned_alloc() and
```suggestion
// Both Unix-y alternatives to _aligned_malloc(), the C11 aligned_alloc() and
```

2021-11-14 15:37 UTC, BertalanD commented
> Looks reasonable, although I haven't tested it yet. Do we have anything to test this with?

We could do a bunch of allocations and check if the pointers are aligned correctly. That would leave a few failure modes uncovered, like if we return a smaller block than requested or if free it improperly.

In terms of real-world usages, `libc++`'s `std::barrier` implementation performs over-aligned allocations internally.

2021-11-14 16:23 UTC, linusg requested changes
The typo is still present in the first commit and only fixed in the second. Please never introduce it in the first place, then we get nicer diffs :)

2021-11-14 16:46 UTC, merged