Meta: Resolve cyclic dependency between LibPthread and libc++
SerenityOS/serenity pull request #10845
Opened 2021-11-08 18:26 UTC by BertalanD

libc++ uses a Pthread condition variable in one of its initialization
functions. This means that Pthread forwaring has to be set up in LibC
before libc++ can be initialized.

Because LibPthread is written in C++, (at least some) parts of the C++
standard library have to be linked against it. Conversely, libc++ calls
LibPthread functions, so it has to link against LibPthread. This creates
a circular dependency, which means that the order in which these two
libraries' initialization functions are called is undefined. This
initialization order fiasco prevents us from running C++ ports compiled
with the Clang toolchain.

This issue isn't necessarily unique to LibPthread, as all libraries that
libc++ depends on exhibit the same circular dependency issue. This is
why I chose to all it to the `serenity_libc` function, as all POSIX
system libraries end up calling it.

The reason why this issue didn't affect the GNU toolchain is that
libstdc++ is always linked statically. If we were to change that, I
believe that we would run into the same issue there.

2021-11-12 19:46 UTC, BertalanD commented
Fixed LibPthread unintentionally being linked to LibC due to the LLD [dependent libraries feature](https://reviews.llvm.org/D60274).

2021-11-12 21:04 UTC, linusg requested changes
forwaring -> forwarding

2021-11-13 09:05 UTC, BertalanD commented
I fixed the typo.

2021-11-13 11:15 UTC, linusg approved these changes

2021-11-13 11:15 UTC, merged