LibJS: Async arrow function and async generator parsing
SerenityOS/serenity pull request #10926
Opened 2021-11-15 00:58 UTC by davidot

I wanted to implement async generator execution in bytecode but I still have to add a bunch of objects and prototypes so I wanted to start with this.

Draft since I'm still checking some things

2021-11-20 23:57 UTC, linusg requested changes
The second commit message needs refining, it confuses "prototype" with "prototype property" - async functions *do* have a prototype, but unlike regular functions they don't have a prototype property.

`LibJS: Parse Async generator functions` -> `LibJS: Parse async generator functions` for the third commit, c o n s i s t e n c y :^)

2021-11-20 23:57 UTC, linusg commented on Userland/Libraries/LibJS/Runtime/AsyncGeneratorFunctionConstructor.cpp
> +// 27.4.1.1 AsyncGeneratorFunction ( p1, p2, … , pn, body ), https://tc39.es/ecma262/#sec-asyncgeneratorfunction-constructor
we usually link to the same thing for call and construct

```suggestion
// 27.4.1.1 AsyncGeneratorFunction ( p1, p2, … , pn, body ), https://tc39.es/ecma262/#sec-asyncgeneratorfunction
```

2021-11-20 23:57 UTC, linusg commented on Userland/Libraries/LibJS/Runtime/AsyncGeneratorFunctionConstructor.h
> +#include <LibJS/AST.h>
Why is this included?

2021-11-20 23:57 UTC, linusg commented on Userland/Libraries/LibJS/Runtime/AsyncGeneratorFunctionPrototype.h
> +class AsyncGeneratorFunctionPrototype final : public Object {
This should probably inherit from `PrototypeObject`?

2021-11-21 12:57 UTC, davidot commented
Fixed all the comments, are the commit messages alright? I'm not super happy with the second one but don't want to write 10 things of which 2 are really relevant to the actual diff.

2021-11-21 13:02 UTC, linusg commented on Userland/Libraries/LibJS/Runtime/AsyncGeneratorFunctionPrototype.cpp
> +    : Object(*global_object.function_prototype())
```suggestion
    : PrototypeObject(*global_object.function_prototype())
```

2021-11-21 13:02 UTC, linusg commented
Build failure looks like a missing include.

> are the commit messages alright?

Looks good, thanks :+1:

2021-11-21 13:03 UTC, davidot commented on Userland/Libraries/LibJS/Runtime/AsyncGeneratorFunctionPrototype.cpp
> +    : Object(*global_object.function_prototype())
Yeah pushed a little too early

2021-11-21 13:04 UTC, linusg approved these changes

2021-11-21 21:46 UTC, merged