LibJS: Implement Temporal.PlainDate.prototype.{until,since}
SerenityOS/serenity pull request #10930
Opened 2021-11-15 21:29 UTC by Lubrsi

Ticks off two checkboxes in #8982.

2021-11-15 22:00 UTC, linusg requested changes

2021-11-15 22:00 UTC, linusg commented on Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.prototype.since.js
> +const allowedUnits = ["year", "month", "week", "day"];
all comments from the other test apply here as well

2021-11-16 00:56 UTC, Lubrsi commented
Done :+1:

2021-11-16 01:05 UTC, linusg commented on Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
> +StringView negate_temporal_rounding_mode(String const& rounding_mode)
Sorry, that wasn't very clear - I actually meant StringView for the argument, but I guess this works fine.

2021-11-16 01:06 UTC, merged