LibCore: FilePermissionsMask
SerenityOS/serenity pull request #11429
Opened 2021-12-26 10:23 UTC by xavier

This change introduces a Unix file permission parser class as discussed in https://github.com/SerenityOS/serenity/pull/11319.

I have rewritten the symbolic permission parsing algorithm to be FSM-based. It should now be more straightforward as it reduces the number of hoops and doesn't involve recursive calls anymore.

I have updated `mkdir` and `chmod` to use the new library, hence reducing the complexity of both utilities.

2021-12-27 23:14 UTC, linusg requested changes
Please:

- Use east const
- Wrap commit messages at 72 characters, not 50

...as per the [contribution](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy) and [coding style](https://github.com/SerenityOS/serenity/blob/master/Documentation/CodingStyle.md#const-placement) guidelines.

2021-12-27 23:15 UTC, linusg commented on Userland/Libraries/LibCore/FilePermissionsMask.cpp
> +ErrorOr<FilePermissionsMask> FilePermissionsMask::parse(const StringView& string)
Don't pass StringView by const reference, pass it by value (see https://github.com/SerenityOS/serenity/commit/8b1108e4858f797c9216dc8ae4a3918ad50c73b4)

2021-12-27 23:16 UTC, linusg commented on Userland/Libraries/LibCore/FilePermissionsMask.h
> +    mode_t m_write_mask; // the bits that will be set
We use public, protected, private as the usual order of class members and functions

2022-01-01 17:33 UTC, merged

2022-01-11 04:13 UTC, roytam1 commented
it seems break normal usage by scripts, getting this when running perl's Configure script:
```
40.233 chmod(127:127): Exiting with runtime error: invalid access class: expected 'u', 'g', 'o' or 'a'
```

2022-01-11 06:20 UTC, xavier commented
@roytam1 Do you by any chance have an example of the symbolic permission which causes this problem? Or a way to reproduce it?

2022-01-11 07:47 UTC, bgianfo commented
> it seems break normal usage by scripts, getting this when running perl's Configure script:
> 
> ```
> 40.233 chmod(127:127): Exiting with runtime error: invalid access class: expected 'u', 'g', 'o' or 'a'
> ```

Please file a bug with directions on how to reproduce.

2022-01-11 15:16 UTC, roytam1 commented
> @roytam1 Do you by any chance have an example of the symbolic permission which causes this problem? Or a way to reproduce it?

a simple `chmod +r README.md` will do, and mode bits are intact.
IIRC without access class implies `a`.

2022-01-11 15:19 UTC, xavier commented
Gotcha, I'll work on a fix.