LibWeb+Meta: Implement CanvasRenderingContext2D.measureText
SerenityOS/serenity pull request #11512
Opened 2021-12-30 22:20 UTC by sin-ack

This requires an implementation of the "text preparation algorithm" as
specified here:

html.spec.whatwg.org/multipage/canvas.html#text-preparation-algorithm

However, we're missing a lot of things such as the
CanvasTextDrawingStyles interface, so most of the algorithm was not
implemented. Additionally, we also are not able to use a LineBox like
the algorithm suggests, because our layouting infra is not up to the
task yet. The prepare_text function does nothing other than figuring out
the width of the given text and return glyphs with offsets at the
moment.

2021-12-30 22:26 UTC, linusg commented
I know WrapperGenerator is in `Meta/`, but I haven't ever seen us using the `Meta` prefix for it. It's still `LibWeb`, sort of.

2021-12-31 04:30 UTC, sin-ack commented
Fixed.

2022-01-04 18:54 UTC, AtkinsSJ requested changes
One little nitpick but otherwise it seems reasonable to me. Obviously there are a lot of fixmes, so it's going to see a lot of future changes anyway.

2022-01-04 18:54 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
> +RefPtr<TextMetrics> CanvasRenderingContext2D::measure_text(const String& text)
West const?!? In my SerenityOS? It's more likely than you think.

2022-01-04 22:40 UTC, linusg approved these changes

2022-01-04 22:41 UTC, merged