LibSoftGPU: Configurable stats overlay period
SerenityOS/serenity pull request #11741
Opened 2022-01-08 21:36 UTC by ldm5180

Problem:
- The statistics overlay period is hardcoded to 500 ms. This time is
  very short and can result in the values being very "jumpy".

Solution:
- Increasing this value can result in more steady values which is
  useful when trying to evaluate the performance impact of a change. A
  new config value is offered in `Config.h` to let the developer
  change to any value desired.

2022-01-09 22:10 UTC, GMTA approved these changes

2022-01-09 22:21 UTC, sunverwerth approved these changes
Looks gold to me.

2022-01-09 22:27 UTC, linusg requested changes
https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy

> Write the commit message subject line in the imperative mood ("Foo: Change the way dates work", not "Foo: Changed the way dates work").

(also has a conflict)

2022-01-10 06:40 UTC, bgianfo commented
Not sure how I managed to accidentally close this, sorry!

2022-01-22 05:27 UTC, merged