LibTrash: Create an inital trash can API library
SerenityOS/serenity pull request #11794
Opened 2022-01-10 17:10 UTC by nyabla

This is intended to be a starting off point for an API that allows placing files in a "trash can" to be later removed or restored instead of directly deleting them :^)
The intention is to use this library within file manager and to create a command line utility

2022-01-10 17:51 UTC, linusg requested changes
Please don't add such an API without any users. Also, please use `auto` more, in many cases here the full type name is quite verbose. Since the class is called TrashCan, the file name should match that..

2022-01-10 17:51 UTC, linusg commented on Userland/Libraries/LibTrash/Trash.cpp
> +    m_trash_directory = String::formatted("{}/.trash", Core::StandardPaths::home_directory());
This should be in StandardPaths instead

2022-01-10 17:51 UTC, linusg commented on Userland/Libraries/LibTrash/Trash.cpp
> +    if (path.is_empty() || !path.starts_with("/"))
is_empty check is redundant, an empty string also doesn't start with /

2022-01-10 17:51 UTC, linusg commented on Userland/Libraries/LibTrash/Trash.cpp
> +    info_file->write_entry(URL::percent_encode(path), String::number(timestamp), "");
why is percent encoding necessary here? ConfigFile should take care of encoding a key properly so that it can be read again itself.

2022-01-13 23:25 UTC, nyabla commented
Thanks for your review, uni has started again and I need some time to settle down so I'm closing this for the time being

2022-01-13 23:25 UTC, closed without merging