AK: Fix erroneous move operators for SinglyLinkedList
SerenityOS/serenity pull request #11908
Opened 2022-01-15 10:22 UTC by LucasChollet

This patch provides a proper implementation of the move operator and
delete the move assignment operator.

Those operators were introduced in #11888

2022-01-15 10:26 UTC, ADKaster commented on AK/SinglyLinkedList.h
> +        m_tail = nullptr;
This leaks the list. I think you meant to set other.m_head and other.m_tail to nullptr?

2022-01-16 10:13 UTC, awesomekling requested changes

2022-01-16 10:13 UTC, awesomekling commented on AK/SinglyLinkedList.h
> +        , m_tail { move(other.m_tail) }
`move()` does not do anything here, as `m_head` and `m_tail` are both primitive raw pointer values.

2022-01-18 20:36 UTC, IdanHo commented on AK/SinglyLinkedList.h
> +        , m_tail { other.m_tail }
We don't use brace initializers in constructor initializer lists (as in, this should be `m_head(other.m_head)` instead

2022-01-18 23:13 UTC, merged