SoundPlayer: Correct wrong FFT visualization
SerenityOS/serenity pull request #11934
Opened 2022-01-15 23:44 UTC by standardexe

Some small things:

- The time samples were `abs()`ed before being transformed, which just adds a DC offset and distorts the spectrum.
- Only the real part of the frequency bins were visualized, therefore encoding phase information in the spectrum. But if you play a single sine wave sound, you expect only a single bar to show in the spectrum, not a bunch.
- No window was applied to the time samples before transformation, so the spectrum had spectral leakage.
- Normalization of the spectrum energy was bogus.
- The FFT visualization would take a whole input buffer and transform it. That ment frames per second would depend on the size of the buffer and would possibly do very big FFTs which can become CPU intensive. So I took a stab at changing the architecture to make many little subsequent FFTs on the same buffer possible.
- Use log scale because it looks nice :-)

2022-01-17 17:19 UTC, kleinesfilmroellchen requested changes
Sorry for taking so long, I was busy :(.

Looks great, I'll have a test later this evening!

2022-01-17 17:19 UTC, kleinesfilmroellchen commented on Userland/Applications/SoundPlayer/VisualizationWidget.h
> +            m_render_buffer[i] = m_sample_buffer[i + buffer_position];
Please use AK::TypedTransfer

2022-01-17 17:19 UTC, kleinesfilmroellchen commented on Userland/Applications/SoundPlayer/VisualizationWidget.h
> +    Vector<double> m_render_buffer;
Once again, FixedArray :^)

2022-01-17 17:19 UTC, kleinesfilmroellchen commented on Userland/Applications/SoundPlayer/VisualizationWidget.h
> +    static constexpr size_t RefreshTimeMilliseconds = 30;
As per the code style, this should be SCREAMING_SNAKE_CASE.

2022-01-17 17:19 UTC, kleinesfilmroellchen commented on Userland/Applications/SoundPlayer/BarsVisualizationWidget.h
> +    static constexpr size_t BinsPerGroup = (FFTSize / 2) / BinGroupCount;
As per the code style, please SCREAMING_SNAKE_CASE here.

2022-01-17 22:49 UTC, kleinesfilmroellchen commented
Also, please fix your commit message in 1f60f26e2fe4b2f97205624b0d18e5722d2dd2b1

2022-01-19 21:01 UTC, kleinesfilmroellchen commented
Just tried the new visualizer and it's definitely much better than the old one, especially for samples. There we won't need any changes. However, there are a couple of debatable technicalities with the new spectral analyzer:
1. The window is now so short that the bars mostly frantically flip about. The best course of action here is probably to just make the window a bit larger again.
2. The windows are used non-overlappingly. This actually makes the spectral analysis even less smooth and may fix (1) so that we don't need shorter windows. I know from writing spectral analysis myself that overlapping windows give much better visuals because two consecutive frames share (up to) half their audio data. This is also how continuous FFT (or short-time fourier transform STFT) is done in most tools, even if it's not used for convolution filters. See https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.stft.html#scipy.signal.stft for an excellent example.

I'd like the frequency adjustment to be the default. It just makes much more sense to boost the higher frequencies by default.

The visualization is currently ahead of the audio, but I'm guessing that's unavoidable with the current time-course audio playback. When I rearchitect audio streaming, this issue will probably be solvable much more easily so I don't expect it to be fixed.

And finally, there seems to be a bug where playback of any file (both FLAC and WAV) stops quite some time before the file has actually finished playing, without any error or anything. This only happens to SoundPlayer (not aplay) and doesn't happen on master so it might be related.

2022-03-03 11:49 UTC, standardexe commented
> 

Hey Filmroellchen, unfortunately I don't have a lot of free time at the moment. Thanks for taking over the MP3 decoder PR.

2022-03-03 19:12 UTC, kleinesfilmroellchen commented
No problem, I think I'll see this one through as well

2022-03-03 23:31 UTC, kleinesfilmroellchen commented
Continued in #12868

2022-03-03 23:31 UTC, closed without merging