Meta: Fix "Meta/serenity.sh run x86_64 Clang" on M1 Macs
SerenityOS/serenity pull request #12210
Opened 2022-01-29 23:30 UTC by serenityosrocks

qemu crashes on M1 Macs when using "--accel hvf"
To solve this, detect the host's architecture and only add that parameter if it is "x86_64", not "arm64" like it is on M1 Macs.

2022-02-06 02:30 UTC, bgianfo requested changes
Can you please add the description you have in the PR, to the commit message?

2022-02-07 02:23 UTC, bgianfo approved these changes

2022-02-07 02:24 UTC, bgianfo commented
I went ahead and added the description to your commit message my self, thanks!

2022-02-07 02:25 UTC, merged

2022-02-07 17:49 UTC, serenityosrocks commented
Thanks for the review!