PixelPaint: Add missing FileTypes
SerenityOS/serenity pull request #12238
Opened 2022-02-01 03:37 UTC by jedieaston

As mentioned in today's monthly update video, the Open With menu doesn't show Pixel Paint for most image file types.
This commit brings it in sync with Image Viewer, since everything seems to open correctly anyway :)

![image](https://user-images.githubusercontent.com/21368066/151909400-0ab39bb3-b3b8-4074-b988-7244fb38f678.png)

2022-02-01 04:08 UTC, bgianfo commented
Thanks for the patch, congratulations on your first contribution! :partying_face: :two_hearts:

2022-02-01 04:10 UTC, bgianfo requested changes
One small nitpick in the commit message.

This should really be `Base:`, so something like. 

`Base: Add missing FileTypes for PixelPaint`

2022-02-01 11:50 UTC, jedieaston commented
Fixed! Sorry for the goof.

2022-02-01 23:44 UTC, bgianfo approved these changes

2022-02-01 23:44 UTC, merged

2022-02-02 10:07 UTC, shannonrothe commented
Beat me to it 😂