PixelPaint: Multiple buttons at same time now paints in correct color
SerenityOS/serenity pull request #12322
Opened 2022-02-06 20:33 UTC by Matthias-Sleurink

Centralize the storage of the most recently pressed button in the
ImageEditor to ensure that all tools display the same behavior when
multiple buttons are pressed on the mouse at the same time during
movement of the mouse.

This fixes that brush and spray tool wrongly interpreted this situation.

Example before:
![serenity_change_before](https://user-images.githubusercontent.com/83409229/152700089-124c6f32-febd-4bb3-9f03-ee440c4863b8.png)

Example after:
![serenity_change_after](https://user-images.githubusercontent.com/83409229/152700097-26606cc3-7ba7-41dc-bf31-06e0e3321eb9.png)

These examples show what happens with the brush tool when you:
First line:
push-primary
push-secondary
release-secondary
release-primary

Second line:
push-secondary
push-primary
release-primary
release-secondary

third line:
push-primary
push-secondary
release-primary
release-secondary

fourth line:
push-secondary
push-primary
release-secondary
release-primary

2022-02-06 20:35 UTC, Matthias-Sleurink commented
This change also removes the need to have `Color color_for(GUI::MouseEvent const& event);`. But its behavior is correct at the moment so I saw no need to remove it.

2022-02-07 15:09 UTC, linusg requested changes
https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy

> Write the commit message subject line in the imperative mood ("Foo: Change the way dates work", not "Foo: Changed the way dates work").

2022-03-08 23:12 UTC, linusg commented on Userland/Applications/PixelPaint/ImageEditor.h
> +    GUI::MouseButton m_last_pressed_colour_indicating_button { GUI::MouseButton::None };
The project uses US english as its language - colour -> color

2022-03-08 23:12 UTC, linusg commented on Userland/Applications/PixelPaint/Tools/SprayTool.cpp
> +    const Color color = m_editor->current_color();
Please use `auto` where possible. Also, east const for new code.

2022-03-08 23:15 UTC, linusg commented
Also has conflicts :)

2022-04-06 01:37 UTC, closed without merging