LibWeb: Ignore malformed at-rules in CSS parser
SerenityOS/serenity pull request #12440
Opened 2022-02-11 17:49 UTC by eggpi

Fixes #12405.

2022-02-11 20:48 UTC, AtkinsSJ requested changes
Nice work! :^)

I have a few nit-picks but nothing major.

2022-02-11 20:48 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
> +            }
`if (media_query_list.is_empty())` would be clearer here. :^) Also, please remove the braces when it's a single line.

2022-02-11 20:48 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
> +            }
Remove the braces here too. Could even combine the two `if`s if you want.

2022-02-11 20:48 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
> +            }
Can remove the {} here too.

2022-02-11 22:25 UTC, eggpi commented
All done, thanks for the quick review! Please take another look.

2022-02-12 09:05 UTC, AtkinsSJ approved these changes
LGTM!

2022-02-12 10:24 UTC, merged