LibGUI: Multimonitor Dialog and Window positioning improvements
SerenityOS/serenity pull request #12579
Opened 2022-02-16 16:54 UTC by DerpyCrabs

These changes fix positioning of dialogs and windows on multiple screens.

For example with SERENITY_SCREENS=2 ShutdownDialog no longer appears between two screens.
Dialogs with parent and ScreenPosition other than CenterWithinParent now positioned inside of the screen containing most of the parent's window (same behavior as dialogs in Windows/Linux).

2022-02-18 18:04 UTC, tomuta requested changes

2022-02-18 18:04 UTC, tomuta commented on Userland/Libraries/LibGUI/Dialog.cpp
> +    auto bottom_align = [this, screen_rect](Gfx::Rect<int>& rect) { rect.set_y(screen_rect.y() + screen_rect.height() - Desktop::the().taskbar_height() - height() - 12); };
This was already wrong, the taskbar is only displayed if the screen you're centering on is the same as `Desktop::the().main_screen_index()`

2022-02-18 18:04 UTC, tomuta commented on Userland/Libraries/LibGUI/Dialog.cpp
> +        screen_index = static_cast<Window*>(parent())->containing_screen_index();
Overwriting `screen_index` seems wrong here. The value returned by `Desktop::the().main_screen_index()` is the screen where the taskbar is located on, which is information we should take into account when centering a window (there's no taskbar on other screens).

2022-03-13 10:15 UTC, DerpyCrabs commented
It's not stale.

2022-04-22 19:57 UTC, closed without merging