LibWeb: Add origin property to window object
SerenityOS/serenity pull request #12594
Opened 2022-02-17 02:08 UTC by Alexander1994

Added origin property to the window object

Just a small commit / PR to get the hang of making contributions.

2022-02-17 02:09 UTC, timschumi commented
For the future: You can just keep the same PR open and force-push the branch. :^)

2022-02-17 09:21 UTC, linusg requested changes

2022-02-17 09:21 UTC, linusg commented on Userland/Libraries/LibWeb/Bindings/WindowObject.cpp
> +JS_DEFINE_NATIVE_FUNCTION(WindowObject::origin_getter)
Please add a spec link above the function: `https://html.spec.whatwg.org/multipage/webappapis.html#dom-origin`

2022-02-17 09:21 UTC, linusg commented on Userland/Libraries/LibWeb/Bindings/WindowObject.cpp
> +    }
This needs to be abstracted into `Origin::serialize()`, following the spec: https://html.spec.whatwg.org/multipage/origin.html#ascii-serialisation-of-an-origin

2022-02-21 18:09 UTC, paulwratt commented
This should probablyt be checked against the `window.localStorage` (https://github.com/SerenityOS/serenity/commit/47979996e832bdd05440c4a9437920863543441d) where a hash is created against the origin, and weather it affect `window.sessionStorage` in its current form (#12698)

2022-02-22 23:41 UTC, Alexander1994 commented
> This should probably be checked against the `window.localStorage` ([4797999](https://github.com/SerenityOS/serenity/commit/47979996e832bdd05440c4a9437920863543441d)) where a hash is created against "origin" in [Stroage](https://github.com/SerenityOS/serenity/commit/47979996e832bdd05440c4a9437920863543441d#diff-cc430c8292bfa7b11143fa0e4b0d7ed2277519ae5db85f763551e9fb70999ff8), and weather it affects `window.sessionStorage` in its current form (#12698)

I'm not sure we'd want these to be equivalent origin

2022-02-23 02:45 UTC, paulwratt commented
Specifically I meant this (appologies it was in `Window.cpp` not `Storage.cpp`):
```
    static HashMap<Origin, NonnullRefPtr<HTML::Storage>> local_storage_per_origin;
    return local_storage_per_origin.ensure(associated_document().origin(), [] {
        return HTML::Storage::create();
    });
```

2022-02-23 13:08 UTC, Alexander1994 commented
> Specifically I meant this (appologies it was in `Window.cpp` not `Storage.cpp`):
> 
> ```
>     static HashMap<Origin, NonnullRefPtr<HTML::Storage>> local_storage_per_origin;
>     return local_storage_per_origin.ensure(associated_document().origin(), [] {
>         return HTML::Storage::create();
>     });
> ```

 I opted to create a separate function for providing a hash of the origin vs how we would hash it for a hashmap. I'll have a look soon to confirm though. Thanks for the heads up!

2022-02-23 14:01 UTC, Alexander1994 commented
A quick check on chrome confirmed that these hash functions should be the same as "file://" has the same origin. I'll update this PR accordingly.

2022-02-23 15:34 UTC, davidot reviewed
Code LGTM, just one comment about spec comments

2022-03-01 00:27 UTC, davidot approved these changes

2022-03-01 13:37 UTC, linusg approved these changes

2022-03-01 13:38 UTC, merged