DynamicLinker: Implement support for RPATH and RUNPATH
SerenityOS/serenity pull request #12631
Opened 2022-02-18 18:26 UTC by timschumi

This is needed for running Lagom binaries inside Serenity, as they find their `liblagom-core` via the rpath field.

2022-02-18 18:33 UTC, timschumi commented
Hold on, this breaks dlopen...

2022-02-18 18:40 UTC, BertalanD commented
ref #9430

2022-03-08 21:43 UTC, linusg requested changes
Please use east const for all new code.

2022-03-08 22:21 UTC, linusg approved these changes

2022-03-08 22:21 UTC, merged