Base: Improve default WebServer pages
SerenityOS/serenity pull request #12717
Opened 2022-02-22 02:55 UTC by electrikmilk

Add some fancy stuff like semantic tags, styling and the lady ball to the default web server pages :^).

Before:
![Screen Shot 2022-02-21 at 21 36 18](https://user-images.githubusercontent.com/4368524/155054627-9941e0b1-6500-4134-afbc-84288dc93836.png)
![Screen Shot 2022-02-21 at 21 36 33](https://user-images.githubusercontent.com/4368524/155054626-e8080853-9c1c-4728-b663-b505a25536c8.png)

After:
![Screen Shot 2022-02-21 at 21 44 20](https://user-images.githubusercontent.com/4368524/155054635-129abe0b-e4e2-4428-a7ce-e193b16e8444.png)
![Screen Shot 2022-02-21 at 21 49 17](https://user-images.githubusercontent.com/4368524/155054634-14e551a2-5547-4344-bdd7-4ff441eb6ee4.png)

2022-02-22 07:40 UTC, drunderscore commented
(on mobile, can't properly review) The "last modified" HTML comments seem a bit superfluous, we have git commit history for this :^)

2022-02-22 14:25 UTC, paulwratt commented
does Serenity have a "default color palette" ? Does Browser have a @native GUI CSS tag yet?

2022-02-22 14:33 UTC, paulwratt commented
Whats with all the `<header>`, `<main>` and `<section>` tags.  With only `<!doctype html>` and `<html lang="en">` those tags are invalid.

Now I cant browser the Serenity Web Server with my HTML 3.2 Browser ..

Also you forgot the `</head>` tag.

2022-02-22 14:36 UTC, linusg commented
> Whats with all the <header>, <main> and <section> tags. With only <!doctype html> and <html lang="en"> those tags are invalid.

No idea what you're talking about, `<!doctype html>` is the HTML5 doctype.

> Now I cant browser the Serenity Web Server with my HTML 3.2 Browser ..

https://github.com/SerenityOS/serenity/pull/5191#issuecomment-773873994

2022-02-22 14:40 UTC, paulwratt commented
there a difference between _inclusion_ and _exclusion_ . Are you saying WebServer _is not_ going to support HTTP/1.0 ?

2022-02-22 19:38 UTC, paulwratt commented
> > Whats with all the `<header>`, `<main>` and `<section>` tags.  With only `<!doctype html>` and `<html lang="en">` those tags are invalid.
> 
> No idea what you're talking about, `<!doctype html>` is the HTML5 doctype, and those are perfectly valid.
> 

And _still_ inapropriate for the "Well Hello Friends" _landing page_ for your "now working, SerenityOS WebServer". (`HTML5 !== HTML`).

I could have said ".. those tags are invalid for non-HTML5 browsers, without the addition of a 1st line _schema_  or ENTITY tag (comparible to the HTML 4+ _transitional_ tags)." ([Browser _section_ tag support is limited](https://www.w3schools.com/TAgs/tag_section.asp#:~:text=in%20a%20document.-,Browser%20Support,-The%20numbers%20in)) - but I thought everyone would know that was what I meant.

> > Now I cant browser the Serenity Web Server with my HTML 3.2 Browser ..
> 
> [#5191 (comment)](https://github.com/SerenityOS/serenity/pull/5191#issuecomment-773873994)

Then _why_ include [those 2 meta tags](https://stackoverflow.com/a/51006700/8268081).

You do realise the _context_ in which [boricj made that comment](https://github.com/SerenityOS/serenity/pull/5191#issue-797550086), right?

And even without that context, Serenity(OS) has to _support archiology_, by virtue of what it is _and_ what it is doing, even if it itself is _not about archeology_.

---

Anyway, my point was to rather to cause _think _latterally_. Those tags dont _have_ to be used (why not `div` and `span`, or `center`, `i` and `b` - with ID/Class, which can _also_ be rendered by non-CSS Browsers), they are not essential to its functionality, which is why the originals were _super generic_, the same goes for the CSS, (there are not, but I am just saying) dont use the _fancy ones_, while showing continuity with Browser, HTML & CSS _Fu_ (lets not _try_ to break the friendship of our "newly aquired friends, however old they are").

@electrikmilk if you wrap your new "box" layout with the following, it _will_ center any internal content in its _compacted form_ without forcing the its inner text to be _center aligned_, and show in the very _center_ of the browser window.

It works 100% in things like IE3, NS2, and the many HTML 3.2 & non-JS Web Browsers still being used out there today.
```
<table border=0 cellpadding=0 cellspacing=0 align=center valign=middle width=100% height=100%><tr align=center valign=middle width=100% height=100%><td align=center valign=middle width=100% height=100%><table><tr><td>
 ...
</td></tr></table></td></tr></table>
``

2022-02-22 19:47 UTC, linusg commented
This is not up for discussion, we're not going to use table layouts or make the HTML worse to deal with ancient browsers. 

@electrikmilk New page looks very nice, please fix up that missing head tag and I think it's good to go.

2022-02-22 20:06 UTC, paulwratt commented
@linusg I guess I'll have to remember that next time I start up SerentyOS - sorry.

2022-02-22 22:29 UTC, electrikmilk commented
> (on mobile, can't properly review) The "last modified" HTML comments seem a bit superfluous, we have git commit history for this :^)

That's perfectly fair, I was going off of the Apache default page which has this 🤦

2022-02-22 22:31 UTC, electrikmilk commented
> Whats with all the `<header>`, `<main>` and `<section>` tags. With only `<!doctype html>` and `<html lang="en">` those tags are invalid.
> 
> Now I cant browser the Serenity Web Server with my HTML 3.2 Browser ..
> 
> (I was going to share a trick to get that box to render centered on _any_ browser, incl. 3.2 non-JS ones)
> 
> Also you forgot the `</head>` tag.

@paulwratt @linusg I can't believe I forgot the `<head>` tag, I'll fix that.

2022-02-22 22:42 UTC, electrikmilk commented
> 

That's a fair point, I will fix and use `<meta charset="utf-8">` instead as it's the shortest most modern way.

Serenity is more about the *look* from what I understand, but with modern guts, so I'm not looking to use the `<center>` tag or tables because the `<center>` tag is (deprecated)[https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center] and tables are not a modern way of organizing content, we are looking to make our technology and usage as modern as possible. I think it's laudable that the page shouldn't be too complicated.

2022-02-23 03:02 UTC, electrikmilk commented
Removed `<!-- Last Modified... -->` comment and ended `<head>` tag properly in latest commit.

2022-02-23 09:58 UTC, linusg requested changes

2022-02-23 09:58 UTC, linusg commented on Base/www/index.html
> +</html>
Please configure your editor to add a newline to the end of files

2022-02-23 09:58 UTC, linusg commented on Base/www/other.html
> +</html>
Please configure your editor to add a newline to the end of files

2022-02-23 09:58 UTC, linusg commented on Base/www/other.html
> +  </style>
head tag still missing here

2022-02-23 13:19 UTC, electrikmilk commented
Should be all fixed in latest push.

2022-02-23 20:26 UTC, linusg requested changes
Now the indentation changed from spaces to tabs for some reason :neutral_face:
Please just run prettier over them?

2022-02-23 21:12 UTC, electrikmilk commented
> Now the indentation changed from spaces to tabs for some reason :neutral_face:
> 
> Please just run prettier over them?

I had reformatted, I didn't know spaces were preferred, sorry!

2022-02-23 21:23 UTC, linusg commented
I would've complained if spaces wasn't right :^)

2022-02-23 21:28 UTC, linusg approved these changes
Awesome, thanks!

2022-02-23 21:28 UTC, merged

2022-02-23 21:47 UTC, electrikmilk commented
> I would've complained if spaces wasn't right :^)

That's fair, used a different text editor to try and add a new line to the end of them, I'll remember not to reformat using that editor in the future lol.