LibIPC/Meta: Clean up the IPC-compiler a bit
SerenityOS/serenity pull request #12735
Opened 2022-02-22 21:03 UTC by Hendiadyoin1

#### AK: Make SourceGenerator move constructible

#### This makes us able to return one form a function

#### AK: Explicitly move value String in SourceGenerator::set

#### AK: Add appendln helper to SourceGenerator

#### LibIPC: Add IPCErrorOr Type alias

#### Meta: Refactor the IPC-compiler and port it to LibMain

This does a few things in total:
* Ports the IPC-compiler to LibMain
* Extract some compiler steps into separate functions
* Minify some appends to use appendln (or appendff in the case of
  StringBuilder)

This reduces the clang-tidies maximum cognitive-complexity score for
this file from 325 to under 100.

2022-02-22 21:33 UTC, kleinesfilmroellchen commented on Userland/Libraries/LibIPC/Message.h
> +using IPCErrorOr = Result<Value, ErrorCode>;
Let's use ErrorOr instead.

2022-02-22 21:33 UTC, kleinesfilmroellchen commented on Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
> +    message_generator.appendln(R"~~~(
This appendln should have the ending newline in the string removed.

2022-02-22 21:43 UTC, kleinesfilmroellchen approved these changes

2022-02-23 13:55 UTC, AtkinsSJ commented
Nice work! It would be easier to review if that last commit was broken into the three parts listed in the commit message, but it's probably too late to be able to do that now. When code gets moved and changed in the same commit, the diff becomes a big mess.

If you wanted to take it a step further, it would be nice if you used the new Core::Stream::File API instead of Core::File, which is theoretically going away soon.

2022-03-07 12:31 UTC, Hendiadyoin1 commented
I don't know how to `Core::InputFileStream` works, so the conversion should be done by someone with that knowledge at hand

2022-03-09 11:00 UTC, AtkinsSJ requested changes
I spotted a couple of small issues but mostly this is fine. Just, I'm not convinced that replacing a lot of the R-strings is an improvement. eg, this:
```c++
endpoint_generator.append(R"~~~(
                dbgln("@endpoint.name@: Endpoint magic number message_endpoint_magic != @endpoint.magic@, not my message! (the other endpoint may have handled it)");
)~~~");
```
seems easier to read to me than this:
```c++
generator.appendln("\n                dbgln(\"@endpoint.name@: Endpoint magic number message_endpoint_magic != @endpoint.magic@, not my message! (the other endpoint may have handled it)\")");
```
I don't think anyone wants to have to manually type out indentation inside a string, counting that it's the correct number of spaces.

2022-03-13 10:54 UTC, Hendiadyoin1 commented on Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
> +    auto message_generator = generator.fork();
> I spotted a couple of small issues but mostly this is fine. Just, I'm not convinced that replacing a lot of the R-strings is an improvement. eg, this:
> 
> ```c++
> endpoint_generator.append(R"~~~(
>                 dbgln("@endpoint.name@: Endpoint magic number message_endpoint_magic != @endpoint.magic@, not my message! (the other endpoint may have handled it)");
> )~~~");
> ```
> 
> seems easier to read to me than this:
> 
> ```c++
> generator.appendln("\n                dbgln(\"@endpoint.name@: Endpoint magic number message_endpoint_magic != @endpoint.magic@, not my message! (the other endpoint may have handled it)\")");
> ```
> 
> I don't think anyone wants to have to manually type out indentation inside a string, counting that it's the correct number of spaces.

Sure I will revert these changes then

2022-03-13 10:57 UTC, Hendiadyoin1 commented
I spotted a couple of small issues but mostly this is fine. Just, I'm not convinced that replacing a lot of the R-strings is an improvement. eg, this:

    endpoint_generator.append(R"~~~(
                    dbgln("@endpoint.name@: Endpoint magic number message_endpoint_magic != @endpoint.magic@, not my message! (the other endpoint may have handled it)");
    )~~~");

    seems easier to read to me than this:

    generator.appendln("\n                dbgln(\"@endpoint.name@: Endpoint magic number message_endpoint_magic != @endpoint.magic@, not my message! (the other endpoint may have handled it)\")");

    I don't think anyone wants to have to manually type out indentation inside a string, counting that it's the correct number of spaces.

Sure I will revert these changes then

2022-03-13 10:57 UTC, Hendiadyoin1 commented on Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
> +    auto message_generator = generator.fork();
Turns out I forked on-call aswell....

2022-03-28 21:08 UTC, merged