LibGfx: Add `try_request_resource`
SerenityOS/serenity pull request #12731
Opened 2022-02-22 19:40 UTC by filiphsandstrom

This method provides a way for an application to automatically
lookup an icon/resource based on it's name.

A nice bonus we get from this is the ability for users
(including non-root) to configure a custom lookup path which means
that we now have support for custom icon and resource themes :^)

(This greatly benefits Lagom+LibGUI where widgets with hard-coded icon paths is a huge problem).

TL;DR: No more hard-coded res/icon paths :rocket:

2022-02-22 21:01 UTC, linusg requested changes
Nice idea in general, but a massive footgun as currently implemented. Plenty of these will break if someone adds a 16px variant for a currently 32px icon, two applications have an image of the same name each in their own directory, etc.
Automaticcally determining the base path seems fine, more than that not so much.

2022-02-22 21:03 UTC, filiphsandstrom commented
> Nice idea in general, but a massive footgun as currently implemented. Plenty of these will break if someone adds a 16px variant for a currently 32px icon, two applications have an image of the same name each in their own directory, etc. Automaticcally determining the base path seems fine, more than that not so much.

I agree, should probably implement the scaling factor handling to make sure we don't serve the wrong size.
I'm just about to push a commit that adds a nice `lookup` table for previously requested  resources.

2022-02-22 21:17 UTC, filiphsandstrom commented on Userland/Libraries/LibGfx/Bitmap.cpp
> +    recursive = [&](String path, Vector<String>* known_paths) {
That wouldn't work for the Vector since I'm using `append` method; unless I've misunderstood something?

2022-02-22 21:25 UTC, linusg commented on Userland/Libraries/LibGfx/Bitmap.cpp
> +    recursive = [&](String path, Vector<String>* known_paths) {
ah, right, still can be a reference though

2022-02-22 22:09 UTC, filiphsandstrom commented
> Nice idea in general, but a massive footgun as currently implemented. Plenty of these will break if someone adds a 16px variant for a currently 32px icon, two applications have an image of the same name each in their own directory, etc. Automaticcally determining the base path seems fine, more than that not so much.

This is now resolved with the added scaling support :^)

2022-02-23 13:24 UTC, filiphsandstrom commented
Gonna rethink the per-application approach since the lookup needs to prioritize app-specific icons first, then global and the finally other apps’ icons.

2022-02-26 02:13 UTC, closed without merging