Ports: Upgrade to FFmpeg 5.0 and make it run well
SerenityOS/serenity pull request #12828
Opened 2022-03-01 09:30 UTC by rouseabout

Previously the FFmpeg port would build, but did not actually work (!).

To test inside SerenityOS type `ffplay ~/Videos/test-webm.webm` into the terminal.

2022-03-01 12:06 UTC, kleinesfilmroellchen requested changes

2022-03-01 12:06 UTC, kleinesfilmroellchen commented on Userland/Libraries/LibC/mallocdefs.h
> +    [[gnu::aligned(16)]] unsigned char* m_slot[0];
Please just use standard `alignas(16)`.

2022-03-01 12:06 UTC, kleinesfilmroellchen commented on AK/PrintfImplementation.h
> +        }
For these single line if's, we can get rid of the braces.

2022-03-01 12:06 UTC, kleinesfilmroellchen commented on Ports/ffmpeg/package.sh
> +        --arch="${SERENITY_ARCH}" \
Does this work even though our 32-bit arch is `i686` and not `x86_32` as the configure script received before?

2022-03-01 12:30 UTC, kleinesfilmroellchen commented
Great work! I've tested with the standard test video as well as FLAC, WAV and MP3, and they all work great including the spectral display.

2022-03-01 13:46 UTC, paulwratt commented
hmm.. successfully tested - one step away from live streaming the desktop to Twitch ..

2022-03-02 10:39 UTC, awesomekling commented on Userland/Libraries/LibC/inttypes.h
> +#define PRIX16 "X"
Our `printf` used to support `%b` and `%w` as shorthand for 8-bit and 16-bit values. That's where it came from :^)

2022-03-02 10:40 UTC, awesomekling commented on Ports/ffmpeg/patches/errno-is-not-valid-during-cpp.patch
> +-#if EDOM > 0
Oh my, that is an unfortunate construct..

2022-03-02 10:40 UTC, merged