Ports: Fix harbuzz package.sh cmake syntax
SerenityOS/serenity pull request #12966
Opened 2022-03-09 15:00 UTC by archanox

2022-03-10 04:29 UTC, archanox commented
> https://cmake.org/cmake/help/v3.23/manual/cmake.1.html suggests that the current syntax is correct.
> 
When left as is with cmake 3.18.4 (the current version shipped with Ubuntu 20.10) we get the following message when running package.sh

```
Configuring harfbuzz...
+ mkdir -p build
+ sh -c cd build && cmake -DCMAKE_TOOLCHAIN_FILE=/home/pierce/serenity/Build/i686/CMakeToolchain.txt -DHB_HAVE_FREETYPE=ON -DHB_HAVE_ICU=ON ..
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


CMake Error: The source directory "/home/pierce/serenity/Ports/harfbuzz/harfbuzz-2.8.1/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```
After rearranging the params as per this PR we get a successful build
```
Configuring harfbuzz...
+ mkdir -p build
+ sh -c cd build && cmake .. -DCMAKE_TOOLCHAIN_FILE=/home/pierce/serenity/Build/i686/CMakeToolchain.txt -DHB_HAVE_FREETYPE=ON -DHB_HAVE_ICU=ON
-- The C compiler identification is GNU 11.2.0
```
etc etc

2022-03-10 13:43 UTC, linusg requested changes
The cmake change is still not explained in the commit message. Additionally, there are other ports using the same syntax.

2022-03-10 13:43 UTC, linusg commented on Ports/diffutils/package.sh
> +config_sub_path=build-aux/config.sub
Please insert these after `use_fresh_config_sub` consistently, and not sometimes after `version` and sometimes not.

2022-03-12 11:27 UTC, archanox commented
> The cmake change is still not explained in the commit message. 

Fixing that now.
> Additionally, there are other ports using the same syntax.

Do you have a list of the specific ports in question? I'd like to investigate those further. I do see a mish-mash of build locations specified as parameter and as not, there's varying configurations of where built source is located. All in all, it's a bit of a mess that can be cleaned up iteratively.

I'd like to ship this as a preliminary step in getting Ports working out of the box.

2022-03-15 14:03 UTC, merged