Toolchain: Fix the gdb build for aarch64 target on OSX host
SerenityOS/serenity pull request #13393
Opened 2022-03-31 23:09 UTC by jamesmintram

This PR adds a branch in the code to build GDB to add support for building on an OSX host. The relevent additions to the configure step are

```
 --disable-werror \
--with-libgmp-prefix="`brew --prefix gmp`" \
--with-gmp="`brew --prefix gmp`" \
--with-isl="`brew --prefix isl`" \
--with-mpc="`brew --prefix libmpc`" \
--with-mpfr="`brew --prefix mpfr`" \
```

This assumes brew has been used to install the required libs - but the build instructions also assume brew is used.

2022-03-31 23:26 UTC, bgianfo commented
Looks like shellcheck isn't happy?

2022-04-01 10:10 UTC, jamesmintram commented
> Looks like `shellcheck` isn't happy?

@bgianfo fixed

2022-04-01 16:44 UTC, linusg requested changes
OS X hasn't been called OS X since 2016, please use `macOS` or `Darwin`.

2022-04-01 18:10 UTC, jamesmintram commented
> OS X hasn't been called OS X since 2016, please use `macOS` or `Darwin`.

Done

2022-04-01 18:39 UTC, merged