top: add support for quitting top by pressing q
SerenityOS/serenity pull request #13417
Opened 2022-04-01 19:49 UTC by jamesmintram

This PR adds support for quitting `top` by pressing q. This was the behaviour I expected based on other "top"s

2022-04-01 20:42 UTC, linusg requested changes

2022-04-01 20:42 UTC, linusg commented on Userland/Utilities/top.cpp
> +    return true;
?

2022-04-01 20:42 UTC, linusg commented on Userland/Utilities/top.cpp
> +            }
Please omit curly braces for single-line bodies

2022-04-01 21:12 UTC, jamesmintram commented on Userland/Utilities/top.cpp
> +    return true;
Good catch :-O

2022-04-02 12:21 UTC, linusg reviewed
Lowercase top for the prefix was correct, not sure why you changed it.

2022-04-02 13:15 UTC, jamesmintram commented
> Lowercase top for the prefix was correct, not sure why you changed it.

Changed it where?

2022-04-02 13:17 UTC, linusg commented
In the commit message - or maybe I'm misinterpreting it, at least the PR title has it right. Either way, please update.

2022-04-02 13:21 UTC, jamesmintram commented
> In the commit message - or maybe I'm misinterpreting it, at least the PR title has it right. Either way, please update.

Done.

2022-04-02 22:48 UTC, merged