GMLPlayground+LibGUI: Dont clear undo_stack when modifying text
SerenityOS/serenity pull request #13633
Opened 2022-04-11 22:01 UTC by SimonFJ20

Extracted the text modifying part of `TextDocument::set_text()` out into a new method `TextDocument::modify_text()`. So that `modify_text` can be used, when caller doesn't want to clear the `undo_stack`.

`set_text` is used, for example when loading files, where we dont want to be able to undo to the file before. `modify_text` can be used, for example by GMLPlayground to format text, while still being able to undo and the `window->is_modified()` intact.

Closes #11810

2022-04-11 22:04 UTC, awesomekling commented
Hmm, intuitively it feels like we should generate an undo item for "GML auto-formatting" instead of just bypassing the undo stack.

2022-04-12 21:08 UTC, SimonFJ20 commented
I have made a new DocumentUndoCommand called ReplaceAllTextCommand, which as its name suggests replaces all the text with new text (ie. unformatted gml code with formatted gml code in GML Playground).

Playground can now format code, while maintaining the undo stack and also the 'unsaved changes' window state.

I can't quite figure out how to avoid crashing when undoing after a format, so that needs to be fixed.

As I'm not sure what the next step here is, I'm just gonna set the PR up for review and respond to feedback.

2022-04-13 10:23 UTC, awesomekling requested changes
Thank you so much for working on this! :^)

Please rebase your PR branch and get rid of the first commit and subsequent revert, we don't need to preserve those.

2022-04-13 10:23 UTC, awesomekling commented on Userland/Libraries/LibGUI/TextDocument.cpp
> +    return "Playground format text";
This text is specific to the Playground application, but we're in LibGUI here so we'll want to make this more generic.

Even better: we can make it customizable! The `ReplaceAllTextCommand` can take a constructor parameter with an override text. That way, we can set a custom undo item string whenever generating this command.

2022-04-13 10:23 UTC, awesomekling commented on Userland/Libraries/LibGUI/TextEditor.h
> +    void replace_all_text_while_keeping_undo_stack(StringView text);
The `while_keeping_undo_stack` suffix here is a little bit misleading, as it sounds like *nothing* happens to the undo stack.
`without_resetting_undo_stack` perhaps?

2022-04-13 19:24 UTC, merged