Ports: Add port aria2 version 1.36.0
SerenityOS/serenity pull request #13665
Opened 2022-04-14 00:15 UTC by EWouters

I ported aria2, however I can't get it to work.

- [ ] Fails to find `libxml2` so I have to pass `--without-libxml2`
- [ ] Error `--max-mmap-limit`
![image](https://user-images.githubusercontent.com/6179932/163289101-17c208f8-e984-4a58-b2b8-6ad90dc73ccf.png)

2022-05-14 21:09 UTC, EWouters commented
Currently blocked on #13915.

2022-05-21 17:36 UTC, timschumi commented
It might be worth checking if `libxml2` can now be found after 139f9039607ef3972a11b2085ce798f9759aac9d has been merged.

2022-05-21 21:14 UTC, EWouters commented
It can find `libxml2` fine now,  but the numeric over/under-flow error is still there.

2022-06-17 10:12 UTC, timschumi requested changes
The number parsing issue should be fixed by #14313.

2022-06-17 10:12 UTC, timschumi commented on Ports/aria2/package.sh
> +version="1.36.0"
Should be single quotes, same with `auth_type` and `useconfigure`.

2022-06-17 10:12 UTC, timschumi commented on Ports/aria2/package.sh
> +configopts+=("--with-libuv")
Needs `--with-sysroot=${SERENITY_INSTALL_ROOT}` and should be split up across multiple lines.

2022-06-17 10:12 UTC, timschumi commented on Ports/aria2/package.sh
> +}
This is not needed, the tarball ships in an already configured state.

2022-06-17 10:12 UTC, timschumi commented on Ports/aria2/patches/0001-Add-Serenity-to-config.sub.patch
> +Subject: [PATCH 1/2] Add Serenity to config.sub
Please replace this patch with `config_sub_paths` in the `package.sh` script.

2022-06-17 10:12 UTC, timschumi commented on Ports/aria2/patches/0002-Include-sys-select.h.patch
> +From 839f9ff4a68a40d77e873a63531394eb4af8e50b Mon Sep 17 00:00:00 2001
Please regenerate this using a current version of `./package.sh dev` to get rid of the unnecessary metadata.

2022-07-15 23:57 UTC, closed without merging

2022-08-13 15:31 UTC, EWouters commented
It somewhat works now :^)

<img width="825" alt="image" src="https://user-images.githubusercontent.com/6179932/184497742-fb014007-a929-423e-83c5-f2c30eb10539.png">