AK: Add explicit clobbers for x87 stack usage to math helpers
SerenityOS/serenity pull request #13795
Opened 2022-04-25 13:56 UTC by Hendiadyoin1

This should help with some FPU exceptions when trying to build with
clang-14.

Sadly clang does not seem to generate x87's constant load instructions
for ln(2) and lg(2).

This also adjusts the formatting of the assembly in this file to be a
bit more consistent.

CC: @timschumi

2022-04-29 20:54 UTC, linusg requested changes
Please split the formatting changes into a separate commit, that's a lot of noise.

2022-04-29 20:59 UTC, timschumi requested changes

2022-04-29 20:59 UTC, timschumi commented on AK/Math.h
> +    // Fixme: I am naive
Some editors only recognize `FIXME`, and we usually use that in all the other places as well (even in this PR).

2022-05-29 16:37 UTC, timschumi approved these changes
Looks reasonable as far as I can tell, and I haven't found any obvious issues while testing.

2022-06-05 23:25 UTC, closed without merging