Documentation: Document how the event loop works & what it does
SerenityOS/serenity pull request #13892
Opened 2022-05-02 22:15 UTC by kleinesfilmroellchen

This was long overdue; as of writing this I saw another question about something that seems obvious to me who spent a bunch of time with the system.

Hopefully this is generic enough so that we can change things without this getting out of date.

2022-05-02 22:26 UTC, GMTA commented on Documentation/EventLoop.md
> +-   DO NOT access the current event loop if you don't know on which thread you are running. If there is no event loop on your thread, the program will crash. DO recieve the specific event loop you ne
```suggestion
-   DO NOT access the current event loop if you don't know on which thread you are running. If there is no event loop on your thread, the program will crash. DO receive the specific event loop you need to talk to as an initializer variable.
```

2022-05-02 22:29 UTC, GMTA commented
You mention the event loop stack a couple of times, but not why it exists. Maybe give an example of a common use case of the event loop stack?

2022-05-03 10:41 UTC, GMTA commented on Documentation/EventLoop.md
> +The **event loop stack** is mainly used for nesting GUI windows. Each window adds another event loop onto the stack, and remaining events are added to the lower event loop's queue when it exist. The
```suggestion
The **event loop stack** is mainly used for nesting GUI windows. Each window adds another event loop onto the stack, and remaining events are added to the lower event loop's queue when it exits. The purpose behind this system is that `GUI::Window`s and other systems which provide their own event loop can just create and run this class depending on global variables without interfering with other event loops.
```

2022-05-03 10:42 UTC, GMTA requested changes
LGTM, just a small typo!

2022-05-03 18:38 UTC, ADKaster commented on Documentation/EventLoop.md
> +-   To fire an event on a `Core::Object` the next time the event loop runs, `EventLoop::post_event()` exists.
Inverting the subject/object here feels more natural

> `EventLoop::post_event()` allows calling code to fire an event targeting a specific `Core::Object` the next time the event loop is pumped.

2022-05-03 21:04 UTC, merged