LibGUI + Browser: Add Vertical Tabs
SerenityOS/serenity pull request #14002
Opened 2022-05-10 16:03 UTC by cammo1123

## LibGUI::TabWidget
Add Vertical tabs to GUI::TabWidget, This can be set using one of the two new TabWidget::TabPosition's

```cpp
enum TabWidget::TabPosition { Top, Bottom, Left, Right };
// or by using 
void set_tab_position(TabWidget::TabPosition position);
```
## Browser
Using the new TabLayouts the browser now has a new key combination ``` CTRL + , ``` that switches between a ```Top``` positioned  and a ```Left``` positioned tab layout.

![image](https://user-images.githubusercontent.com/36214028/167670085-b014fa44-52cb-44c2-af10-b422f6f33e7a.png)

2022-05-10 16:10 UTC, linusg commented on Userland/Libraries/LibGfx/ClassicStylePainter.cpp
> +    if (position == 0) {
That's no reason to make the code worse :)

2022-05-10 16:10 UTC, networkException commented on Userland/Libraries/LibGfx/ClassicStylePainter.cpp
> +    if (position == 0) {
In my opinion that optimization is not worth the worse readability

2022-05-11 12:49 UTC, kleinesfilmroellchen requested changes
Please add the tab position to GML with `REGISTER_ENUM_PROPERTY`.

2022-05-11 12:49 UTC, kleinesfilmroellchen commented on Userland/Libraries/LibGUI/TabWidget.cpp
> +Gfx::IntRect TabWidget::horz_button_rect(size_t index) const
Don't uselessly abbreviate here. Use `vertical` and `horizontal`.

2022-05-11 12:49 UTC, kleinesfilmroellchen commented on Userland/Libraries/LibGfx/ClassicStylePainter.cpp
This commit should be squashed with the first one.

2022-05-11 12:49 UTC, kleinesfilmroellchen commented on Userland/Libraries/LibGfx/ClassicStylePainter.cpp
> +    if (position == GUI::TabWidget::TabPosition::Top) {
It looks like this is a hand-rolled switch case.

2022-05-11 13:46 UTC, cammo1123 commented
Commits have been squished, and all issues pointed out to me have been resolved (as far as I know)
- [x] Added GML support

2022-05-11 15:10 UTC, AtkinsSJ commented on Userland/Libraries/LibGUI/TabWidget.cpp
> +        { TabPosition::Right, "Right" }, );
Can you also add this property to the table in https://github.com/SerenityOS/serenity/blob/master/Base/usr/share/man/man5/GML-Widget-TabWidget.md?

2022-05-11 15:44 UTC, kleinesfilmroellchen approved these changes

2022-05-11 15:44 UTC, kleinesfilmroellchen commented on Userland/Libraries/LibGUI/TabWidget.cpp
> +#include "LibCore/Object.h"
Angle bracket includes, please

2022-05-11 20:48 UTC, cammo1123 commented
Sorry for all the force commits. I'm not too familiar with git, and I had to resolve some conflicts. It should be all up to date and conflict-free now!

2022-05-11 21:30 UTC, kleinesfilmroellchen approved these changes

2022-05-13 07:05 UTC, AtkinsSJ commented
You've ended up with a merge commit in there. You can remove it with `git rebase -i master` and then deleting the line with that commit. (Make sure you don't delete anything else though! But if you do, you can rescue it still, ask on Discord about that.)

There are ways of avoiding creating merge commits in the first place, but I don't remember them off the top of my head.

2022-05-13 07:58 UTC, closed without merging