Utilities: Refactor and improve du
SerenityOS/serenity pull request #14170
Opened 2022-06-02 05:48 UTC by SeekingBlues

* Make sure the size calculation is correct even if `--max-depth` or `--threshold` is specified.
* Correctly implement apparent size calculation (`st_size`).
* Improve POSIX correctness by using a default block size of 512 bytes and including the size of directories themselves.
* Add more options.
* Clarify some documentation.

Fixes #12899.

2022-06-02 11:22 UTC, timschumi requested changes
Coincidentally, this also checks off a point in #12303.

That said, this is way too much for a single commit. Please split it up into separate commits, which should also make it less impossible to review.

2022-06-02 20:33 UTC, SeekingBlues commented
Sorry, I totally forgot about splitting the commits. Hopefully this looks better. Let me know if there is anything that I can improve.

2022-06-16 13:11 UTC, Hendiadyoin1 commented on Userland/Utilities/du.cpp
> +    if (is_directory) {
The check against the maximum recursion depth seems to be missing now

2022-06-16 13:11 UTC, Hendiadyoin1 commented on Userland/Utilities/du.cpp
> +        out("{}", howmany(size, block_size));
`ceil_div` from `AK/StdLibExtras.h` might be even better.

2022-06-16 13:11 UTC, Hendiadyoin1 commented on Userland/Utilities/du.cpp
> +        Change
This seems like an unrelated change.

2022-06-16 13:11 UTC, Hendiadyoin1 commented on Userland/Utilities/du.cpp
> +            out("{}", howmany(size, block_size));
-> `ceil_div`

2022-07-15 02:04 UTC, closed without merging