LibGUI: Draw scrollbar buttons as triangles, and make the draw_triangle function symmetric
SerenityOS/serenity pull request #14282
Opened 2022-06-15 02:22 UTC by frhun

This changes the arrows on the scrollbar buttons from hard coded bitmaps to being drawn as triangles.
Apart from arguably being more elegant (although less simple), this lays the groundwork to have them scaled for HIDPI once the necessary changes to the painter and window back store are done.

To enable this, I had to rewrite the draw_triangle function to be symmetrical. Because prior to this, the same triangle would be rendered differently depending on the direction it faced. You can simply have a look at this by compiling this at the commit before the re implementation of draw_triangle, you will see that triangles on the scrollbar buttons all look slightly different.

2022-06-15 16:46 UTC, AtkinsSJ commented on Userland/Libraries/LibGfx/Painter.cpp
> +    VERIFY(control_points.size() >= 3);
It feels like this should be `== 3` instead. What does a triangle with > 3 corners mean?

2022-06-15 23:10 UTC, MacDue requested changes

2022-06-15 23:10 UTC, MacDue commented on Userland/Libraries/LibGUI/Scrollbar.cpp
> +static const AK::Vector<Gfx::IntPoint, 3> s_up_arrow_coords {
These static arrays don't need to by `Vectors`, just make them `constexpr Arrays`.

2022-06-15 23:10 UTC, MacDue commented on Userland/Libraries/LibGUI/Scrollbar.cpp
> +static const AK::Vector<Gfx::IntPoint, 3> s_down_arrow_coords {
(same here and the other ones)

2022-06-15 23:10 UTC, MacDue commented on Userland/Libraries/LibGfx/Painter.cpp
> +void Painter::draw_triangle(IntPoint offset, AK::Vector<IntPoint> const& control_points, Color color)
`control_points` should be a `Span<const IntPoint> rather than `AK::Vector<IntPoint> const&` there's no reason for this to be specific to `Vector`.

2022-06-16 16:34 UTC, MacDue commented
There's no reason to pass a `Span` by const reference, since a `Span` is a reference (it's like `StringView` for Vectors/Arrays). 

Also can (and probably should) omit the AK:: prefix (since AK is in the global namespace).

2022-06-16 21:31 UTC, frhun commented
> There's no reason to pass a `Span` by const reference, since a `Span` is a reference (it's like `StringView` for Vectors/Arrays).
> 
> Also, you can (and probably should) omit the AK:: prefix (since AK is in the global namespace).

Done

2022-06-20 11:40 UTC, AtkinsSJ approved these changes
Lgtm!

2022-06-20 11:40 UTC, merged