Docs: FAQ: Grammar - Word order/sentence structure
SerenityOS/serenity pull request #14483
Opened 2022-07-04 21:22 UTC by Jonta

The original wording had a different meaning, that I'm pretty sure was not the intended one. :^)

2022-07-04 21:26 UTC, linusg requested changes
There's no such prefix as `Docs`, that's `Documentation`. Also

> Write the commit message subject line in the imperative mood ("Foo: Change the way dates work", not "Foo: Changed the way dates work").

2022-07-05 15:13 UTC, Jonta commented
Ah yes. "Docs" is an old habit from projects with less rigid requirements

I was very unsure of the commit message, wanting to keep it at or below 50 characters as well

"Documentation: Restructure wording" fits, but if I had the space, I would've chosen something like "Documentation: Restructure wording to align with intended meaning"

2022-07-06 00:22 UTC, MacDue commented
@Jonta `Documentation: Restructure wording to align with intended meaning` is fine as the limit is 72 characters not 50. 
Also you've only changed the title of your PR not your commit message. To change the commit message do:
```
git commit --amend
<update the title>
git push -f 
```

2022-10-01 18:25 UTC, Jonta commented
Activity

2022-10-01 21:29 UTC, linusg commented
Please just update the PR if you intend to make it mergeable, instead of artificially keeping it alive.

2022-10-02 21:17 UTC, Jonta commented
> Please just update the PR if you intend to make it mergeable, instead of artificially keeping it alive.

- I predict that's not going to happen for at least another 2 months
- Hence closing this for now

2022-10-02 21:17 UTC, closed without merging