Everywhere: Make the codebase more architecture aware
SerenityOS/serenity pull request #14651
Opened 2022-07-22 20:04 UTC by Undefine-Unity

Mainly not assuming that not X86_64 is I686 and in reverse.

2022-07-26 09:53 UTC, linusg requested changes
I'm very much in favour of explicit arch macro branches and banning `#else` for this purpose, but not like this - pick one of `#error Unknown architecture`, `TODO()` or stub code, not all of them. Preferably the first.

2022-07-27 01:00 UTC, bgianfo commented on Userland/Utilities/functrace.cpp
> +
Extra newline here?

2022-07-27 01:03 UTC, bgianfo commented on Userland/Libraries/LibC/string.cpp
> +#elif !ARCH(X86_64)
nit: Please make this a normal if/else check and then move the comment about the x86_64 assembler implementation into the `ARCH(X86_64)` check, and add a standard `#else` + Unknown architecture message.

2022-07-27 21:46 UTC, bgianfo approved these changes
LGTM!

2022-07-27 21:46 UTC, merged