LibGUI: Allow GlyphMapWidget to highlight modified glyphs
SerenityOS/serenity pull request #14708
Opened 2022-07-27 15:48 UTC by AtkinsSJ

![image](https://user-images.githubusercontent.com/222642/181291735-50f15c42-85f6-4bef-ab88-80de25c52e27.png)

This makes modifications in FontEditor more visible, both so you know
what you've changed, and for taking a handy "here's what's changed"
screenshot for a font PR. :^)

The background color for new glyphs is green, modified glyphs is blue,
and deleted glyphs is red. The changes persist until you load a new
font file, so you can continue saving your work as you go and still be
able to take a convenient screenshot at the end.

FontEditor does not currently mark glyphs as unmodified if you undo a
change you made though.

2022-07-27 18:40 UTC, djwisdom commented
More love to FontEditor. ❤️

2022-07-30 18:58 UTC, TobyAsE approved these changes
Lgtm, very nice addition!

Some sort of documentation would be nice as to not guess what the colours mean. Tooltip maybe, or a legend somewhere... But that's :ideaguying:

2022-07-30 19:21 UTC, Xexxa requested changes
I love this addition. I would love it even more if there was an on/off option.

2022-08-02 13:43 UTC, AtkinsSJ commented
Thanks everyone! I wasn't initially sure if this was a desired feature. I've improved it a bit:
- Tweaked the colours because I wasn't happy with them.
- Added darker versions of the colours when the theme is dark. (A proper solution might be to add color-roles for them, but it felt excessive for one application. If we end up with other apps wanting "created/modified/deleted" colours then we can move it into the theme then.)
- Added undo support.
- Add a menu option to show or hide the highlights.

New screenshots are in the first post. :^)

2022-08-05 15:56 UTC, AtkinsSJ commented
Fixed a merge conflict.

2022-08-05 19:33 UTC, thankyouverycool approved these changes

2022-08-14 10:00 UTC, TobyAsE approved these changes

2022-08-14 12:59 UTC, merged