LibJS: Avoid calling ToString on calendar when calendarName is "never"
SerenityOS/serenity pull request #14807
Opened 2022-08-08 13:51 UTC by Lubrsi

This is a normative change in the Temporal spec.

See:
- https://github.com/tc39/proposal-temporal/commit/6122f4e
- https://github.com/tc39/proposal-temporal/commit/cf586bc

2022-08-08 17:32 UTC, linusg requested changes

2022-08-08 17:32 UTC, linusg commented on Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
> +ThrowCompletionOr<String> maybe_format_calendar_annotation(GlobalObject& global_object, Value calendar_object, StringView show_calendar)
`calendar_object` should be an `Object&` (`Object const&`?)

2022-08-23 18:09 UTC, linusg commented
Ping @Lubrsi in case you forgot about this PR :)

2022-08-25 19:59 UTC, linusg commented on Userland/Libraries/LibJS/Runtime/Temporal/Calendar.cpp
> +ThrowCompletionOr<String> maybe_format_calendar_annotation(GlobalObject& global_object, Value calendar_object, StringView show_calendar)
Actually, I was wrong about this - the spec says it must be an object, but it's called with undefined in at least one place. Will file a spec fix.

2022-08-25 20:00 UTC, Lubrsi commented
Oh yeah, sorry, I'll rebase it now.

2022-08-25 20:07 UTC, linusg commented
Already done :^)

2022-08-25 20:11 UTC, merged