PixelPaint: Added scaling function to move tool
SerenityOS/serenity pull request #14806
Opened 2022-08-08 12:35 UTC by tommasopeduzzi

This patch adds scaling function to the move tool. When the move tool is selected and the mouse is over the lower right corner of the layer, the cursor changes to signify, that the layer can be scaled by dragging the mouse.
There is currently no preview of the scaling, as doing a resize every time the mouse moves leads to unexpected behaviour, where the image isn't scaled properly and is cut off. The image can also only be scaled from the lower right corner.
Maybe it would be smarter to add a new "scale" tool to do this, or rename the move tool to "translate" tool, to signify these changes.

2022-08-08 12:50 UTC, MacDue requested changes
You need to run clang format over your code via `./Meta/lint-clang-format.sh` or the pre-commit hook (see in the docs). 

Also your commit should be `PixelPaint: Add scaling function to move tool` (present tense).

2022-08-08 12:52 UTC, MacDue commented
Also, when adding a new feature it's better to add a little video clip or screenshot to your PR than try to describe it.

2022-08-10 12:18 UTC, tommasopeduzzi commented
@MacDue Thanks for feedback, I have now implemented it!

2022-08-12 09:40 UTC, TobyAsE commented
Welcome @tommasopeduzzi to the Serenity Project!

This seems like a very sensible addition to PP.
I doesn't need to go into this PR but some things I'd like to see regarding this feature:
- Keep aspect ratio when a modifier (ctrl or shift) is pressed
- While a fully-fledged preview is hard as you mentioned, you can use on_second_paint to paint the outline of the new size at least, that would be helpful.

2022-08-12 09:46 UTC, TobyAsE reviewed
Very nice addition, I've left some comments.
Also, there seems to be an empty line between every line in your commit message, I don't think that's intended :^)

2022-08-12 09:46 UTC, TobyAsE commented on Userland/Applications/PixelPaint/Tools/MoveTool.h
> +    bool m_is_in_lower_right_corner = false;
We usually initialize members using braces, so `bool m_scaling { false };`

2022-08-12 09:46 UTC, TobyAsE commented on Userland/Applications/PixelPaint/Tools/MoveTool.h
> +    bool m_is_in_lower_right_corner = false;
I prefer the name `m_mouse_in_resize_corner` or something along these lines, to make clear _what_ is in _which_ corner and for _what function_.

2022-08-12 09:46 UTC, TobyAsE commented on Userland/Applications/PixelPaint/Tools/MoveTool.cpp
> +    auto sensitivity = 20;
This can be a `constexpr int` to signify its constant-ness.

2022-08-12 09:46 UTC, TobyAsE commented on Userland/Applications/PixelPaint/Tools/MoveTool.cpp
> +#include <LibGUI/Painter.h>
Is this needed?

2022-08-12 09:46 UTC, TobyAsE commented on Userland/Applications/PixelPaint/Tools/MoveTool.cpp
> +    auto updated_is_in_lower_right_corner = Gfx::IntRect(Gfx::IntPoint(layer->location().x() + layer->size().width() - sensitivity / 2, layer->location().y() + layer->size().height() - sensitivity /
For readability I'd split this huge thing into multiple locals.
Consider building a `Gfx::IntRect grab_rect` and `Gfx::IntPoint grab_rect_position` separately.

2022-08-12 14:44 UTC, tommasopeduzzi commented
Thanks @TobyAsE! I have implemented your suggestions.
These two additions are on my TODO, I will implement them in the near future :^)

2022-08-13 09:00 UTC, TobyAsE approved these changes

2022-08-13 09:01 UTC, TobyAsE commented
Very cool, looking forward to the PRs :^)

2022-08-13 14:47 UTC, tommasopeduzzi commented
@TobyAsE I implemented the feature, where it keeps the aspect ratio, when the shift key is pressed. I am struggling with the preview, as when I draw a rect in on_second_paint_event, it's drawn behind the image. Do you know what might cause that?

2022-08-14 09:34 UTC, TobyAsE commented
I took a look at the aspect ratio preserving code, looks good!

I suggest first getting this PR merged in the state that it is in now and not adding more functionality here, the preview can be its own new shiny PR :^)
I'll ping you in discord for you second_paint problem

2022-08-14 09:34 UTC, TobyAsE approved these changes

2022-08-25 18:39 UTC, MacDue commented
(This now has conflicts)

2022-08-29 08:34 UTC, tommasopeduzzi commented
I'm sorry, I made a mess. Is the history okay like this, or should I change something?

2022-09-16 20:53 UTC, merged