Magnifier: Add the option to save captures
SerenityOS/serenity pull request #14975
Opened 2022-08-22 20:43 UTC by gigaroby

2022-08-26 17:20 UTC, vkoskiv reviewed
Added comments. Just some nitpicks, I'm fine with this being merged as-is. 8)

2022-09-17 17:04 UTC, vkoskiv commented
@linusg Can we get this merged? No conflicts and I'm fine with this being merged as-is

2022-09-19 15:55 UTC, gigaroby commented
Sorry, I was on vacation. There's now support for saving in different formats. I don't think the UX for this is great (if users type the wrong extension all they get is a "Unable to save") but we can fix that later.

2022-09-20 11:50 UTC, AtkinsSJ requested changes
I have a couple of nit-picks, otherwise this looks good.

2022-09-20 11:50 UTC, AtkinsSJ commented on Userland/Applications/Magnifier/main.cpp
> +#include "LibGfx/BMPWriter.h"
```suggestion
#include <LibGUI/MessageBox.h>
#include <LibGfx/BMPWriter.h>
```

2022-09-20 11:50 UTC, AtkinsSJ commented on Userland/Applications/Magnifier/main.cpp
> +        // filename is filled-in by save_bitmap_to and used for warnln to give a more descriptive error
This comment refers to `save_bitmap_to` which doesn't exist. Please remove it.

2022-09-26 16:28 UTC, AtkinsSJ approved these changes

2022-09-26 16:28 UTC, merged