Ports/python3: Patches to make pip work
SerenityOS/serenity pull request #15099
Opened 2022-09-01 20:59 UTC by hjalves

Add two patches to allow Python's package manager (pip) to work on
Serenity:

- The first one enables the zlib module which is needed for `ensurepip`
- The second one allows pip to download packages from the repository,
when installed through the "ensurepip" command.

This may fix #13529

2022-09-01 21:19 UTC, hjalves commented
(Changed to draft because the second patch has a bug)

2022-09-02 10:39 UTC, linusg requested changes
https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy
> Write the commit message subject line in the imperative mood

2022-09-02 12:16 UTC, linusg commented on Ports/python3/patches/0005-Tweak-setup.py-sysroot-detection.patch
> ++        var += ' --sysroot=' + os.environ.get('SERENITY_INSTALL_ROOT', '')
```suggestion
+        if serenity_install_root := os.environ.get('SERENITY_INSTALL_ROOT'):
+            var += f' --sysroot={serenity_install_root}'
```

2022-09-02 12:16 UTC, linusg commented on Ports/python3/patches/0005-Tweak-setup.py-sysroot-detection.patch
> ++        var += ' --sysroot=' + os.environ.get('SERENITY_INSTALL_ROOT', '')
(this needs a regen of the patch as line numbers no longer match up)

2022-09-02 13:03 UTC, linusg approved these changes
Thanks, very exciting!

2022-09-02 13:03 UTC, merged