Hexeditor: Implement undo and redo actions
SerenityOS/serenity pull request #15160
Opened 2022-09-07 22:23 UTC by nbvdkamp

This PR adds undo redo functionality to HexEditor and fixes the window being marked dirty even when no bytes are actually modified.

2022-09-08 05:58 UTC, djwisdom commented
About time for HexEditor to get some more ❤️   🎉 🎉 🎉 🎉 🎉

2022-09-08 09:00 UTC, linusg commented
@djwisdom please tone down the excitment-posting on PRs a bit. :^)

2022-10-16 23:23 UTC, linusg requested changes

2022-10-16 23:23 UTC, linusg commented on Userland/Applications/HexEditor/HexEditor.h
> +#include "LibGUI/UndoStack.h"
Please use `<>` includes for libraries

2022-10-17 22:44 UTC, nbvdkamp commented on Userland/Applications/HexEditor/HexEditor.h
> +#include "LibGUI/UndoStack.h"
Oops, fixed

2022-11-01 12:07 UTC, merged