LibWeb: Add CanvasRenderingContext2D spec links
SerenityOS/serenity pull request #15209
Opened 2022-09-12 14:24 UTC by jdahlin

Add spec links and FIXMEs

2022-09-12 14:33 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
> +// 4.12.5.1.10 https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-fillrect
Please omit the section number, which is for https://html.spec.whatwg.org/multipage/canvas.html#drawing-rectangles-to-the-bitmap

2022-09-12 14:33 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
> +// 4.12.5.1.10 https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-clearrect
Likewise

2022-09-13 13:35 UTC, davidot commented on Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
> +// 4https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-fillrect
I think you just missed this `4` in front of the link here

2022-09-13 13:42 UTC, davidot requested changes
Thanks for removing the numbers, just found one last one.
Also the clang-format is complaining about some white space

And also could you squash the commits? No need to make another PR, you can try to follow this video: https://youtu.be/ElRzTuYln0M or ask for help on the discord or here.

2022-09-13 13:42 UTC, davidot commented on Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
> +// 4https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-fillrect
Looks like you missed the `4` just in front of the link here

2022-09-13 13:42 UTC, davidot commented on Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
> +
And here is some more trailing white space

2022-10-12 02:51 UTC, closed without merging