SystemMonitor: Remember column configurations
SerenityOS/serenity pull request #15263
Opened 2022-09-16 17:07 UTC by orellazri

Make SytemMonitor remember the last column configurations by save the state of the columns to the program's config file.

2022-09-16 17:24 UTC, orellazri commented
Having some trouble not having a branch merge commit without opening a new PR.

2022-09-16 18:46 UTC, AtkinsSJ commented
Hi, welcome to Serenity and thanks for working on this!

Git is confusing but it does get easier. :^) What you want to do here is:
- Interactive-rebase your branch onto master
- Modify your first commit to include the missing newline
- Drop the second commit and the merge one

This video is helpful: https://www.youtube.com/watch?v=ElRzTuYln0M I think it covers all of those things. Feel free to ask questions on the Discord server if you get stuck though.

2022-09-16 19:26 UTC, orellazri commented
> Hi, welcome to Serenity and thanks for working on this!
> 
> Git is confusing but it does get easier. :^) What you want to do here is:
> 
> * Interactive-rebase your branch onto master
> * Modify your first commit to include the missing newline
> * Drop the second commit and the merge one
> 
> This video is helpful: https://www.youtube.com/watch?v=ElRzTuYln0M I think it covers all of those things. Feel free to ask questions on the Discord server if you get stuck though.

This was really helpful, thanks! Updated my commit :)

2022-09-20 11:28 UTC, AtkinsSJ requested changes
I have a couple of small comments. Also, please wrap your commit message at 72 characters. Otherwise, looks good.

2022-09-20 11:28 UTC, AtkinsSJ commented on Userland/Applications/SystemMonitor/main.cpp
> +                ProcessModel::the().is_default_column(column)));
We already have the `ProcessModel` in a variable, so we don't need to call `ProcessModel::the()` to get it.

```suggestion
        process_table_view.set_column_visible(column,
            Config::read_bool("SystemMonitor"sv, "ProcessesPreferences"sv, process_model.column_name(column),
                process_model.is_default_column(column)));
```

2022-09-20 11:28 UTC, AtkinsSJ commented on Userland/Applications/SystemMonitor/main.cpp
> +        Config::write_bool("SystemMonitor"sv, "ProcessesPreferences"sv, ProcessModel::the().column_name(column), process_table_header.is_section_visible(column));
"ProcessesPreferences" doesn't make it clear that this is for the table columns. I think "ProcessTableColumns" would be better. (This needs to be changed on line 299 too of course.)

2022-09-21 09:14 UTC, AtkinsSJ approved these changes
Looks good to me!

2022-09-21 09:14 UTC, merged