Kernel: Remove i8042 scan code setting sequence
SerenityOS/serenity pull request #15346
Opened 2022-09-24 15:34 UTC by supercomputer7

cc @linusg

2022-09-25 11:45 UTC, linusg commented
Tested on my machine, works!

2022-09-26 20:54 UTC, 8infy commented on Kernel/Arch/x86/ISABus/I8042Controller.cpp
> +        TRY(drain_output_buffer());
I don't think this is safe if user is mashing keyboard keys/moving the mouse (as people sometimes do at PC startup). Maybe a better approach would be to consume any garbage as part of the expected output? Even if they aren't mashing the keys there's still a race window here.

2022-11-06 05:37 UTC, supercomputer7 commented
What I think is the best to do with the problem of setting scan code 2 is to gate that piece of code with a kernel commandline option. I will look into this today.

2022-12-22 01:54 UTC, supercomputer7 commented
Let's try this again.

2022-12-22 02:38 UTC, supercomputer7 commented
All of these patches work both on QEMU and on my ICH7 test machine, so @linusg please test them and if they are OK, we should merge these :)

2023-01-05 21:29 UTC, supercomputer7 commented
This had conflicts so I rebased it now again.

2023-01-05 23:22 UTC, linusg requested changes

2023-01-06 10:09 UTC, merged