headless-browser: add ca-certs-path options
SerenityOS/serenity pull request #15391
Opened 2022-09-30 13:28 UTC by leeight

FIX #15390

2022-09-30 13:31 UTC, leeight commented
```diff
$ ./headless-browser -r ../../Base/res -c ../../Base/etc/ca_certs.ini https://serenityos.org/
Loaded 0 CA Certificates
+ Loaded 103 CA Certificates
Loading https://serenityos.org/
ResourceLoader: Starting load of: "https://serenityos.org/"
ResourceLoader: Starting load of: "https://serenityos.org/favicon.ico"
ResourceLoader: Finished load of: "https://serenityos.org/", Duration: 1908ms
The encoding sniffing algorithm returned encoding 'UTF-8'
ResourceLoader: Starting load of: "https://serenityos.org/banner2.png"
ResourceLoader: Starting load of: "https://camo.githubusercontent.com/eec2b668c9d82d25aaf61d9afec1af3923f2d9e21bddc83a9ac621254af00ee6/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3837333637323530353330393637393735382e706e67"
ResourceLoader: Starting load of: "https://serenityos.org/screenshot-b36968c.png"
ResourceLoader: Finished load of: "https://camo.githubusercontent.com/eec2b668c9d82d25aaf61d9afec1af3923f2d9e21bddc83a9ac621254af00ee6/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3837333637323530353330393637393735382e706e67", Duration: 2297ms
Taking screenshot after 1 seconds !
ResourceLoader: Finished load of: "https://serenityos.org/favicon.ico", Duration: 5584ms
Saving to output.png
```

2022-10-13 17:43 UTC, alimpfard requested changes

2022-10-13 17:43 UTC, alimpfard commented on Userland/Libraries/LibTLS/Certificate.h
> +    void reload_certificates(NonnullRefPtr<Core::ConfigFile>&);
No point in taking a refptr as a reference, either take a `ConfigFile&` or a `NonnullRefPtr<ConfigFile>` (prefer the first)

2022-10-13 17:43 UTC, alimpfard commented on Userland/Libraries/LibTLS/TLSv12.cpp
> +void DefaultRootCACertificates::reload_certificates(NonnullRefPtr<Core::ConfigFile>& config)
This does not clear the old certs, so it's not much of a "reload". Should probably just clear the existing certs.

2022-10-14 23:14 UTC, merged