AK: Make StringUtils to_int a bit faster
SerenityOS/serenity pull request #15415
Opened 2022-10-01 09:23 UTC by Hendiadyoin1

#### AK: Add a max_digits field to NumericLimits

This field describes the maximum amount of digits a number of that type
can have in the decimal system.
The fromular used is:
```py
len(str(2**n -1))
```

#### LibLine: Use to_int instead of to_uint for time_t's

time_t is technically signed and this will allow us to make to_int and
to_uint more restrictive

#### AK: Make to_int_* and to_uint_* functions more restrictive

#### AK: Do range checks earlier in to_[u]int

This avoids use of __builtins and speeds up the code by up to 10%.
This also adds a more turned down version of the benchmark used to
measure the speedup.

2022-10-01 10:10 UTC, davidot requested changes
These methods are now no longer overflow safe and will give wrong results

2022-10-01 10:10 UTC, davidot commented on AK/StringUtils.cpp
> +        return {};
Just checking this does not mean we avoid overflow.
We can probably use a `max_digits_no_overflow` which is lower than your current `max_digits()`.

For example `9223372036854776808` has 19 digits but is higher than $2^{63}$.

This is a problem for every single integer type as powers of ten don't match the powers of two

2022-10-01 10:10 UTC, davidot commented on AK/StringUtils.cpp
> +        return {};
Here an example would be `19000000000000000000` which is 20 digits but larger than $2^{64}$

2022-10-01 13:30 UTC, Hendiadyoin1 commented
I think I have a solution, although it did cost a surprising amount of runtime....

2022-10-01 13:43 UTC, davidot approved these changes
Looks fine to me now, yeah it seems tricky to do this safely unfortunately.
Maybe we can add tests to ensure this keeps working?

2022-10-01 14:26 UTC, Hendiadyoin1 commented
As far as I could tell all of CI caught it

2022-10-01 14:54 UTC, davidot commented
> As far as I could tell all of CI caught it

Ah sorry I didn't check the CI before, good to know!

2022-10-12 05:30 UTC, ADKaster reviewed
This looks like a reasonable refactor, but i've got a couple questions

2022-10-12 05:30 UTC, ADKaster commented on AK/NumericLimits.h
> +    static constexpr size_t max_digits() { return 3; }
:de:  is showing, should be "formula" in the first commit message.

2022-10-12 05:30 UTC, ADKaster commented on AK/StringUtils.cpp
> +    // If we are at the edge of the representable range, we need to check for overflows
is the 10% claim true across the board? or only for numbers close to NumericLimits::<T>::max() ?

In one of your other comment replies you mentioned that the may_overflow change cost "significant runtime", is it still a net positive of ~10%?

The benchmark looks like it only verifies large numbers, is there any noticable performance difference for small numbers? < 10, 10 - 100, < 1000? I feel like numbers in that range are more common in our codebase and the types of applications/data they commonly interact with.

2022-11-12 06:05 UTC, closed without merging