Ports: Add dtc utility suite
SerenityOS/serenity pull request #15479
Opened 2022-10-05 07:40 UTC by supercomputer7

This includes the known dtc utility as well with other bundled utilities with it.

cc @ADKaster

2022-10-06 17:55 UTC, timschumi requested changes

2022-10-06 17:55 UTC, timschumi commented on Ports/dtc/package.sh
> +workdir="dtc-${version}"
This is the default value, so it should be omitted.

2022-10-06 17:55 UTC, timschumi commented on Ports/dtc/package.sh
> +version=98a07006c48dc0bc3f42b3b3ce75b7f03e87e724
```suggestion
port='dtc'
version='98a07006c48dc0bc3f42b3b3ce75b7f03e87e724'
```

2022-10-06 17:55 UTC, timschumi commented on Ports/dtc/package.sh
> +auth_type=sha256
```suggestion
auth_type='sha256'
```

2022-10-06 17:55 UTC, timschumi commented on Ports/dtc/package.sh
> +files="https://github.com/dgibson/dtc/archive/${version}.zip dtc-${version}.zip 52cffaf31085cb9dce4afb91617a7017065cff7668c9a23291ad04f8c85270c4"
Eh, a ZIP is technically fine, but basically everything else uses `.tar.gz`. As long as there are no files that might require their file modes to be preserved, I'll leave it up to you on whether to change it.

2022-10-06 17:55 UTC, timschumi commented on Ports/dtc/package.sh
> +    run make PREFIX="$DESTDIR" BINDIR="$DESTDIR/usr/bin" install
```suggestion
    run make PREFIX="${DESTDIR}" BINDIR="${DESTDIR}/usr/bin" install
```

2022-10-06 23:59 UTC, timschumi approved these changes
Looks good from a code-review standpoint, I'll assume that you already built and tested it anyways. :^)

2022-10-07 01:54 UTC, supercomputer7 commented
> Looks good from a code-review standpoint, I'll assume that you already built and tested it anyways. :^)

Yes I tried the dtc utility. The `fdtget` utility seems to not work because it says "Could not find required shared library: libfdt.so.1" although that library is present (so it might not be located in the correct place?). The `dtdiff` script requires `bash` so I will add that as a dependency.

2022-10-07 01:55 UTC, supercomputer7 commented
Apparently we don't support the compiled `fdtget` binary. The DynamicLoader spits out many debug messages about this:
```
97.174 fdtget(50:50): DynamicObject: DYNAMIC tag handling not implemented for DT_VERNEEDED (1879048190)
97.178 fdtget(50:50): DynamicObject: DYNAMIC tag handling not implemented for DT_VERNEEDEDNUM (1879048191)
97.182 fdtget(50:50): DynamicObject: DYNAMIC tag handling not implemented for DT_VERSYM (1879048176)
97.182 fdtget(50:50): DynamicObject: DYNAMIC tag handling not implemented for DT_VERNEEDED (1879048190)
97.182 fdtget(50:50): DynamicObject: DYNAMIC tag handling not implemented for DT_VERNEEDEDNUM (1879048191)
97.182 fdtget(50:50): DynamicObject: DYNAMIC tag handling not implemented for DT_VERSYM (1879048176)
```

2022-10-07 01:59 UTC, supercomputer7 commented
> Looks good from a code-review standpoint, I'll assume that you already built and tested it anyways. :^)

Done, the `dtdiff` script should work too now. Once CI passes this should be ready for merging :)

2022-10-09 15:51 UTC, merged