Utilities: Add jq-like json query functionality to `jp`
SerenityOS/serenity pull request #15557
Opened 2022-10-12 19:51 UTC by maxtrussell

The syntax/feature set is much simpler than `jq` though. It just takes a dotted set of keys (e.g. "foo.bar.baz") to index with. If one of the given keys is `*` then it will match all elements of the `JsonValue`.

See attached screenshot for more info:
![jp](https://user-images.githubusercontent.com/27985762/195433870-5cd8bc04-3a68-4bae-b28a-2fec494067dc.png)

2022-10-12 23:47 UTC, drunderscore reviewed
Just these two code smell issues... although I really don't believe a program named `jp` for "JSON Pretty" should have `jq`-like abilities.

2022-10-12 23:47 UTC, drunderscore commented on Userland/Utilities/jp.cpp
> +    }
Single-statement `if`s shouldn't have curly braces

2022-10-12 23:47 UTC, drunderscore commented on Userland/Utilities/jp.cpp
> +        }
Ditto.

2022-10-12 23:58 UTC, maxtrussell commented on Userland/Utilities/jp.cpp
> +    }
Fixed

2022-10-12 23:58 UTC, maxtrussell commented on Userland/Utilities/jp.cpp
> +        }
Also fixed

2022-10-13 00:05 UTC, maxtrussell commented
> Just these two code smell issues... although I really don't believe a program named `jp` for "JSON Pretty" should have `jq`-like abilities.

@drunderscore That's a fair complaint. I thought of it more as "JSON Print" and printing a subset of the JSON didn't see too off-base to me.

If people feel strongly I could either create a new utility or just close the PR.

If I had to create a new utility, I'd need to:
a. pull out the JSON pretty printing logic to some shared library
b. duplicate it
c. ugly print the json

Given those choices I thought placing it in `jp` was reasonable. And of course, I'm open to alternate ideas if I'm not thinking of something.

2022-10-21 18:12 UTC, linusg requested changes
Second commit needs a little explanation, something along the lines "it no longer just prints JSON"

2022-10-21 18:12 UTC, linusg commented on Userland/Utilities/jp.cpp
> +    StringView key = key_parts[key_index++];
`auto`

2022-10-21 18:12 UTC, linusg commented on Userland/Utilities/jp.cpp
> +    if (key == "*") {
`== "*"sv`

2022-10-21 18:36 UTC, maxtrussell commented on Userland/Utilities/jp.cpp
> +    StringView key = key_parts[key_index++];
Fixed

2022-10-21 18:36 UTC, maxtrussell commented on Userland/Utilities/jp.cpp
> +    if (key == "*") {
Fixed

2022-10-21 21:53 UTC, linusg requested changes
You added the changes to the second commit by accident :)

2022-10-21 22:11 UTC, maxtrussell commented
> You added the changes to the second commit by accident :)

@linusg Ah dang good catch, just rebased the logic changes into the first commit, so the second is just the rename now.

2022-10-21 22:23 UTC, linusg approved these changes

2022-10-21 22:47 UTC, merged