Lagom: Remove GLOB patterns for most libraries, and build using their CMakeLists in Userland
SerenityOS/serenity pull request #15580
Opened 2022-10-14 02:46 UTC by ADKaster

Bunch of cleanup here:

- Create an AK_SOURCES variable for use n places that want to include AK in their library (LibC, DynamicLodaer, Lagom LibCore)
- Convert lagom_lib rules to use add_serenity_subdirectory helper, which will defer to the CMakeLists.txt in each library or application or service's individual subdirectory.
- Remove logic for Lagom vs Serenity build directory in code generator helpers
- Leave some low hanging fruit FIXMEs for a crafty CMake apprentice to pick up if they want.

2022-10-14 09:15 UTC, linusg requested changes

2022-10-14 09:15 UTC, linusg commented on Meta/Lagom/CMakeLists.txt
> +        GL
`swap()`

2022-10-14 09:15 UTC, linusg commented on Meta/Lagom/CMakeLists.txt
> +        SQL
`swap()`

2022-10-14 09:15 UTC, linusg commented on Meta/Lagom/CMakeLists.txt
> +        GML/SyntaxHighlighter.cpp
Um

2022-10-14 09:15 UTC, linusg commented on Userland/Libraries/LibCore/CMakeLists.txt
> +        GetPassword.cpp
`swap()`

2022-10-14 17:48 UTC, ADKaster commented on AK/CMakeLists.txt
> +    StringUtils.cpp
That's the order of inodes on my machine, I copy pasted from `find` :)

2022-10-15 01:11 UTC, nico commented
Typo "varaible" in commit message

2022-10-16 10:34 UTC, ADKaster commented
Re-ordered lists and fixed typos, thanks for the reviews!

2022-10-16 14:36 UTC, linusg approved these changes

2022-10-16 14:36 UTC, merged