SystemServer: Make system-mode=text the default in case of failure
SerenityOS/serenity pull request #15594
Opened 2022-10-14 18:34 UTC by supercomputer7

I know we should not encounter such case, but when I worked on #15593, I managed to remove the `/proc/system_mode` but replaced it with nothing so `SystemServer` launched `WindowServer` which crashed because it didn't know what to do without reading `system_mode`.

2022-10-15 06:58 UTC, bgianfo requested changes
Small nits

2022-10-15 06:58 UTC, bgianfo commented on Userland/Services/SystemServer/main.cpp
> +    dbgln("{}", g_system_mode);
Isn't the double logging unnecessary, especially this line where we log no other context?

2022-10-15 06:58 UTC, bgianfo commented on Userland/Services/SystemServer/main.cpp
> +        g_system_mode = "text";
The comments on line 74 and 79 are now wrong.

2022-10-15 08:43 UTC, bgianfo approved these changes

2022-10-15 16:05 UTC, linusg requested changes
This is consistently failing CI even after a restart, seems suspicious.

2022-10-16 03:19 UTC, supercomputer7 commented
I had a small mistake in the code (I removed the line where it was setting the system mode based on what we read from `/proc/system_mode`). Should be good to go now.

2022-10-16 15:43 UTC, merged