Ports: Add a ClassiCube port
SerenityOS/serenity pull request #15622
Opened 2022-10-15 17:18 UTC by cflip

This works fairly well out of the box, but there are still a few issues:
- The world is completely invisible, however occasionally you can see some block faces or black triangles extending into the distance.
- The mouse doesn't lock into the window
- I haven't implemented backtraces into the game's error logger. I could either port libexecinfo which is what ClassiCube uses on other platforms such as Haiku, or implement the function using Serenity's API. (Intentionally crashing the game so we can view the backtrace in CrashReporter is a hacky third option.)

2022-10-15 19:56 UTC, GMTA commented on Ports/ClassiCube/package.sh
> +	run cp ClassiCube ${SERENITY_INSTALL_ROOT}/home/anon/Games/ClassiCube
Port binaries go into `/usr/local/bin` so the executable is on `$PATH`

2022-10-15 19:57 UTC, GMTA commented on Ports/ClassiCube/package.sh
> +depends=("SDL2" "curl")
For all the strings above, please apply the following:
* Single-quoted strings for non-interpolated values (i.e. `auth_type='sha256'`)
* Double-quoted strings for interpolated values (i.e. `workdir="${port}-${version}/src/"`)

2022-10-15 19:59 UTC, GMTA commented on Ports/ClassiCube/package.sh
> +makeopts=serenity
You are overwriting `makeopts` here, losing the parallel processing default option. Could be `makeopts+=('serenity')` perhaps?

2022-10-15 19:59 UTC, GMTA commented on Userland/Libraries/LibGL/Tex/Texture2D.h
> +    static constexpr u16 MAX_TEXTURE_SIZE = 4096;
Can you add the reasoning for this change to the commit message?

2022-10-15 20:02 UTC, GMTA commented
@cflip 

As stated in #ports on Discord, I don't think mouse grabbing/capturing is possible without some additional kernel level features to toggle the virtualized mouse's behavior.

Maybe you can add a launcher for ClassiCube as well? Look at some other ports that have launchers for an example of how to do this in `package.sh`.

2022-10-15 21:58 UTC, cflip commented
I tried adding a script to launch ClassiCube with in the correct working directory, but it looks like it can't initialize the GUI when run through the launcher this way. `package.sh` is a bit messy at the moment, but I'll look into adding support to `LibDesktop::AppFile` to launch a program with a specific working directory.

2022-10-16 21:49 UTC, UnknownShadow200 commented
glGetInteger(GL_MAX_TEXTURE_SIZE) always returns 4096 <https://github.com/SerenityOS/serenity/blob/6dcc808994d14de3134a6fa406a118f0100a7980/Userland/Libraries/LibGL/ContextParameter.cpp#L82>, which is why it tries to make a texture atlas that tall

2022-10-17 10:11 UTC, GMTA commented on Ports/ClassiCube/package.sh
> +depends=("SDL2" "curl")
These constant strings can be single-quoted (same for `port` and `version` above)

2022-10-17 10:12 UTC, GMTA commented on Ports/ClassiCube/patches/0003-HACK-Disable-interrupt-hooks-on-Serenity.patch
> ++#endif
Instead of `#ifndef`ing it out, you can just patch it to remove the `Logger_Hook();` line. The patches are only applied for SerenityOS anyway.

2022-10-17 10:14 UTC, GMTA requested changes
LibGL / LibGPU / LibSoftGPU changes look good. Left some additional remarks on ClassiCube.

2022-10-18 17:03 UTC, cflip commented
Now that sound is working, I think this is ready to go.

2022-10-18 17:17 UTC, linusg requested changes

2022-10-18 17:17 UTC, linusg commented on Ports/libopenal/patches/0001-Disable-example-programs-and-force-SDL2-backend-to-b.patch
> ++option(ALSOFT_EXAMPLES  "Build example programs"  OFF)
There's no reason whatsoever to patch out CMake options we can simply pass to the `run cmake` invocation :thinking:

2022-10-18 17:17 UTC, linusg commented on Ports/ClassiCube/package.sh
> +depends=('SDL2' 'curl' 'libopenal')
One per line

2022-10-19 19:52 UTC, GMTA approved these changes

2022-10-19 20:06 UTC, linusg approved these changes

2022-10-19 20:07 UTC, merged