WebDriver: Eat (delete) all the cookies!
SerenityOS/serenity pull request #15649
Opened 2022-10-16 17:58 UTC by TobyAsE

Two more for @AtkinsSJ list in #15551 
This needed some plumbing into the Browser to allow for the changing of Cookies.
What good does it bring if we can only see Cookies, now we can eat them too!

2022-10-16 19:01 UTC, linusg requested changes

2022-10-16 19:01 UTC, linusg commented on Userland/Services/WebDriver/Client.cpp
> +    { HTTP::HttpRequest::Method::DELETE, { "session", ":session_id", "cookie", ":name" }, &Client::handle_delete_cookie },
This comes before `handle_delete_cookie` below, let's do the same here

2022-10-16 19:01 UTC, linusg commented on Userland/Services/WebDriver/Session.cpp
> +ErrorOr<JsonValue, HttpError> Session::delete_cookie(String const& name)
StringView

2022-10-16 19:06 UTC, davidot reviewed
Don't have much to add beyond linus' comments. 
Just one spot where some spec links/comments would help

2022-10-16 19:06 UTC, davidot commented on Userland/Applications/Browser/CookieJar.cpp
> +        cookie.creation_time = old_cookie->value.creation_time;
That the creation time has to stay the same is non-obvious, perhaps a link/spec text from 
https://www.rfc-editor.org/rfc/rfc6265#section-5.3 step 11.3 is nice?

Also that says that something about HttpOnly which I don't know if this follows

2022-10-17 08:11 UTC, TobyAsE commented on Userland/Applications/Browser/WebDriverConnection.h
> +    virtual void update_cookie(Web::Cookie::Cookie const&) override;
This is not possible since the IPC function that this overrides gets a const&. Any ideas on what to do instead?

2022-10-17 08:22 UTC, TobyAsE commented on Userland/Applications/Browser/WebDriverConnection.h
> +    virtual void update_cookie(Web::Cookie::Cookie const&) override;
Apparently it works by keeping the signature `const&` and then `move()`ing it to the `on_update_cookie()`
Is this a sensible approach?

constness and references, my eternal nemesis...

2022-10-17 08:31 UTC, linusg commented on Userland/Applications/Browser/WebDriverConnection.h
> +    virtual void update_cookie(Web::Cookie::Cookie const&) override;
sad, but you can't `move()` a reference, at least it won't do anything.

2022-10-17 08:44 UTC, TobyAsE commented on Userland/Applications/Browser/WebDriverConnection.h
> +    virtual void update_cookie(Web::Cookie::Cookie const&) override;
I'll just keep it as it is now, right?
So the reference becomes a value once it gets passed in `WebDriverConnection.cpp:103` to the `on_update_cookie`, which takes a `Cookie` as value as an argument.

2022-10-17 09:15 UTC, linusg requested changes

2022-10-17 09:29 UTC, TobyAsE commented on Userland/Applications/Browser/WebDriverConnection.cpp
> +            tab.on_update_cookie(tab.url(), cookie);
Advanced git-fu sometimes goes wrong... fixed.

2022-10-17 09:31 UTC, merged