LibGUI: Fixed EditingEngine Shift + Up/Down highlight behavior
SerenityOS/serenity pull request #15691
Opened 2022-10-19 04:16 UTC by skelegorg

This commit fixes the highlight behavior of pressing Shift + Up Arrow and Shift + Down Arrow in the EditingEngine. Previously, pressing Shift + Up with your cursor in the middle of the top line would not respond, likewise with pressing Shift + Down with your cursor in the middle of the bottom row. This behavior is inconsistent with the normal, unselected cursor movement when pressing just the Up Arrow or Down Arrow in the same parts of the same lines, where it would send the cursor to the start or end of the line respectively. This commit carries that behavior over to highlighting, so pressing Shift + Up on the middle of the top line will select (or append to an existing selection) the text between the start of the line and the cursor, while pressing Shift + Down on the bottom line will select text between the cursor and the end of the line. 

This is my first commit - feedback very welcome!

2022-10-19 04:32 UTC, skelegorg commented
Sorry for the spam of fixing commits.

2022-10-19 08:27 UTC, TobyAsE commented
Welcome to serenity, I hope you'll enjoy working our little project :^)

The code lgtm

Some comments to your commit message though: please use the imperative (Fixed->Fix), Remove the LibGUI: from the message body, move the related issue to the end "This fixes #xxxx"

2022-10-19 12:25 UTC, skelegorg commented
Thanks TobyAsE, Fixed those commit format issues.

2022-10-24 22:57 UTC, linusg requested changes
Please remove the PR reference from the commit and wrap the description at 72 characters - not less.

2022-10-25 00:06 UTC, skelegorg commented
@linusg  Sorry about that - I have fixed the wrapping but I am not sure what you mean by removing the PR reference from the commit.

2022-10-25 03:57 UTC, skelegorg commented
all commit issues dealt with

2022-10-25 09:17 UTC, linusg commented
Apologies, I worded that badly - by "wrapping at X chars" we don't mean that literally, but "fitting as many words onto the line as possible, up to 72 characters". Many IDEs and git clients can do this for you :)

i.e.:

```
Fix unwanted behavior in the EditingEngine where using Shift + Up or
Down keys will not highlight to the beginning or end of the first or
last lines of the file. Fixes #15695.
```

2022-10-25 13:42 UTC, skelegorg commented
ohh ok, fixed!

2022-10-25 13:46 UTC, skelegorg commented
that makes 7 commits to fix my commit style

2022-10-25 17:35 UTC, merged