WebDriver: Some code niceties
SerenityOS/serenity pull request #15719
Opened 2022-10-20 13:22 UTC by AtkinsSJ

The main change here is to create errors with an `ErrorCode` enum rather than having to specify the HTTP status and error name every time. `WebDriverError::from_code(ErrorCode::Foo, "Extra info here")` is more verbose than I'd like though.

Also added a helper for the "If the current top-level browsing context is no longer open, return error with error code no such window." spec step which occurs in basically every Session function.

2022-10-20 13:23 UTC, AtkinsSJ commented
@TobyAsE Apologies in advance as this is going to conflict with your work unless yours is merged first. :sweat_smile:

2022-10-20 14:32 UTC, AtkinsSJ commented
Forget that, I'll rebase on #15713 once that's merged and then try and get this merged quick. :^)

2022-10-20 20:15 UTC, AtkinsSJ commented
Since last time:
Moved `current_window_or_error()` and `check_for_open_top_level_browsing_context_or_return_error()` out of line.

2022-10-20 20:19 UTC, TobyAsE commented
:marge:

2022-10-20 20:26 UTC, linusg requested changes
Very nice, just some naming and style concerns. Last commit is especially :yakkiss:

2022-10-20 20:26 UTC, linusg commented on Userland/Services/WebDriver/WebDriverError.cpp
> +Vector<ErrorCodeData> s_error_code_data = {
`s_` but not actually `static`

2022-10-20 20:37 UTC, AtkinsSJ commented on Userland/Services/WebDriver/WebDriverError.cpp
> +Vector<ErrorCodeData> s_error_code_data = {
:man_facepalming:

2022-10-20 20:41 UTC, linusg commented on Userland/Services/WebDriver/Client.cpp
> -#include <WebDriver/TimeoutsConfiguration.h>
(To be clear, that I changed it doesn't mean it's right - just very unclear which style to use when atm)

2022-10-21 11:02 UTC, AtkinsSJ commented on Userland/Services/WebDriver/WebDriverError.h
> +struct WebDriverError {
Yeah I wasn't super happy with it, but regular `AK::Error` does get used in a few places in Variants with WebDriverError:

```c++
class Session {
// ...
    ErrorOr<void, Variant<WebDriverError, Error>> close_window();
```

So I'm a little dubious about naming it that. I'll give it a shot.

2022-10-21 11:05 UTC, AtkinsSJ commented on Userland/Services/WebDriver/WebDriverError.h
> +struct WebDriverError {
It's not my favourite. :thonk: But it should work. What do you think?
```c++
    static ErrorOr<void, Error> unwrap_result(ErrorOr<void, Variant<Error, AK::Error>> result)
    {
        if (result.is_error()) {
            Variant<Error, AK::Error> error = result.release_error();
            if (error.has<Error>())
                return error.get<Error>();
            return Error { 500, "unsupported operation", error.get<AK::Error>().string_literal() };
        }
        return {};
    }
```

2022-10-21 11:10 UTC, AtkinsSJ commented on Userland/Services/WebDriver/Client.cpp
> -#include <WebDriver/TimeoutsConfiguration.h>
Sure, but for now there's no sense flipping it back and forth. I'll drop the commit.

2022-10-21 11:54 UTC, AtkinsSJ commented
Made all requested changes except for the `WebDriverError` -> `Error` one, for now.

2022-10-21 17:57 UTC, linusg commented on Userland/Services/WebDriver/WebDriverError.h
> +struct WebDriverError {
that _is_ a bit weird, let's skip it for now.

2022-10-21 17:59 UTC, merged