WebDriver+Browser: Implement `GET /session/{id}/element/{id}/screenshot`
SerenityOS/serenity pull request #15927
Opened 2022-11-04 21:22 UTC by trflynn89

[Screencast from 2022-11-04 17-17-52.webm](https://user-images.githubusercontent.com/5600524/200076421-ddc8b727-a85a-4ece-bd70-dc9c04001628.webm)

Ref #15551

2022-11-04 21:34 UTC, trflynn89 commented
Hmm might not be totally right - we might be responsible for only saving a screenshot of the part of the element in the viewport? Not sure. Firefox and Chrome behave differently:

Firefox:
1. Window screenshot saves just the visible portion (like us).
2. Element screenshot saves the entire element (like us).

Chrome:
1. Window screenshot saves just the visible portion (like us).
2. Element screenshot saves just the visible portion (*not* like us).

2022-11-04 21:42 UTC, linusg requested changes

2022-11-04 21:42 UTC, linusg commented on Userland/Services/WebDriver/Session.cpp
> +// 17.1 Take Screenshot, https://w3c.github.io/webdriver/#take-screenshot
```suggestion
// 17.2 Take Element Screenshot, https://w3c.github.io/webdriver/#take-element-screenshot
```

2022-11-04 22:35 UTC, linusg commented
It looks like Chrome is right, yeah:

> ...and a [command](https://w3c.github.io/webdriver/#dfn-commands) [Take Element Screenshot](https://w3c.github.io/webdriver/#dfn-take-element-screenshot) for doing the same with the **visible region** of an [element](https://dom.spec.whatwg.org/#concept-element)’s [bounding rectangle](https://w3c.github.io/webdriver/#dfn-bounding-rectangle) after it has been [scrolled into view](https://w3c.github.io/webdriver/#dfn-scrolls-into-view).

Shouldn't this be as simple as intersecting the element rect with the viewport rect?

2022-11-05 00:01 UTC, trflynn89 commented
> Shouldn't this be as simple as intersecting the element rect with the viewport rect?

It *should* have been except took too long to figure out why that wasn't working. Turns out after scrolling the element into view, there's a series of events that need to happen before the viewport rect is actually updated. That scroll API was async, so it was happening *after* the screenshot was taken.

So I made it sync, and now it works:
[Screencast from 2022-11-04 19-58-53.webm](https://user-images.githubusercontent.com/5600524/200091050-81bb754a-68fc-4a3d-93a4-d1c7c16a7b99.webm)

2022-11-05 01:09 UTC, linusg approved these changes
rad!

2022-11-05 01:10 UTC, merged