LibJS: Add explicit assertion for days in Temporal > round_duration
SerenityOS/serenity pull request #15942
Opened 2022-11-05 18:53 UTC by Smrtnyk

This is an editorial change in Temporal spec.

See: https://github.com/tc39/proposal-temporal/commit/15b7293b38956a99805a48ab042a780a343cb5e2

This ticks off one checkbox in #15525

2022-11-06 01:41 UTC, linusg requested changes
Please also add the assertion.

Also, this looks strange: `Temporal > round_duration`

2022-11-11 11:58 UTC, Smrtnyk commented
> Please also add the assertion.
> 
> Also, this looks strange: `Temporal > round_duration`

I wanted it to standout that it is about temporal, still learning about rules of serenity :D
I have changed the title and commit message

2022-11-11 12:08 UTC, linusg commented
just regular C++ `trunc()`: https://github.com/SerenityOS/serenity/blob/57162ad510b7e03137f9c6bf00b49252604c01d5/Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.cpp#L266-L267

2022-11-11 12:14 UTC, linusg approved these changes
Thanks!

2022-11-11 12:14 UTC, merged

2022-11-11 14:12 UTC, linusg commented
@Smrtnyk I had to revert this, it made test-js crash. Please always run that to ensure nothing is broken :)
(my bad for not letting CI run to completion, it looked simple enough)

2022-11-11 14:14 UTC, Smrtnyk commented
> @Smrtnyk I had to revert this, it made test-js crash. Please always run that to ensure nothing is broken :) (my bad for not letting CI run to completion, it looked simple enough)

oh, I am very sorry for that
will make sure to run that
is it the test262, or some other kind of tests?

2022-11-11 14:17 UTC, linusg commented
`./Meta/serenity.sh run lagom test-js` should do the trick :)

2022-11-11 14:20 UTC, Smrtnyk commented
thank you, will make sure to always run that first before commiting anything
also do you think it makes sense to open the PR again, but with FIXME for actual assertion?
so at least spec comments are in sync
I will try to figure out why assertions are failing

2022-11-11 14:25 UTC, linusg commented
No, I think we should find the underlying issue first. There is a possibility that this would be fixed by implementing a preceding spec change first, but that's really just a guess.