PixelPaint: Enable color picking for paint tools on Alt key
SerenityOS/serenity pull request #15955
Opened 2022-11-06 11:10 UTC by kdaker

Adds color picker ability similar to the `PickerTool`.

 Feature is available to any `Tool` that inherits from `BrushTool` but can be turned off for tools that don't require it. It is off for `EraseTool` as it doesn't make sense and also for `CloneTool` to not interfere with it's current functionality.

There is some duplication between `BrushTool` and `SprayTool` however it felt cleaner as is than to re-use the code by adding more abstraction. Let me know your thoughts!

 Resolves #11860

2022-12-04 01:38 UTC, kdaker commented
@AtkinsSJ Rebased and tested on latest master.

2022-12-12 16:57 UTC, AtkinsSJ requested changes
Code looks fine, but it's querying the wrong position for the color. Seems like it's not taking the zoom and position of the current layer into account, though I'm not sure.

2022-12-17 21:23 UTC, kdaker commented
@AtkinsSJ thanks for testing! Do you mind giving me steps to reproduce what you're seeing?

I'm testing again with zooming and it seems to still respect the colors at the cursors position regardless of the zoom level. I tried testing with layers and it only picks from what is in the layer but this is how the color picker tool itself works currently.

Screenshots of picked color at the zoom level. The cursor shows the brush tool cursor since I couldn't have alt held while taking a screenshot but the cursor was left at the same position and you can see the picked color below.
![Screenshot from 2022-12-17 13-12-42](https://user-images.githubusercontent.com/905997/208266429-1d4fc257-8a0f-4288-bd6f-563420d8806c.png)
![Screenshot from 2022-12-17 13-12-23](https://user-images.githubusercontent.com/905997/208266430-e83c5b95-df8f-4576-93b3-37b39dfb3d0f.png)
![Screenshot from 2022-12-17 13-11-52](https://user-images.githubusercontent.com/905997/208266431-d32c985b-bfdf-4896-819d-9f918b25a616.png)

2022-12-18 03:33 UTC, kdaker commented
I updated the code to use "sample all layers" when color picking from the brush, pencil and spray tools.

2023-01-17 18:44 UTC, closed without merging