Base: Add red cursor theme
SerenityOS/serenity pull request #15966
Opened 2022-11-07 02:30 UTC by electrikmilk

This adds a red cursor theme.

![Screenshot 2022-11-06 at 21 29 31](https://user-images.githubusercontent.com/4368524/200214247-01a4c242-b46c-40f3-9d80-b2d59b4139af.png)

![Screenshot 2022-11-06 at 21 29 36](https://user-images.githubusercontent.com/4368524/200214253-86b86647-91fe-4e6e-b019-fb1b9b75fdf0.png)

![Screenshot 2022-11-06 at 21 29 41](https://user-images.githubusercontent.com/4368524/200214258-6d2e3652-f53b-413f-a004-8d52952d229f.png)

![Screenshot 2022-11-06 at 21 30 02](https://user-images.githubusercontent.com/4368524/200214263-e30bce58-3975-4a24-b9f2-9adbd93e7698.png)

2022-11-07 08:39 UTC, timschumi requested changes
Those files look awfully large, please run them through `optipng` if you haven't done so already (if I recall correctly we usually use `optipng -strip all`). Alternatively, if you want to be adventurous, `zopflipng` has been in discussion lately for achieving better results than `optipng` (but please make sure that it strips all metadata and that the result is still loadable by our PNG parser).

2022-11-07 08:39 UTC, timschumi commented on Base/res/cursor-themes/Red/Config.ini
> +Zoom=zoom.x0y0.png
This looks like it's missing a newline at the end.

2022-11-11 13:56 UTC, timschumi reviewed
I likely wouldn't use it personally, but at least there doesn't seem to be anything objectively wrong with it.

2022-11-14 00:30 UTC, ADKaster commented
I do wonder, would these cursors be better suited for the serenity-theming repository? @Xexxa  what do you think?

2022-11-14 05:19 UTC, Xexxa commented
> I do wonder, would these cursors be better suited for the serenity-theming repository? @Xexxa  what do you think?

I can't be objective on this one. What's suited for the main repo seems to be a matter of taste and I'm happy I don't have to make that decision...

2022-11-14 10:04 UTC, closed without merging