LibJS: Some work on exception handling and finally
SerenityOS/serenity pull request #16055
Opened 2022-11-13 20:18 UTC by Hendiadyoin1

At some point of this we did not crash in `test-js -b` 🚀

The main issue now is further control-flow support through finally, like `break`s and `continue`s, which currently cause crashes (`try-finally-break`)

2022-11-14 00:21 UTC, linusg requested changes
All commits need to make it clear that they only concern the BC interpreter via the commit message, `LibJS: Try to handle returns to finally statements` isn't clear enough

2022-11-25 22:27 UTC, alimpfard reviewed
Just a couple nitpicks.

2022-11-25 22:27 UTC, alimpfard commented on Userland/Libraries/LibJS/Bytecode/Generator.cpp
> +                // FIXME: We need to enter the `finally`, while still scheduling and the break to happen
s/and //

2022-11-25 22:27 UTC, alimpfard commented on Userland/Libraries/LibJS/Bytecode/Generator.cpp
> +                // FIXME: We need to enter the `finally`, while still scheduling and the continue to happen
s/and //

2022-11-25 22:27 UTC, alimpfard commented on Userland/Libraries/LibJS/Bytecode/Generator.h
> +            case BlockBoundaryType::Unwind:
Pick one pls.

2022-12-06 12:39 UTC, merged