LibCore: fix build with musl libc
SerenityOS/serenity pull request #16323
Opened 2022-12-05 13:04 UTC by aidgamesa

2022-12-05 14:44 UTC, ADKaster commented on Userland/Libraries/LibCore/Group.cpp
> +#if !defined(AK_OS_MACOS) && defined(__GLIBC__)
This isn't quite sufficient. The check for !AK_OS_MACOS implicitly means (AK_OS_LINUX || AK_OS_SERENITY || AK_OS_OPENBSD || AK_OS_FREEBSD || .... etc ). Any checks for glibc should be asking AK_OS_LINUX && glibc.

2022-12-05 16:18 UTC, aidgamesa commented
superbuild passed...
now i build serenityos image...

2022-12-05 16:20 UTC, aidgamesa commented
superbuild passed successful
verdict: "sys/cdefs.h is deprecated" warning crash build if I comment its build!
now i'm build serenityos image...

2022-12-05 17:40 UTC, aidgamesa commented
![screenshot](https://user-images.githubusercontent.com/113248631/205705095-2d6f1558-4922-4363-adbc-5dd0581d4234.png)
its booted successful!

2022-12-07 12:16 UTC, aidgamesa commented
fix sys/cdefs.h build error

2022-12-07 14:42 UTC, linusg reviewed
Listing that many categories is a bit silly, just use `Everywhere:` please :)

2022-12-15 07:09 UTC, ADKaster requested changes
Some other PRs have come along to try to address the same problem as part of https://github.com/SerenityOS/serenity/issues/16463

The only 3 left are 
- remove sys/cdefs.h entirely
- zero init msghdr and then set the fields we want in ntpquery.cpp
- unfortunate overriding of `__assert_fail` in test262 runner.

The last one is the only reason we would want AK_MUSL or a similar define. It might be that we want to use a SIGABRT handler instead to do this error reporting. that would likely be less undefined-behavior/less annoying for C library authors if we did that.

2022-12-31 10:19 UTC, ADKaster commented
All of the mentioned changes have made it into master, feel free to open another PR if we break musl builds again!

2022-12-31 10:19 UTC, closed without merging