Implement remaining value sanitation algorithms
SerenityOS/serenity pull request #16320
Opened 2022-12-05 05:08 UTC by lanmonster

left a couple FIXMEs. it looks like the `multiple` attribute is not implemented yet, so I did not handle that case for the email type, and also sometimes there are 53 weeks in a year.

2022-12-05 13:54 UTC, linusg requested changes

2022-12-05 13:54 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
> +        // Strip newlines from the value, then strip leading and trailing ASCII whitespace from the value.
`// https://html.spec.whatwg.org/multipage/input.html#url-state-(type=url):value-sanitization-algorithm`

2022-12-05 13:54 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
> +
Don't fix whitespace across commits

2022-12-05 13:54 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
> +static u32 number_of_days_in_month_year(u32 month, u64 year)
Let's use the existing `AK::days_in_month()` for this

2022-12-05 13:54 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
> +
Don't fix whitespace across commits

2022-12-05 13:54 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
> +        // https://html.spec.whatwg.org/multipage/input.html#date-state-(type=date):value-sanitation-algorithm
```suggestion
        // https://html.spec.whatwg.org/multipage/input.html#date-state-(type=date):value-sanitization-algorithm
```

2022-12-05 13:54 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
> +        // https://html.spec.whatwg.org/multipage/input.html#month-state-(type=month):value-sanitation-algorithm
```suggestion
        // https://html.spec.whatwg.org/multipage/input.html#month-state-(type=month):value-sanitization-algorithm
```

2022-12-05 13:54 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
> +        // https://html.spec.whatwg.org/multipage/input.html#week-state-(type=week)
```suggestion
        // https://html.spec.whatwg.org/multipage/input.html#week-state-(type=week):value-sanitization-algorithm
```

2022-12-05 13:54 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
> +        // https://html.spec.whatwg.org/multipage/input.html#time-state-(type=time)
```suggestion
        // https://html.spec.whatwg.org/multipage/input.html#time-state-(type=time):value-sanitization-algorithm
```

2022-12-05 13:54 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
> +        // https://html.spec.whatwg.org/multipage/input.html#local-date-and-time-state-(type=datetime-local)
```suggestion
        // https://html.spec.whatwg.org/multipage/input.html#local-date-and-time-state-(type=datetime-local):value-sanitization-algorithm
```

2022-12-05 13:54 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
> +        // https://html.spec.whatwg.org/multipage/input.html#range-state-(type=range)
```suggestion
        // https://html.spec.whatwg.org/multipage/input.html#range-state-(type=range):value-sanitization-algorithm
```

2022-12-14 16:04 UTC, linusg approved these changes
One missing link, rest looks great :)

2022-12-14 16:04 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
> +        // Strip newlines from the value, then strip leading and trailing ASCII whitespace from the value.
```suggestion
        // https://html.spec.whatwg.org/multipage/input.html#email-state-(type=email):value-sanitization-algorithm
        // Strip newlines from the value, then strip leading and trailing ASCII whitespace from the value.
```

2022-12-14 16:47 UTC, linusg approved these changes

2022-12-14 17:19 UTC, AtkinsSJ commented
CI is failing to build.

2022-12-15 09:43 UTC, merged