Kernel: Ignore an invalid QEMU multiboot entry
SerenityOS/serenity pull request #16345
Opened 2022-12-06 22:08 UTC by implicitfield

This makes the kernel ignore a seemingly invalid QEMU multiboot entry and allows Serenity to boot once again on the q35 machine on x86-based platforms.

For reference, a similar fix was put in place by [this](https://gitlab.com/weinholt/loko/-/commit/1e88ef9067a3d53f1148e87962335a6a1bb12bc8) project.

Fixes #14952.

2022-12-06 22:24 UTC, ADKaster commented
I haven't convinced myself that the conditional is correct there yet, but a fix for 14952 should remove the workaround in run.sh that we added for it. 

https://github.com/SerenityOS/serenity/blob/master/Meta/run.sh#L124

2022-12-14 16:07 UTC, linusg requested changes

2022-12-14 16:07 UTC, linusg commented on Kernel/Memory/MemoryManager.cpp
> +                // Workaround for QEMU commit 8504f12.
Please:
- Add a link to said commit
- Go into slightly more detail so others can understand what this is doing

Comments are free :)

2022-12-14 17:04 UTC, linusg commented on Kernel/Memory/MemoryManager.cpp
> +                // 1T boundary on VFs with big bars."
:100:

2022-12-14 17:04 UTC, linusg commented on Kernel/Memory/MemoryManager.cpp
> +                // Workaround for QEMU commit 8504f12.
:100:

2022-12-14 17:05 UTC, merged