Meta: seperate ccache setup and detect ccache being passed as a compiler
SerenityOS/serenity pull request #16346
Opened 2022-12-06 22:08 UTC by Jan200101

This PR seperates the ccache setup found in the root CMakeLists and the Lagom CMakeLists into its own cmake component and expands thats cmake component to detect if the compiler used is already pointing towards ccache.

Some distros set up symlinks for common compilers to call ccache, simplifying the process of using it.
For example on Fedora:
`gcc` invokes `/usr/lib64/ccache/gcc` which is a symlink to `/usr/bin/ccache`

While ccache invoking itself is harmless, other compiler wrappers that may be used with ccache, like icecc, become unhappy when they invoke themselves and terminate compilation.

2022-12-06 22:21 UTC, ADKaster commented
This seems pretty reasonable. I'm wondering if there's similar changes that should be made to Meta/serenity.sh (I forget if we do any ccache magic there) or Ports/.port_include.sh (we definitely mess with ccache there).

2022-12-06 22:32 UTC, Jan200101 commented
> This seems pretty reasonable. I'm wondering if there's similar changes that should be made to Meta/serenity.sh (I forget if we do any ccache magic there) or Ports/.port_include.sh (we definitely mess with ccache there).

The ccache logic in Ports/.port_include.sh shouldn't be a problem, since it prepares ccache symlinks and only deals with the serenity toolchain.

2022-12-12 15:37 UTC, timschumi requested changes

2022-12-13 04:34 UTC, ADKaster approved these changes

2022-12-13 04:34 UTC, merged