AK/Platform.h: check for glibc
SerenityOS/serenity pull request #16466
Opened 2022-12-13 10:37 UTC by ddevault

Ref #16463

2022-12-13 11:22 UTC, timschumi requested changes
`glibc` isn't the only libc that implements these functions. If we want to do something like this, dynamically checking if those functions are supported should be the way to go.

Also, again, please note the commit message format.

2022-12-13 11:29 UTC, timschumi commented
In my opinion, if that's the main concern, that variant of the code should just be removed entirely. But as long as there is a maintained code path that uses these functions and it makes implementing it more safe for us, then why not use it everywhere where we can?

2022-12-13 11:31 UTC, linusg commented on AK/Platform.h
> +#endif
Let's move this after AK_COMPILER_* instead of mixing it with the AK_OS_* macros

2022-12-13 11:35 UTC, ddevault commented
>In my opinion, if that's the main concern, that variant of the code should just be removed entirely. But as long as there is a maintained code path that uses these functions and it makes implementing it more safe for us, then why not use it everywhere where we can?

Probably safe to remove the variant. Does it need re-entrancy? I don't think so. It's better to use portable interfaces rather than reach for reentrant interfaces on an unjustified assumption that reentrancy semantics are required. If they are required, a re-entrant implementation of the required functions should be vendored into the project.

2022-12-13 12:22 UTC, ddevault commented
I think the new message aligns with the commit style, let me know if not so.

2022-12-13 21:06 UTC, trflynn89 commented
@ddevault We can check for the presence of these reentrant functions without #ifdef soup, which is implemented over at #16478. Can you check if that works for you / musl?

2022-12-13 22:02 UTC, ddevault commented
I think the new approach is considerably worse. I wash my hands of the matter. I leave the choice of patch at the discretion of the maintainers.

2022-12-15 07:32 UTC, ADKaster commented
This PR is obsolete given the changes that have been merged into master. There are still 3 remaining issues for compiling on a musl host, as I described in https://github.com/SerenityOS/serenity/pull/16323#pullrequestreview-1218671223

After those 3 are addressed, the only remaining action for https://github.com/SerenityOS/serenity/issues/16463 is to figure out where / how often / what provider to run musl CI on. It could probably slot into the nightly Azure next to the run that runs android CI.

2022-12-15 07:32 UTC, closed without merging