LibCore: Change Core::System::mkstemp's argument to a ByteBuffer
SerenityOS/serenity pull request #16702
Opened 2022-12-28 18:16 UTC by kuzux

This leads to cleaner usages in call sites compared to a Span<char>. This commit also removes a FIXME in LibCore/Account.cpp :^)

2022-12-28 18:24 UTC, drunderscore requested changes
Yes, a `Span<char>` makes no sense here, but a `ByteBuffer` by value makes even less sense!

Rather, this should be changed to take a `StringView`.

2022-12-28 18:24 UTC, drunderscore commented on Userland/Libraries/LibCore/Account.cpp
> +#include "AK/Forward.h"
Use angle brackets for AK includes

2022-12-28 18:24 UTC, drunderscore commented on Userland/Libraries/LibCore/Group.cpp
> +#include "AK/Forward.h"
Ditto

2022-12-28 18:53 UTC, timschumi commented
> Rather, this should be changed to take a `StringView`.

A `StringView` isn't writable though.

That said, I don't understand the initial comment to begin with, a `Span<char>` should be perfectly "AK-able", whatever that means. The resulting string doesn't change in length due to the placeholder, so all one needs to do is preparing a `ByteBuffer` externally and passing in the `Span` to that.

2022-12-28 19:38 UTC, kuzux commented
As for using a `StringView`; that was what I initially wanted to do as well, but the function modifies the span and callers generally use the modified span to get the filename.

For retaining a span; `ByteBuffer::span()` returns a `Span<u8>` value, which is not simply convertible to a `Span<char>`.

2022-12-28 19:59 UTC, drunderscore commented
> A StringView isn't writable though.

Oops, I didn't recall that `mkstemp` modifies the given buffer! Absolutely correct.

Then I believe `Span<char>` is correct, even if it looks weird -- because our `String`s are immutable, it's a very odd API to work with. Certainly don't believe the API itself needs to care about `ByteBuffer`s, especially ones that are passed by value.

2022-12-29 06:50 UTC, kuzux commented
So, what would be the best solution to make calling mkstemp less awkward?

* Make mkstemp take a ByteBuffer argument (perhaps by reference?)
* Make mkstemp take a Span<u8> as argument, create a ByteBuffer at call site and pass its .span()
* Have mkstemp continue taking a Span<char>, but add a reinterpret_as<U>() function to Span to convert a Span<u8> to Span<char>. Then create a ByteBuffer at call site and pass its .span(). reinterpret_as<char>()
* Have mkstemp continue taking a Span<char>, create a ByteBuffer at call site, create a new Span<char> from ByteBuffer's span
* Leave things as-is, dealing with char pointers
* Something else entirely?

2022-12-29 13:35 UTC, timschumi commented
Passing in a `ByteBuffer` (either by value or by reference) sounds needlessly restrictive, surely someone will find a way to require `mkstemp` that only needs part of a `ByteBuffer` or none at all.

As for all the variants taking a `Span`, those sound more likely, but I'm not a particular fan of reinterpreting the contents. You'd also have to explain the difference between your option 2 and option 4 is, as those look basically the same to me.

2022-12-29 14:22 UTC, kuzux commented
For the difference between option 2 and option 4, looks like the difference between `Span<char>` and `Span<u8>` got eaten by github formatting when they were not inside backticks :)

Demonstrating the difference between option 2 and option 4 should be simpler in code

One is
```
mkstemp(Span<u8> pattern);

// in call site
ByteBuffer pattern("stuff.XXXXXX"sv);
mkstemp(pattern.span());
```

While the other is more like
```
mkstemp(Span<char> pattern);

// in call site
ByteBuffer pattern("stuff.XXXXXX"sv);
auto char_span = Span<char> { pattern.data(), pattern.size() }
mkstemp(char_span);
```

2023-01-08 11:36 UTC, timschumi commented
Even if it seems more ugly on the user side, I feel like taking a `Span<char>` would be the correct thing to do here. Users that don't use a `ByteBuffer` at all won't be affected by this in the slightest, and for everyone else, maybe a `Buffer<char>` (and a matching `using ByteBuffer = Buffer<u8>`) will come along some time in the future.

2023-01-10 14:35 UTC, kuzux commented
PR #16946 does not change the original method in LibCore but only changes the call site

2023-01-10 14:35 UTC, closed without merging