LibWeb+LibJS: Format Console arguments with JS::Print
SerenityOS/serenity pull request #16914
Opened 2023-01-08 19:20 UTC by ADKaster

Instead of just calling JS::Value::to_string_without_side_effects() when
printing values to the console, have all the console clients use
the same JS::Print that the REPL does to print values.

This method leaves some things to be desired as far as OOM hardening
goes, however. We should be able to create a String in a way that
doesn't OOM on failure so hard.

Before: 
![Screenshot from 2023-01-08 11-25-05](https://user-images.githubusercontent.com/8388494/211214694-07b1a4a5-2079-44b3-90ea-d8902dbe02f2.png)

After:

![Screenshot from 2023-01-08 11-04-04](https://user-images.githubusercontent.com/8388494/211214703-eafc3ec1-3c99-4307-b2c8-9b79d4be7d57.png)

2023-01-08 19:24 UTC, ADKaster commented on Userland/Libraries/LibJS/Print.cpp
> +    size_t original_num_seen_objects = seen_objects.size();
This is an ugly hack, but without it printing even the simplest HTML Element will end up printing essentially every single element in the DOM due to all the cross-links b/w nodes.

2023-01-31 10:06 UTC, linusg requested changes

2023-02-16 11:32 UTC, AtkinsSJ commented
It's conflict o'clock :clock10:

2023-02-20 10:54 UTC, linusg requested changes

2023-02-20 17:26 UTC, ADKaster commented on AK/String.cpp
> +    static ErrorOr<NonnullRefPtr<StringData>> from_stream(Stream&, size_t count);
Ack I thought I got all of them when I changed that name during development. Let me know when we want to start enforcing select clang-tidy rules in CI 😅. I'm pretty sure it complains about this.

2023-02-21 09:57 UTC, merged