df+du+ls: Add an option to print the human readable sizes in powers of 10
SerenityOS/serenity pull request #16944
Opened 2023-01-10 12:11 UTC by kuzux

2023-01-13 13:04 UTC, supercomputer7 approved these changes
Seems OK to me, as long as you tested it and it looked OK :)

2023-01-15 12:26 UTC, GMTA commented
This is not right - only `df` works with `-H` as an argument, but `du` and `ls` dereference symbolic links when you pass them that short option. Those last two tools use the long opt `--si` only.

2023-01-15 12:26 UTC, GMTA commented on Userland/Utilities/du.cpp
> +    args_parser.add_option(du_option.human_readable_si, "Print human-readable sizes in SI units", "si", 'H');
`du` does not use `-H` for this; please remove

2023-01-15 12:27 UTC, GMTA commented on Userland/Utilities/ls.cpp
> +    args_parser.add_option(flag_human_readable_si, "Print human-readable sizes in SI units", "si", 'H');
`ls` does not use `-H` for this; please remove and leave `--si`

2023-01-15 12:27 UTC, GMTA requested changes
Two `-H` short options should be removed.

2023-01-15 18:05 UTC, GMTA approved these changes
LGTM!

2023-01-15 18:12 UTC, merged