LibGfx+ImageViewer: Add option to load raw bitmap binary files as pictures
SerenityOS/serenity pull request #17015
Opened 2023-01-14 15:56 UTC by supercomputer7

Related to #16574.
When generating a binary file containing the raw bitmap data of a picture, we could now view it in the `ImageViewer` application without a problem :)

2023-01-15 12:14 UTC, GMTA requested changes

2023-01-15 12:14 UTC, GMTA commented on Userland/Applications/ImageViewer/main.cpp
> +    }
These one-line `if`-blocks do not need their braces (maybe remove them for `if (path)` below as well?)

2023-01-15 12:14 UTC, GMTA commented on Userland/Applications/ImageViewer/ViewWidget.cpp
> +            return;
This can be an early return by moving it up, removing one level of indentation

2023-01-15 12:14 UTC, GMTA commented on Userland/Applications/ImageViewer/ViewWidget.h
> +    void set_forced_dimensions(Gfx::IntSize dimensions);
You seem to be using this API for two purposes:
- read in binary data for specific dimensions;
- crop a loaded bitmap to specific dimensions.

What if I want to do both? I.e. load a binary bitmap with specific dimensions, then crop them? I think this should be two separate APIs and two separate command line arguments. And in this case, the newly added functionality of cropping an image in ImageViewer (for whatever reason we may want to do so) should be a separate commit.

Ideally this also gets rid of all the `.clear()`s that are now required.

2023-01-15 12:14 UTC, GMTA commented on Userland/Applications/ImageViewer/ViewWidget.cpp
> +}
I'd leave these inline, similar to `set_scaled_for_first_image`

2023-01-15 12:14 UTC, GMTA commented on Base/usr/share/man/man1/Applications/ImageViewer.md
> +* `-b [bgrx, bgra, rgbx, rgba]`, `--bitmap-format [bgrx, bgra, rgbx, rgba]`: Force bitmap format when decoding as a raw binary bitmap file
Couldn't we use `Bitmap`s naming of these formats instead? They are a bit longer, but prevents issues in the future if we were to add other RGBA formats that are not stored as 4 sequential bytes.

2023-01-15 12:14 UTC, GMTA commented on Base/usr/share/man/man1/Applications/ImageViewer.md
> +* `-h Height`, `--height Height`: Force height when displaying an image
Width/Height -> width/height

I.e. similar to `bitmap_format` and matches the arguments as provided to `ArgsParser`

2023-01-15 12:14 UTC, GMTA commented on Userland/Libraries/LibGfx/Bitmap.cpp
> +    unsigned expected_size_max = Bitmap::minimum_pitch(size.width() * scale_factor, format) * size.height() * scale_factor;
Can this `unsigned` be a `size_t` instead?

2023-04-13 05:49 UTC, supercomputer7 commented
Let's try this again.

2023-04-14 15:14 UTC, AtkinsSJ commented
This has conflicts. (Not sure if that happened before or after your last comment.)

2023-05-06 18:59 UTC, GMTA commented
> Let's try this again.

Discussions are still unresolved

2023-06-15 20:54 UTC, closed without merging