LibWeb: Update stylesheet loading to use fetch infrastructure
SerenityOS/serenity pull request #17016
Opened 2023-01-14 16:09 UTC by srikavin

This replaces the adhoc stylesheet loading implementation with one that more closely follows the spec, fixing some issues with stylesheet load events not firing.

2023-01-14 16:59 UTC, MacDue commented
Looks like you have some linter errors

(Just as an FYI you might want to setup the pre-commit to catch these before pushing: https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#commit-hooks)

2023-01-14 20:14 UTC, linusg requested changes

2023-01-14 20:14 UTC, linusg commented on Userland/Libraries/LibWeb/Fetch/Body.cpp
> +            // FIXME: run errorSteps with that exception.
Same here

2023-01-14 20:14 UTC, linusg commented on Userland/Libraries/LibWeb/Fetch/Body.h
> +[[nodiscard]] JS::NonnullGCPtr<JS::Promise> consume_body(JS::Realm& realm, BodyMixin const& object, JS::SafeFunction<WebIDL::ExceptionOr<JS::Value>(AK::ByteBuffer)> convertBytesToJSValue);
Drop AK prefix, snake case

2023-01-14 20:14 UTC, linusg commented on Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Bodies.cpp
> +void Body::fully_read(JS::SafeFunction<void(ByteBuffer)> process_body, JS::SafeFunction<void()> process_body_error,
Use `TaskDestination` alias instead of typing out the variant again

2023-01-14 20:14 UTC, linusg commented on Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Bodies.h
> +    void fully_read(JS::SafeFunction<void(ByteBuffer)>, JS::SafeFunction<void()>, Variant<Empty, JS::NonnullGCPtr<JS::Object>>) const;
Likewise

2023-01-14 20:14 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/CORSSettingAttribute.cpp
> +CORSSettingAttribute cors_setting_attribute_from_keyword(DeprecatedString keyword)
This can take a StringView

2023-01-14 20:14 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/CORSSettingAttribute.cpp
> +    if (keyword.is_null()) {
Never use null strings in new code, use `Optional<T>` instead

2023-01-14 20:14 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/CORSSettingAttribute.cpp
> +}
Missing newline before closing namespace

2023-01-14 20:14 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/CORSSettingAttribute.h
> +CORSSettingAttribute cors_setting_attribute_from_keyword(DeprecatedString);
Make return value `[[nodiscard]]`

2023-01-14 20:14 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/PotentialCORSRequest.cpp
> +#include "PotentialCORSRequest.h"
Use `<LibWeb/*>` include style

2023-01-14 20:14 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/PotentialCORSRequest.cpp
> +}
Missing newline before closing namespace

2023-01-14 20:14 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/PotentialCORSRequest.h
> +namespace Web::HTML {
Missing newline after opening namespace

2023-01-14 20:14 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/PotentialCORSRequest.h
> +}
Missing newline before closing namespace

2023-01-14 20:14 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/PotentialCORSRequest.h
> +JS::NonnullGCPtr<Fetch::Infrastructure::Request> create_potential_CORS_request(JS::VM&, const AK::URL&, Optional<Fetch::Infrastructure::Request::Destination>, CORSSettingAttribute, SameOriginFallback
nodiscard

2023-01-14 20:14 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
> -
Put this back :)

2023-01-14 20:14 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
> -
Put this back :)

2023-01-15 11:01 UTC, srikavin commented on Userland/Libraries/LibWeb/Fetch/Body.cpp
> +        //       even though the spec states this callback takes 'error'.
I might be misunderstanding the spec, but the spec's definition and use of `fully read` appear to be inconsistent.

The [definition for `fully read`](https://fetch.spec.whatwg.org/commit-snapshots/464326e8eb6a602122c030cd40042480a3c0e265/#body-fully-read) states `processBodyError must be an algorithm accepting no arguments`, and step 4 is `...If that threw an exception, then run errorSteps with that exception and return.` (and `errorSteps` isn't defined to take a parameter).

In this instance, processBodyError takes an error argument, but it's also used in [`fetch response handover`](https://fetch.spec.whatwg.org/commit-snapshots/464326e8eb6a602122c030cd40042480a3c0e265/#ref-for-fetch-params-process-response-consume-body%E2%91%A0) without the error parameter.

I guess we could just have `fully read` expect a `JS::Value exception` argument in the error callback, and have it be unused in the callback created in fetch response handover.

2023-01-15 11:21 UTC, linusg commented on Userland/Libraries/LibWeb/Fetch/Body.cpp
> +        //       even though the spec states this callback takes 'error'.
Yeah, let's always add the parameter to the callback, provide undefined where the argument is omitted by the spec, and ignore is where unused by the spec within the callback body 👍

2023-02-04 22:48 UTC, ADKaster commented
Whoops, I re-requested a review from linus but it looks like this has conflicts with Fetch/Body.cpp now.

2023-03-18 00:50 UTC, linusg commented
@srikavin would you mind fixing the conflicts? :)

2023-03-18 03:18 UTC, srikavin commented
Whoops, I completely forgot about this.

I dropped the first two commits and rebased on master. I'm not entirely sure how to properly propagate errors relating to converting attribute values from `DeprecatedString` to `String`s with the current design, so I just used `release_value_but_fixme_should_propagate_errors`.

2023-03-18 16:05 UTC, linusg reviewed
Looks great, thanks! Two small issues, happy to merge afterwards :)

2023-03-18 16:05 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
> +    (void)Fetch::Fetching::fetch(
This should probably not ignore errors, let's use `release_value_but_fixme_should_propagate_errors()` on the return value for better visibility

2023-03-19 14:16 UTC, merged