Kernel+Userland: Refine preventing syscall annotations of Regions option
SerenityOS/serenity pull request #17096
Opened 2023-01-19 22:40 UTC by supercomputer7

The idea behind this is to remove the special case of handling a `nullptr` virtual address in `annotate_mapping`, therefore simplifying the syscall to some extent. It also makes perfect sense to disallow annotations of more regions as syscall regions with the `prctl` syscall, so let's do it that way :)

2023-01-20 08:19 UTC, supercomputer7 commented
Seems like there was a CI flakes again in our Azure CI/CD, because it stopped when trying to install Ubuntu packages...

2023-02-14 16:45 UTC, supercomputer7 commented
This is not stale.

2023-02-24 19:23 UTC, linusg requested changes

2023-02-24 19:23 UTC, linusg commented on Kernel/Syscalls/prctl.cpp
>          }
I don't think these curly braces are needed; the rule we have for multiple if/else branches needing curlies doesn't spply to switch statements :)

2023-02-24 21:26 UTC, merged