Kernel+LibC: Support monotonic clock in clock_getres()
SerenityOS/serenity pull request #17154
Opened 2023-01-24 00:19 UTC by hjalves

Add `CLOCK_MONOTONIC` as a supported clock_id. Also, fix this function to use the actual ticks per second value, not the constant `_SC_CLK_TCK`, which is always equal to 8.

This enables functionality in certain ports, such as the use of asyncio in Python.

Before fix:

![before-fix](https://user-images.githubusercontent.com/2660905/214181659-dbace87b-4553-45e0-89f6-06977653bea4.png)

After fix:

![after-fix](https://user-images.githubusercontent.com/2660905/214181700-4842bae1-ea0e-44a1-8ee3-bcc2c5a10fe1.png)

2023-01-24 00:24 UTC, timschumi commented
In that case, wouldn't we want to add the remaining clocks there as well? Also, maybe it's time to move "get the clock resolution" into `TimeManagement`, since we already have "get the actual clock value" in there.

2023-01-28 15:14 UTC, konradekk commented on Kernel/Syscalls/clock.cpp
> +        ts.tv_nsec = 1000000000 / TimeManagement::the().ticks_per_second();
while visiting… care to add digit separator? 🫣

2023-02-02 13:45 UTC, awesomekling commented
Some good review comments here.

2023-02-20 21:20 UTC, hjalves commented
Thank you everyone for the comments. I've just pushed the branch with the suggestions aforementioned.

2023-02-20 23:08 UTC, linusg requested changes

2023-02-20 23:08 UTC, linusg commented on Kernel/Time/TimeManagement.cpp
> +    long nanos_per_tick = 1'000'000'000 / m_time_keeper_timer->ticks_per_second();
`nanoseconds_per_tick` as per https://github.com/SerenityOS/serenity/blob/master/Documentation/CodingStyle.md#names

2023-02-20 23:21 UTC, linusg reviewed
ah, one more thing - since this doesn't actually touch LibC, the commit title should be something like `Kernel: Support more clocks in sys$clock_getres()`. Code LGTM though :)

2023-02-21 00:00 UTC, merged