Remove uses of DeprecatedString in file utility.
SerenityOS/serenity pull request #17266
Opened 2023-02-01 19:44 UTC by vkoskiv

Found out that most of it can just be `StringView` anyway, because the source strings are static byte arrays.

2023-02-01 19:49 UTC, MacDue reviewed
Some nit picks:

2023-02-01 19:49 UTC, MacDue commented on Userland/Utilities/file.cpp
> +static ErrorOr<Optional<String>> gzip_details(StringView const& description, StringView const& path)
And here:
```suggestion
static ErrorOr<Optional<String>> gzip_details(StringView description, StringView path)
```

2023-02-01 19:51 UTC, linusg requested changes
Missing punctuation in first commit message:

https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#human-language-policy
> The following applies to all user-facing strings, code, comments, and commit messages:
> - Use proper spelling, grammar, and punctuation.

2023-02-01 19:51 UTC, linusg commented on Userland/Libraries/LibCore/MimeData.cpp
> +    return OptionalNone {};
This shouldn't be needed (you didn't change `mime_type_for_file()` either)

2023-02-01 19:51 UTC, linusg commented on Userland/Utilities/file.cpp
> +static ErrorOr<Optional<String>> description_only(StringView const& description, [[maybe_unused]] StringView const& path)
Never pass string views by const reference, always by value

2023-02-01 19:51 UTC, linusg commented on Userland/Utilities/file.cpp
> +static ErrorOr<Optional<String>> image_details(StringView const& description, StringView const& path)
Same here, and below

2023-02-01 19:51 UTC, linusg commented on Userland/Utilities/file.cpp
> +        is_dynamically_linked ? dynamic_section : String()));
`String {}` for consistency with other code using the new empty string

2023-02-01 19:52 UTC, linusg commented on Userland/Utilities/file.cpp
> +static ErrorOr<Optional<String>> description_only(StringView const& description, [[maybe_unused]] StringView const& path)
For reference: https://github.com/SerenityOS/serenity/commit/8b1108e4858f797c9216dc8ae4a3918ad50c73b4

2023-02-01 20:05 UTC, vkoskiv commented
Thanks for the good feedback @MacDue and @linusg !

Fixups amended.

2023-02-01 22:29 UTC, trflynn89 reviewed
Seems like there's several errors that should be propagated now that some of the handlers return ErrorOr (feel free to do that as a separate commit or PR even).

2023-02-01 22:29 UTC, trflynn89 commented on Userland/Utilities/file.cpp
>      auto& mapped_file = *file_or_error.value();
Now that we're returning ErrorOr, this feels like an error we should propagate.
```c++
auto mapped_file = TRY(Core::MappedFile::map(path));
```

2023-02-01 22:29 UTC, trflynn89 commented on Userland/Utilities/file.cpp
>      auto file_or_error = Core::MappedFile::map(path);
Same here

2023-02-01 22:29 UTC, trflynn89 commented on Userland/Utilities/file.cpp
>      auto file_or_error = Core::MappedFile::map(path);
Same here

2023-02-01 22:29 UTC, trflynn89 commented on Userland/Utilities/file.cpp
>      auto result_or_error = ELF::validate_program_headers(*(const ElfW(Ehdr)*)elf_data.data(), elf_data.size(), elf_data, &interpreter_path_builder);
Same here

2023-02-02 15:12 UTC, vkoskiv commented
Done, errors now propagate from file detail provider functions. Reduced lines of code!

2023-02-02 15:32 UTC, trflynn89 commented
So I think the first commit isn't needed (or rather isn't the right fix). We already define

2023-02-02 15:34 UTC, trflynn89 commented
So I think the first commit isn't needed (or rather isn't the right fix). We already define this HashCompatible override in StringUtils.h:
https://github.com/SerenityOS/serenity/blob/9a2ee5a9dd792359440429832ac564f5dde2b315/AK/StringUtils.h#L17-L18

That *should* work for `String` as well. The problem is it doesn't work at all and will need to be fixed separately:
https://discord.com/channels/830522505605283862/860165510263996427/1070727121225388152

2023-02-02 15:36 UTC, vkoskiv commented
> So I think the first commit isn't needed (or rather isn't the right fix). We already define this HashCompatible override in StringUtils.h:
> 
> https://github.com/SerenityOS/serenity/blob/9a2ee5a9dd792359440429832ac564f5dde2b315/AK/StringUtils.h#L17-L18
> 
> That _should_ work for `String` as well. The problem is it doesn't work at all and will need to be fixed separately: https://discord.com/channels/830522505605283862/860165510263996427/1070727121225388152

This PR won't compile without it, so it cannot be merged without it.

2023-02-02 15:37 UTC, trflynn89 commented
> This PR won't compile without it, so it cannot be merged without it.

I know - I'm working on a fix. But we also shouldn't merge this PR *with* it because it isn't right (which I understand is unfortunate and annoying).

2023-02-02 15:40 UTC, vkoskiv commented
OK

2023-02-02 15:41 UTC, trflynn89 commented
You can leave the PR open if you want :sweat_smile: I would just mark it a draft or add a blocked label

2023-02-02 16:53 UTC, vkoskiv commented
@trflynn89 Dropped the AK commit, this is now blocked on the appropriate fix.

2023-02-02 16:54 UTC, vkoskiv commented
I can't seem to add a "Blocked" label, though!

2023-02-02 16:54 UTC, vkoskiv commented
Thanks :D

2023-04-18 04:58 UTC, closed without merging