js: Remove usage of DeprecateString
SerenityOS/serenity pull request #17306
Opened 2023-02-04 02:46 UTC by evansmal

This removes usage of DeprecatedString throughout the `js` utility. Let me know if a different method of error propagation is preferred.

2023-02-05 12:28 UTC, Hendiadyoin1 commented on Userland/Utilities/js.cpp
> +        const auto& traceback = static_cast<JS::Error const&>(thrown_value.as_object()).traceback();
We use east-const in this project

2023-02-08 15:13 UTC, linusg requested changes
Please squash or reword a couple of those commits, there shouldn't me multiple with the exact same message (`js: Remove DeprecatedString usage`)

2023-02-08 15:13 UTC, linusg commented on Userland/Utilities/js.cpp
> +            editor.set_prompt(MUST(prompt_for_level(open_indents)).to_deprecated_string());
Don't use MUST here, use
https://github.com/SerenityOS/serenity/blob/1ce34805f81be6b5c544a7f9aa03505d1b46ff26/AK/Error.h#L152

2023-02-08 15:13 UTC, linusg commented on Userland/Utilities/js.cpp
> +        String piece = TRY(read_next_piece());
`auto`

2023-02-08 15:13 UTC, linusg commented on Userland/Utilities/js.cpp
> +    String save_path = TRY(vm.argument(0).to_string(vm));
`auto`

2023-02-08 16:39 UTC, evansmal commented
@linusg Thanks for the review :^)

I've reworked the commits wih (hopefully) some better commit messages. Let me know what you think.

2023-02-08 16:48 UTC, merged