AK+Piano+LibGUI: Prepare for per-track controls
SerenityOS/serenity pull request #17391
Opened 2023-02-09 14:40 UTC by kleinesfilmroellchen

This is an assortment of bug fixes, layouting improvements, and small Piano refactors in order to prepare for per-track controls in Piano.

The LibGUI fixes make dynamic layouting work better with labels and sliders, as you can see in these screenshots:

2023-02-10 00:23 UTC, frhun commented
This has some overlap with [set_fixed_size](https://github.com/SerenityOS/serenity/pull/17407).

2023-02-10 00:26 UTC, frhun commented on Userland/Libraries/LibGUI/Slider.cpp
> +    size.set_secondary_size_for_orientation(orientation(), calculated_min_size()->secondary_size_for_orientation(orientation()));
Just setting it to `SpecialDimension::Shrink` is the more ideomatic way of achieving this.

2023-02-17 23:18 UTC, kleinesfilmroellchen commented
@frhun I think I removed all conflicting layout changes and it looks fine on master now that your PR is merged.

2023-02-21 08:43 UTC, AtkinsSJ requested changes
From a fairly quick phone review, this looks good, I just have one nitpick.

2023-02-21 08:43 UTC, AtkinsSJ commented on Userland/Applications/Piano/MainWidget.cpp
> +    (void)TRY(m_octave_container->try_set_layout<GUI::VerticalBoxLayout>());
The (void) here is no longer needed.

2023-02-26 03:49 UTC, merged