LibGUI: Fix annoying slider imperfections
SerenityOS/serenity pull request #17689
Opened 2023-03-01 20:55 UTC by andreao

2023-03-01 20:59 UTC, awesomekling requested changes

2023-03-01 21:47 UTC, andreao commented on Userland/Libraries/LibGUI/Slider.cpp
> +        return;
Right, I'll write it behind my ear and leave out the commit.

2023-03-01 21:53 UTC, andreao commented on Userland/Libraries/LibGUI/Slider.cpp
> +        return;
In some other UI frameworks there is the concept of mouse enter/leave. Would that be an idea for a better solution in LibGUI?

2023-03-02 10:46 UTC, awesomekling commented on Userland/Libraries/LibGUI/Slider.cpp
> +        return;
There are already mouse enter/leave events. (See `Widget::enter_event` and `Widget::leave_event`)

Re: writing it behind your ear, please open an issue about it instead. Then we don't have to remember to look behind your ear :)

2023-03-02 20:24 UTC, andreao commented on Userland/Libraries/LibGUI/Slider.cpp
> +        return;
Don't know how I missed those, thanks :)
Agree about opening an issue instead as my ears have a tendency to get washed every morning... but even better to try to fix it myself! Your intuition was right that we should track this down, as it turns out to be caused by fake mouse events sent from `WindowManager.reevaluate_hover_state_for_window`, which causes dragging to be interrupted. Just gotta figure out how to best fix it :)

2023-03-02 21:07 UTC, andreao commented on Userland/Libraries/LibGUI/Slider.cpp
> +        return;
Opened issue to get some feedback: https://github.com/SerenityOS/serenity/issues/17695

2023-03-24 09:33 UTC, merged