Kernel: Merge {get,set}_process_name syscalls to the prctl syscall
SerenityOS/serenity pull request #17728
Opened 2023-03-05 18:53 UTC by supercomputer7

It makes much more sense to have these actions being performed via the prctl syscall, as they both require 2 plain arguments to be passed to the syscall layer, and in contrast to most syscalls, we don't get in these removed syscalls an automatic representation of Userspace<T>, but two FlatPtr(s) to perfrom casting on them in the prctl syscall which is suited to what has been done in the removed syscalls.

Also, it makes sense to have these actions in the prctl syscall, because they are strongly related to the process control concept of the prctl syscall.

2023-03-07 23:11 UTC, kleinesfilmroellchen requested changes
Very neat :^)

2023-03-07 23:11 UTC, kleinesfilmroellchen commented on Kernel/Syscalls/prctl.cpp
> +            size_t buffer_size = static_cast<size_t>(arg2);
This would be more readable as `static_cast<size_t>(user_buffer_size)`

2023-03-11 22:39 UTC, kleinesfilmroellchen approved these changes

2023-03-12 11:52 UTC, GMTA approved these changes

2023-03-12 11:54 UTC, GMTA requested changes
Typo in commit:
> to perfrom casting

2023-03-15 19:10 UTC, GMTA approved these changes

2023-03-15 19:10 UTC, merged