LibGUI+SpaceAnalyzer: Improve shortcut invocation for non-visible actions
SerenityOS/serenity pull request #17750
Opened 2023-03-07 18:03 UTC by tcl3

This PR fixes two seperate but related issues around the handling of shortcuts for non-visible actions.

1. Non-visible shortcuts are no longer invokable - this fixes an issue in PixelPaint, where the "Add Mask" action could be invoked with its shortcut key when non-visible.
2. Multiple globally scoped actions can be registered which share the same shortcut. This fixes an issue in SpaceAnalyzer where the wrong action could be invoked when multiple actions shared the same shortcut.

2023-03-08 11:35 UTC, kleinesfilmroellchen requested changes

2023-03-08 21:38 UTC, kleinesfilmroellchen approved these changes

2023-03-09 20:47 UTC, awesomekling commented
I am skeptical of the change `LibGUI: Allow multiple globally scoped actions to share a shortcut`

Having multiple global actions with the same shortcut seems like poor design.

"It works because I ensure that my program only lets one of the actions be enabled and visible at any given time" is a pretty sloppy contract :)

2023-03-10 17:57 UTC, tcl3 commented
> I am skeptical of the change LibGUI: Allow multiple globally scoped actions to share a shortcut

Yeah, I agree. I've gotten rid of this change. My latest push fixes the SpaceAnalyzer issue by combining the "Reveal in File Manager" and "Open in File Manager" actions into a single action, which changes behavior based on what is currently selected.

2023-03-11 14:03 UTC, kleinesfilmroellchen approved these changes

2023-03-15 23:02 UTC, merged