LibWeb: Support more length types in SVG width/height attributes
SerenityOS/serenity pull request #17922
Opened 2023-03-19 14:58 UTC by MichielVrins

Previously we were using the HTML parse_dimension_value method for the height and width attributes of an SVG element. These attributes should however be treated as css properties instead and thus also support calc() and absolute units so we use the css parser for this instead.

This allows PR allows us to render the following snippet from the SVG specification which has a size of 12cm x 4cm
https://www.w3.org/TR/SVG2/shapes.html#LineElement
```
<svg width="12cm" height="4cm" viewBox="0 0 1200 400"
     xmlns="http://www.w3.org/2000/svg" version="1.1">
  <desc>Example line01 - lines expressed in user coordinates</desc>

  
  <rect x="1" y="1" width="1198" height="398"
        fill="none" stroke="blue" stroke-width="2" />

  <g stroke="green" >
    <line x1="100" y1="300" x2="300" y2="100"
            stroke-width="5"  />
    <line x1="300" y1="300" x2="500" y2="100"
            stroke-width="10"  />
    <line x1="500" y1="300" x2="700" y2="100"
            stroke-width="15"  />
    <line x1="700" y1="300" x2="900" y2="100"
            stroke-width="20"  />
    <line x1="900" y1="300" x2="1100" y2="100"
            stroke-width="25"  />
  </g>
</svg>
```

I have tested that this does **not** break the discord.gg/login and serenityos github page.

2023-03-19 15:39 UTC, AtkinsSJ requested changes
Looks good, just a couple of small nit-picks.

2023-03-19 15:39 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/Layout/SVGSVGBox.cpp
> +        auto width = parse_css_value(CSS::Parser::ParsingContext { document() }, dom_node().attribute(Web::HTML::AttributeNames::width), CSS::PropertyID::Width);
We can get away with just creating the ParsingContext once and passing it to both `parse_css_value()` calls.

2023-03-19 15:39 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/SVG/SVGForeignObjectElement.cpp
> +    if (auto width_value = parse_css_value(CSS::Parser::ParsingContext { document() }, attribute(Web::HTML::AttributeNames::width), CSS::PropertyID::Width))
Same point about the ParsingContext here.

2023-03-20 08:36 UTC, awesomekling requested changes

2023-03-20 08:36 UTC, awesomekling commented on Userland/Libraries/LibWeb/SVG/SVGSVGElement.cpp
> +    auto parsingContext = CSS::Parser::ParsingContext { document() };
Please use `snake_case` instead of `camelCase`.

2023-03-20 22:45 UTC, merged