Applications+Libraries: Move to `LibFileSystem`
SerenityOS/serenity pull request #17985
Opened 2023-03-22 09:39 UTC by cammo1123

Part one of many in the process of moving to `LibFileSystem`. The only remaining usages of `DeprecatedFile` is either using the `open/construct` functions, or inside `LibCore` as it creates a Cyclic import.

2023-03-22 09:51 UTC, cammo1123 commented
CI's just discovered a leak in real_path. Turning into a draft until I can find a fix

2023-03-22 15:39 UTC, linusg requested changes
Missing backtick in second commit message

2023-03-22 15:39 UTC, linusg commented on Userland/Applications/FileManager/DirectoryView.cpp
>          perror("chdir");
Pre-existing bug, but `perror` only prints an error - we also need to return false here!

2023-03-22 15:39 UTC, linusg commented on Userland/Applications/FileManager/main.cpp
> +        initial_location = Core::StandardPaths::home_directory().view();
UAF, the `DeprecatedString` you're pointing into disappears after this line.

2023-03-23 15:34 UTC, linusg commented on Userland/Applications/FileManager/main.cpp
> +            initial_location = error_or_path.release_value().bytes_as_string_view();
Please be explicit here and use to_deprecated_string

2023-03-24 09:39 UTC, linusg commented
This has conflicts 😅

2023-03-24 10:58 UTC, merged