CI: Update `cache` to v3
SerenityOS/serenity pull request #18059
Opened 2023-03-27 13:18 UTC by cammo1123

TODO was waiting new release containing the changes; it was [released in v3](https://github.com/actions/cache/pull/489#issuecomment-1362450032)

2023-03-27 13:28 UTC, linusg requested changes
`CI:`

2023-03-27 14:20 UTC, cammo1123 commented
Marking as draft while i figure out how to run CI locally

2023-03-27 14:32 UTC, MacDue commented
You can run the CI in a fork (I think), or just push here a lot (I don't think there's an easy way to run locally?)

2023-03-27 18:40 UTC, davidot commented
The problem might just be that you're missing a binutils upgrade commit, meaning there's no cache to pull from master.
Just rebasing the branch on master might already be enough.

2023-03-30 11:20 UTC, cammo1123 commented
I rebased and removed the additional set-output commit, as I can't quite figure out how to do it.

2023-04-27 13:05 UTC, closed without merging