Base: Update man page for utilities
SerenityOS/serenity pull request #18108
Opened 2023-03-30 22:52 UTC by tcl3

This PR updates the existing man pages for user facing command line programs. These man pages should now document all currently available options. I have also made sure the formatting is consistent between man pages.

2023-03-31 07:07 UTC, AtkinsSJ requested changes
I spotted one typo, but this is very helpful! Thanks for going through all those. :^)

2023-03-31 07:07 UTC, AtkinsSJ commented on Base/usr/share/man/man1/tar.md
> +* `-lzma`: Compress or decompress file using lzma
This should be `--lzma`

2023-03-31 07:19 UTC, tcl3 commented on Base/usr/share/man/man1/tar.md
> +* `-lzma`: Compress or decompress file using lzma
Oops! Well spotted :^)

2023-03-31 07:19 UTC, tcl3 commented
Latest push removes colons from generated markdown header names, for better consistency.

2023-04-01 10:49 UTC, AtkinsSJ approved these changes
👍

2023-04-01 10:49 UTC, merged