LibArchive+Utilities: Add a helper to `Archive::ZipOutputStream` for adding files
SerenityOS/serenity pull request #18107
Opened 2023-03-30 21:26 UTC by caoimhebyrne

Prior to this PR, you'd need to do a bit of manual work (as seen in the `zip` utility) to add a file to a zip via ZipOutputStream. 
**Now, you can just call `add_member_from_path` and let it handle directories and files for you! Amazing, right?**

You also can pass a callback function, which will get called with the file's canonical path, and the deflated amount as a percentage. This is useful for utilities like zip which provide the user with progress updates.

*This is the first PR in a series of a few which aims to improve the experience of ZIP files in Serenity. My next one will be making `FileOperation` support the extraction and creation of zip files so we can do it asynchronously without blocking FileManager.*

2023-03-30 22:25 UTC, LucasChollet commented on Userland/Utilities/zip.cpp
> +            auto const* type = FileSystem::is_directory(source_path) ? "directory" : "file";
A raw pointer :eyes:
`StringView` are preferred.

2023-04-14 17:06 UTC, linusg requested changes

2023-04-14 17:06 UTC, linusg commented on Userland/Libraries/LibArchive/Zip.h
> +    ErrorOr<void> add_directory_from_path(StringView path, bool recurse_through_directories, AddMemberCallback const& callback);
Please make these boolean parameters a `Yes/No` enum class, which is much clearer than `add_member_from_path("/the/path", true, ...)`. Grep for `::Yes` to see some examples :)

2023-04-14 17:07 UTC, linusg commented
Oh, and for the second commit message:

```diff
- Utilities: Use the ZipOutputStream::add_member_from_path helper in zip
+ zip: Use the ZipOutputStream::add_member_from_path helper
```

2023-05-01 14:51 UTC, caoimhebyrne commented
Sorry for the delay, @linusg. I've made those changes :^)

2023-05-14 01:45 UTC, timschumi commented on Userland/Libraries/LibArchive/Zip.cpp
> +    auto file = TRY(Core::File::open(path, Core::File::OpenMode::Read));
There are certainly opportunities for making the API more comfortable, for example by replacing the rather raw `ZipMember` parameter with something that carries a Stream (which provides the data, and ideally automatic size and CRC32), the target file name, and one of our newer datetime types (:mergebait:).

However, I feel like "pass me a path to a file, we'll take it from there" is a bit over the top as far as API simplification goes.

2023-05-14 04:33 UTC, LucasChollet commented on Userland/Libraries/LibArchive/Zip.cpp
> +    auto file = TRY(Core::File::open(path, Core::File::OpenMode::Read));
I really don't have a strong opinion on that. My two cents:
- It makes sense from a user perspective
- The `add_directory` helper seems useful and can only take a path, keeping `add_file_from_path` is coherent IMO

2023-05-14 06:46 UTC, caoimhebyrne commented on Userland/Libraries/LibArchive/Zip.cpp
> +    auto file = TRY(Core::File::open(path, Core::File::OpenMode::Read));
I think a good middle ground for now is to replace the file paths with AK::Stream

2023-05-14 22:04 UTC, caoimhebyrne commented on Userland/Libraries/LibArchive/Zip.cpp
> +    auto file = TRY(Core::File::open(path, Core::File::OpenMode::Read));
@LucasChollet @ADKaster @timschumi In regards to a good middleground for now, do we agree that having an `AK::Stream` being passed to something like `add_file(String path, AK::Stream& stream)` is a good approach? Plus, we also drop the recursing through directories, etc. and make the owner of the `ZipOutputStream` handle all of that?

2023-05-21 23:57 UTC, ADKaster commented on Userland/Libraries/LibArchive/Zip.cpp
> +    auto file = TRY(Core::File::open(path, Core::File::OpenMode::Read));
If the `add_file()` implementation has to open the File via path to query data that the zip compressor needs, then the API still isn't quite right. I would expect the `stream` to be a Core::File. if you open the file handle (fd) in a Core::File and then later open it via path, you've just created a classic file TOCTOU bug. So either taking a Core::File& directly or taking enough information to build up the items in a ZipMember without going crazy with number of arguments would be best.

2023-06-02 16:30 UTC, closed without merging

2023-06-02 16:30 UTC, caoimhebyrne commented
Going to re-do this in a new PR