LibCrypto: Add PBKDF2
SerenityOS/serenity pull request #18191
Opened 2023-04-05 14:02 UTC by stelar7

2023-04-06 18:43 UTC, BenWiederhake approved these changes
I love how clear this is, and now I really get the advantage of inline spec-links. Awesome :D

2023-04-08 23:53 UTC, GMTA requested changes
Nice!

2023-04-08 23:53 UTC, GMTA commented on Userland/Libraries/LibCrypto/Hash/PBKDF2.h
> +        }
You can leave out the braces for single line `if` blocks

2023-04-08 23:53 UTC, GMTA commented on Userland/Libraries/LibCrypto/Hash/PBKDF2.h
> +            }
```suggestion
            key.overwrite((i - 1) * h_len, ti.data(), i == l ? r : h_len);
```

2023-04-09 16:39 UTC, GMTA approved these changes

2023-04-09 23:05 UTC, merged