LibWeb: Add an initial implementation of CRC2D.clip()
SerenityOS/serenity pull request #18212
Opened 2023-04-06 20:21 UTC by MacDue

**Demo:**
![image](https://user-images.githubusercontent.com/11597044/230485776-6506f40b-bf6e-4c3d-9449-dc062619b57c.png)

With this PR you can clip the canvas to any path you like! This implementation

2023-04-07 12:54 UTC, Lubrsi requested changes
Awesome! One little thing

2023-04-08 05:44 UTC, awesomekling requested changes
Strange in commit message: Floor draw origin for in fill path implementation 
Typo in commit message: This initial implementation is fairly native

2023-04-08 05:44 UTC, awesomekling commented on Userland/Libraries/LibWeb/HTML/Canvas/CanvasPathClipper.h
> +struct ScopedCanvasPathClip {
Please use `class` for data structures that aren't just a bunch of values bundled together :)

2023-04-09 14:54 UTC, linusg reviewed
Typo in second commit: `UAE` -> `UAF` (?)

2023-04-09 16:42 UTC, merged