LibWeb: Introduce navigable and traversable
SerenityOS/serenity pull request #18396
Opened 2023-04-16 09:22 UTC by kalenikaliaksandr

it's a part of https://github.com/SerenityOS/serenity/pull/18219
patches from Andreas's navigables work I need to get merge :)

2023-04-16 23:01 UTC, linusg requested changes

2023-04-16 23:01 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/Navigable.h
> +    DeprecatedString id() const;
Let's not introduce more uses of `DeprecatedString` in new code. Also should return a const ref.

2023-04-16 23:01 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
> +    return parent() == nullptr;
`// A top-level traversable is a traversable navigable with a null parent.`

2023-04-16 23:01 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
> +}
Same question here regarding plain getters.

2023-04-17 14:48 UTC, kalenikaliaksandr commented on Userland/Libraries/LibWeb/Forward.h
> +class NavigableContainer;
ah, it's so embarrassing messing up sorting so often, sorry.

2023-04-17 15:11 UTC, linusg commented on Userland/Libraries/LibWeb/Forward.h
> +class NavigableContainer;
no, I'm just being unusually strict about it, most people don't care :)

2023-04-17 15:19 UTC, linusg reviewed
Looks much better, two more things I missed :)

2023-04-17 15:19 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
> +    HTML::VisibilityState system_visibility_state() const { return m_system_visibility_state; };
You can omit `HTML::` here, we're already in the namespace

2023-04-17 15:19 UTC, linusg commented on Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
> +    HTML::VisibilityState m_system_visibility_state { HTML::VisibilityState::Visible };
Likewise

2023-04-19 05:56 UTC, awesomekling commented on Userland/Libraries/LibWeb/HTML/Navigable.h
> +    JS::GCPtr<HTML::Window> active_window();
Let's add a FIXME then, saying that these should be non-null pointers eventually :)

2023-04-19 07:20 UTC, kalenikaliaksandr commented on Userland/Libraries/LibWeb/HTML/Navigable.h
> +    JS::GCPtr<HTML::Window> active_window();
done

2023-04-19 07:52 UTC, kalenikaliaksandr commented on Userland/Libraries/LibWeb/HTML/Navigable.h
> +    JS::GCPtr<HTML::Window> active_window();
I changed it to return non-null now. I will have to figure how to handle problem I described here https://github.com/whatwg/html/issues/9148 without null check on active document but it's ok.

2023-04-19 13:44 UTC, kalenikaliaksandr commented on Userland/Libraries/LibWeb/HTML/Navigable.h
> +    JS::GCPtr<HTML::Window> active_window();
well, I tried to rebase my WIP navigables branch and found out that actually active_document() can return null pointer and it is valid behaviour. for example:
1. `Document::destroy()` set associated navigable's active document to nullptr on step 7 https://html.spec.whatwg.org/multipage/document-lifecycle.html#destroy-a-document
2. `node_navigable()` tries to find navigable associated with a document but and stumble on a navigable with destroyed document https://html.spec.whatwg.org/multipage/document-sequences.html#node-navigable

2023-04-19 16:26 UTC, awesomekling commented on Userland/Libraries/LibWeb/HTML/Navigable.h
> +    JS::GCPtr<HTML::Window> active_window();
Yeah all right. We can come back to this later :)

2023-04-19 16:26 UTC, merged