AK+Everywhere: Add new failable JsonArray::{append/set} functions
SerenityOS/serenity pull request #18409
Opened 2023-04-17 06:11 UTC by cammo1123

Quite the Yakhole was explored here. Initially started off trying to `Convert JsonArrayModel to use Core::File` but these changes made it a lot easier to do so.

2023-04-17 07:42 UTC, GMTA requested changes

2023-04-17 07:49 UTC, cammo1123 commented on AK/JsonArray.h
> +    void must_set(size_t index, JsonValue value) { m_values.insert(index, move(value)); }
Doesn't it already do that internally? Or should i `MUST` it manually?

https://github.com/SerenityOS/serenity/blob/f0dde6236d8fbd1ae17e33f868df139467872768/AK/Vector.h#L257-L269

2023-04-17 07:50 UTC, cammo1123 commented on AK/JsonArray.h
> +    ErrorOr<void> set(size_t index, JsonValue value) { return TRY(m_values.try_insert(index, move(value))); }
Oh! didn't know that :^)

2023-04-17 07:55 UTC, GMTA commented on AK/JsonArray.h
> +    void must_set(size_t index, JsonValue value) { m_values.insert(index, move(value)); }
I could have sworn I read `try_*` methods there, you are right! These don't need additional `MUST`s :-)

2023-04-17 08:15 UTC, cammo1123 commented on Userland/Applications/BrowserSettings/BrowserSettingsWidget.h
>      C_OBJECT(BrowserSettingsWidget)
Learning lots of things!

2023-04-17 08:15 UTC, cammo1123 commented on Userland/Applications/BrowserSettings/BrowserSettingsWidget.cpp
> +    auto widget = adopt_ref(*new BrowserSettingsWidget);
Learning lots of things :^)

2023-04-22 07:12 UTC, AtkinsSJ commented
This has conflicts.

2023-04-24 07:21 UTC, merged