Kernel: Introduce basic USB HID support (keyboard and mouse)
SerenityOS/serenity pull request #18673
Opened 2023-05-06 08:42 UTC by supercomputer7

Work derived from #12885.
Relies on #18574, #18654, #18342.

2023-06-28 15:42 UTC, kleinesfilmroellchen requested changes
Some review of the Mouse/Keyboard commits; I'm surprised the changes are this straightforward and readable for someone mostly unfamiliar with USB like me!

2023-06-28 15:42 UTC, kleinesfilmroellchen commented on Kernel/Bus/USB/USBConfiguration.cpp
> +                memcpy(&endpoint_descriptor, raw_endpoint_descriptor_offset, sizeof(USBEndpointDescriptor));
AK::TypedTransfer?

2023-06-28 15:42 UTC, kleinesfilmroellchen commented on Kernel/Bus/USB/USBConfiguration.cpp
> +                memcpy(&descriptor, &m_descriptor, sizeof(USBConfigurationDescriptor));
TypedTransfer here as well?

2023-06-28 15:42 UTC, kleinesfilmroellchen commented on Kernel/Bus/USB/USBConfiguration.cpp
> +                }
Use dbgln_if instead

2023-06-28 15:42 UTC, kleinesfilmroellchen commented on Kernel/Devices/HID/USB/MouseDevice.cpp
> +        char packet_raw[6];
`i8` instead to force the signedness.

2023-06-28 15:42 UTC, kleinesfilmroellchen commented on Meta/run.sh
> +        -machine vmport=off
A USB/PS2 switch should be configurable via a `SERENITY_HID_HARDWARE={usb,ps2}` env var like we have with much other hardware.

2023-09-13 09:46 UTC, FireFox317 reviewed
Some small things I noticed while trying to integrate this code for aarch64 mouse/keyboard support.

2023-09-13 09:46 UTC, FireFox317 commented on Kernel/Bus/USB/USBConfiguration.cpp
> +                    m_device.set_interrupt_in_pipe({}, move(interrupt_in_pipe));
I think we should store the `InterruptInPipe` in the `USB{Mouse,Keyboard}Device`, instead of storing it into the `USBDevice`.

2023-09-13 09:46 UTC, FireFox317 commented on Kernel/Bus/USB/USBDescriptors.h
> +static constexpr u8 DESCRIPTOR_TYPE_HID = 0x21;
Doesn't seem to be used anywhere?

2023-12-16 14:49 UTC, supercomputer7 commented
I will re-open this later.

2023-12-16 14:49 UTC, closed without merging