LibGUI: Increase autoscroll threshold value
SerenityOS/serenity pull request #18714
Opened 2023-05-07 19:11 UTC by AhmedTheGeek

Resolves #18398

The current auto-scroll threshold value of `20` is a little too low which causes a very slow rubberband auto-scroll.

I played with multiple values and `70` feels like a sweet spot.

2023-05-07 19:20 UTC, konradekk commented
not sure what the current effect is, but i thought that maybe introducing some non-linearity in `automatic_scroll_delta_from_position` could also be a thing: the farther from the edge you are, the more the delta is growing? (not sure what kind of linearity would be good enough™, though; maybe what youʼve proposed is exactly whatʼs needed.)

2023-05-07 19:38 UTC, AhmedTheGeek commented
@konradekk Yeah, I get your concern, I think it's going to be fine because the delta change is always triggered at the same position regardless of the of the threshold `delta.set_y(clamp(-(m_autoscroll_threshold - pos.y()), -m_autoscroll_threshold, 0));`

I recorded this video to show the effect

[Screencast from 2023-05-07 22-30-58.webm](https://user-images.githubusercontent.com/1913834/236699102-4e6912a1-1e35-411e-b9bc-18494204801c.webm)

2023-05-07 19:49 UTC, konradekk commented
oh! looks nice! thanks for the capture! could you check other types of view on whether those are usable? (i believe theyʼre – no need for visual proof if you feel those are sensible and okay!)

2023-05-07 20:31 UTC, GMTA commented
Arguably this makes an edge case significantly worse: if you start selecting at the top of a window that's already scrolled down, it immediately starts scrolling up before you can move your mouse down to select icons.

https://user-images.githubusercontent.com/3210731/236701193-1165b928-5740-4bb5-8738-dc6dafbb1dfa.mp4

Also what @konradekk seems to be hinting at, is that the effect should be larger if you move your mouse further outside the window. This is not the case as far as I can see, but possibly also out of scope for your PR.

2023-05-08 06:08 UTC, AhmedTheGeek commented
@GMTA  Ah, thanks for explaining that. I changed my approach to have a better linearity as @konradekk hinted. So instead of changing the auto scroll threshold value, it now calculates the scroll delta based on how much further the cursor position is from the inner widget rect.

So the further you go out, the larger the scroll delta becomes. Here's a capture to better show the behavior.
 
[Screencast from 2023-05-08 09-02-19.webm](https://user-images.githubusercontent.com/1913834/236746916-5b9f6c02-d7c2-47ac-be89-e0e8dd542bc4.webm)

2023-05-08 07:31 UTC, GMTA commented
That looks supernice!

2023-05-08 07:35 UTC, GMTA commented on Userland/Libraries/LibGUI/AbstractScrollableWidget.h
> +    int m_autoscroll_threshold { 70 };
Please remove this commit and the subsequent revert commit from your PR; you only need the last commit

2023-05-08 07:45 UTC, GMTA requested changes

2023-05-08 07:45 UTC, GMTA commented on Userland/Libraries/LibGUI/AbstractScrollableWidget.cpp
> +        delta.set_y(clamp(-(m_autoscroll_threshold - pos.y()), -(m_autoscroll_threshold + autoscroll_threshold_offset), 0));
In `-(m_autoscroll_threshold + autoscroll_threshold_offset)`, `autoscroll_threshold_offset` is equivalent to `-pos.y()` so you can also write this as `-(m_autoscroll_threshold - pos.y())` which is the same as the first argument to `clamp()`. Effectively this argument does not limit anything, so your entire expression is equivalent to `AK::min(pos.y() - m_autoscroll_threshold, 0)`

So this becomes:
```cpp
delta.set_y(AK::min(pos.y() - m_autoscroll_threshold, 0));
```

2023-05-08 07:45 UTC, GMTA commented on Userland/Libraries/LibGUI/AbstractScrollableWidget.cpp
> +        autoscroll_threshold_offset = pos.y() - widget_inner_rect().height();
You're overwriting `autoscroll_threshold_offset` here. I suggest dropping the entire variable, you don't need it for the calculations.

2023-05-08 07:45 UTC, GMTA commented on Userland/Libraries/LibGUI/AbstractScrollableWidget.cpp
> +        delta.set_y(clamp(m_autoscroll_threshold - (widget_inner_rect().height() - pos.y()), 0, m_autoscroll_threshold + autoscroll_threshold_offset));
You can simplify this:
```cpp
delta.set_y(AK::max(pos.y() + m_autoscroll_threshold - widget_inner_rect().height(), 0));
```

2023-05-08 08:58 UTC, GMTA commented
Thanks @AhmedTheGeek, this works (and looks) really well now! And welcome to the project :^)

2023-05-08 08:58 UTC, GMTA approved these changes

2023-05-08 09:28 UTC, merged

2023-05-08 10:14 UTC, konradekk commented
note an easy win: do the same for x-axis. 😄