AK+Userland: Introduce custom error codes and start using them for Streams (cursed edition)
SerenityOS/serenity pull request #18940
Opened 2023-05-20 18:26 UTC by timschumi

The same idea as #18589, but combined with my horrible C++ skills.

The performance values look like they are reasonably within margin of error:

```
|                                                  | Before  | After   |
|--------------------------------------------------|---------|---------|
| `tar -tf llvm-project-15.0.3.src.tar.xz` (n=10)  | 26006ms | 26414ms |
| `/usr/Tests/LibCompress/TestXz` (n=1000)         | 48ms    | 44ms    |
| `test-js` (n=100)                                | 5628ms  | 5727ms  |
```

2023-05-24 16:33 UTC, kleinesfilmroellchen requested changes

2023-05-24 18:20 UTC, kleinesfilmroellchen approved these changes

2023-06-24 11:52 UTC, kleinesfilmroellchen approved these changes

2023-09-27 01:54 UTC, timschumi commented
Boop. I forgot what I was planning to do. Probably getting some more performance metrics.

2023-10-29 12:21 UTC, closed without merging