Userland: Replacing DeprecatedString [2048, Chess]
SerenityOS/serenity pull request #19032
Opened 2023-05-25 00:40 UTC by JRedrupp

Raising these migrations from DeprecatedString in order to assist with issue #17128 
No new Features added, purely a migration.

2023-05-25 06:16 UTC, caoimhebyrne requested changes
Commit title formatting is incorrect. See https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy

2023-05-25 18:54 UTC, JRedrupp commented
> Commit title formatting is incorrect. See https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy

Thanks for the feedback, have edited the messages to hopefully be inline! :)

2023-05-29 11:29 UTC, GMTA commented on Userland/Games/2048/BoardView.cpp
Commit message: `DeprecatedString` instead of `DepricatedString` (2x)

2023-05-29 11:29 UTC, GMTA commented on Userland/Games/Chess/ChessWidget.cpp
>      update();
Commit message: `depricated` should be `deprecated` (4x)

Also, you don't need to type "Summary:" before your commit description. Finally , please use your editor's word wrapping feature to automatically wrap lines after 72 characters.

2023-05-29 21:39 UTC, closed without merging