LibWeb: Implement CSS trigonometric functions
SerenityOS/serenity pull request #19165
Opened 2023-05-30 18:35 UTC by stelar7

https://drafts.csswg.org/css-values-4/#trig-funcs

2023-06-09 14:41 UTC, AtkinsSJ requested changes
A couple of things, most of which apply to each trig function.

2023-06-09 14:41 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
> +    virtual bool contains_percentage() const override { return false; };
As I've commented on some of the other PRs, this needs to check if the contained value has a percentage in it.

2023-06-09 14:41 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
> +    NonnullOwnPtr<CalculationNode> m_a;
`m_value`

2023-06-09 14:41 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
> +    NonnullOwnPtr<CalculationNode> m_a;
`m_value`

2023-06-09 14:41 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
> +    virtual bool contains_percentage() const override { return false; };
Same as before.

2023-06-09 14:41 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
> +    NonnullOwnPtr<CalculationNode> m_a;
`m_value`

2023-06-09 14:41 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
> +    virtual bool contains_percentage() const override { return false; };
Same as before.

2023-06-09 14:41 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
> +    NonnullOwnPtr<CalculationNode> m_a;
`m_value`

2023-06-09 14:41 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
> +    NonnullOwnPtr<CalculationNode> m_a;
`m_value`

2023-06-09 14:41 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
> +    virtual bool contains_percentage() const override { return false; };
Same as before.

2023-06-09 14:41 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
> +    NonnullOwnPtr<CalculationNode> m_b;
`m_a` -> `m_y`
`m_b` -> `m_x`

2023-06-10 15:21 UTC, stelar7 commented on Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
> +    };
Its needed, since without it that branch would resolve to a void value, and not double as the others.

2023-06-10 15:24 UTC, stelar7 commented on Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
> +ErrorOr<OwnPtr<CalculationNode>> Parser::parse_sin_function(Function const& function)
I could do a pass to turn everything into a generator, but id want do to it after theyve been merged in their current state

2023-06-15 11:28 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
> +    };
Ah ok. The alternative would be this then:
```c++
[](auto const&) -> double { VERIFY_NOT_REACHED(); });
```
But yeah it doesn't matter either way. :+1:

2023-06-15 14:41 UTC, AtkinsSJ commented
Dang it, I merged the constants one instead and gave this conflicts. :grimacing: Just one rebase to go hopefully.

2023-06-15 15:54 UTC, merged