LibArchive+zip: Add helper functions for adding members to a `ZipOutputStream`
SerenityOS/serenity pull request #19229
Opened 2023-06-02 16:57 UTC by caoimhebyrne

*This is a re-do of #18107.*

We now have helper functions in `ZipOutputStream` for adding files (via `AK::Stream`) to a zip. This should allow other applications to add files to a zip archive with ease (and not have to invoke `zip` when doing so).

The `zip` utility has been updated to use these new helpers.

2023-06-05 23:12 UTC, GMTA commented on Userland/Libraries/LibArchive/Zip.cpp
> +ErrorOr<double> ZipOutputStream::add_member_from_stream(StringView path, Stream& stream, Optional<Core::DateTime> optional_date)
Returning a `double` to represent the compression ratio seems like a pretty straightforward copy/paste from `zip`. But maybe a nicer API is to return a struct with some information about the added entry, including the compression ratio and compressed size?

Also, maybe a `double` is a bit overkill to represent a ratio that is usually displayed with low precision - a `float` will probably do as well.

2023-06-05 23:12 UTC, GMTA commented on Userland/Libraries/LibArchive/Zip.cpp
> +        compression_ratio = (double)deflate_buffer.value().size() / buffer.size();
`static_cast<double>` (or `float`)

2023-06-05 23:12 UTC, GMTA commented on Userland/Libraries/LibArchive/Zip.cpp
> +ErrorOr<void> ZipOutputStream::add_directory(StringView name, Optional<Core::DateTime> optional_date)
`optional_date` does not describe what the argument represents. I'd name it something like `modification_time`. Same goes for `::add_member_from_stream`.

2023-06-05 23:12 UTC, GMTA commented on Userland/Libraries/LibArchive/Zip.cpp
> +    auto compression_ratio = 0.0;
Since you only update this value if `deflate_buffer.value().size() < buffer.size()`, shouldn't the default be `1.f`? (i.e. no compression)

2023-06-05 23:12 UTC, GMTA commented on Userland/Utilities/zip.cpp
> +        if (compression_ratio > 0.0) {
I'd expect this expression to be `compression_ratio < 1.f` (see other comment on this)

2023-06-05 23:12 UTC, GMTA commented on Userland/Utilities/zip.cpp
>              outln("  adding: {} (stored 0%)", canonicalized_path);
This `0%` is weird - if you compress a file by 90%, you would see `(deflated 10%)`. So `0%` would mean no bytes were stored at all? I'd just leave out this percentage and just show `(stored)`.

2023-07-05 10:26 UTC, caoimhebyrne commented
Oopsies, completely forgot about this! I'll hopefully get around to this after work this evening :)

2023-07-06 13:52 UTC, linusg requested changes

2023-07-06 13:52 UTC, linusg commented on Userland/Libraries/LibArchive/Zip.cpp
> +ErrorOr<ZipOutputStream::MemberInformation> ZipOutputStream::add_member_from_stream(StringView path, Stream& stream, Optional<Core::DateTime> modification_time)
pass `modification_time` by const ref

2023-07-06 13:52 UTC, linusg commented on Userland/Libraries/LibArchive/Zip.cpp
> +        auto date = modification_time.value();
`auto const& date`, but I'd just use `modification_time->foo()` below - `date.second()` makes no sense.

2023-07-06 13:52 UTC, linusg commented on Userland/Libraries/LibArchive/Zip.cpp
> +ErrorOr<void> ZipOutputStream::add_directory(StringView name, Optional<Core::DateTime> modification_time)
Same comments for `modification_time` here

2023-07-08 11:42 UTC, linusg approved these changes

2023-07-08 12:14 UTC, merged