Ladybird: Add copy action to JS Console output
SerenityOS/serenity pull request #19420
Opened 2023-06-16 13:43 UTC by ArmindoFlores

This adds the ability to use CTRL+C to copy text from the JS Console output, while previously it was only possible to do so from the text input widget.

2023-06-16 14:03 UTC, AtkinsSJ requested changes
One nit-pick but this looks good otherwise. Thanks!

2023-06-16 14:03 UTC, AtkinsSJ commented on Ladybird/ConsoleWidget.cpp
> +    copy_selected_text_action->setShortcut(QKeySequence(Qt::CTRL | Qt::Key_C));
Qt isn't my thing, but I know I've seen `StandardKey` used in a few places for standard keyboard shortcuts:

```suggestion
    copy_selected_text_action->setShortcut(QKeySequence::keyBindings(QKeySequence::StandardKey::Copy));
```

2023-06-18 18:32 UTC, awesomekling commented
This feels like a behavior that should be part of `WebContentView` instead of something that everyone who embeds `WebContentView` has to do manually :)

2023-06-21 11:09 UTC, trflynn89 commented
So `BrowserWindow::copy_selected_text` already tries to copy the text from the console widget:
https://github.com/SerenityOS/serenity/blob/9c568282dc003ccf94a1fcbe58f93ed5e44acaa7/Ladybird/BrowserWindow.cpp#L638-L639

When I added that, I was working on a mac, where copying from the console widget still works - guess it didn't work on Linux.

But it any case, that action is installed on the BrowserWindow itself and on the Tab's context menu. So this new action in WebContentView conflicts with that action, and Qt gives this error message on the console when I hit ctrl+c:
```
QAction::event: Ambiguous shortcut overload: Ctrl+C
```

I think having the action on the WebContentView makes sense though, so this patch will need to remove creating a copy action in BrowserWindow, and make BrowserWindow and Tab use the action from WebContentView.

2023-06-21 20:33 UTC, ArmindoFlores commented
> 

I can do that, however I won't be able to test it on any other system besides Linux.

2023-06-22 01:53 UTC, trflynn89 commented
> I can do that, however I won't be able to test it on any other system besides Linux.

No problem, I'm happy to test on macOS for ya

2023-07-20 05:15 UTC, closed without merging