Main: Add Wiby Search Engine
SerenityOS/serenity pull request #19732
Opened 2023-07-01 17:11 UTC by kimkulak

Wiby is a search engine for older style pages, lightweight and based on a subject of interest. Building a web more reminiscent of the early internet.

2023-07-01 17:22 UTC, circl-lastname commented
`Main:` should be `Base:` and the merge commit shouldn't be there, rebase onto the branch instead

2023-07-01 20:10 UTC, kimkulak commented
> `Main:` should be `Base:` and the merge commit shouldn't be there, rebase onto the branch instead

Fixed :^)

2023-07-01 21:10 UTC, linusg requested changes

2023-07-01 21:10 UTC, linusg commented on Base/home/anon/.config/SearchEngines.json
> +        "url_format": "http://wiby.me/?q={}"
```suggestion
        "url_format": "https://wiby.me/?q={}"
```

2023-07-01 21:11 UTC, linusg reviewed
> Fixed :^)

Still says `Main:`.

2023-07-01 21:33 UTC, kimkulak commented
> > Fixed :^)
> 
> Still says `Main:`.

I fixed it a couple of hour ago but managed to somehow both reverse the change and requested a review from you.
At least after this snafu things should work fine... right?

:^)

2023-07-01 21:37 UTC, linusg commented on Base/home/anon/.config/SearchEngines.json
> +        "url_format": "http://wiby.me/?q={}"
This is not resolved

2023-07-01 21:45 UTC, linusg commented
Please squash the fixup commit as per https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy

2023-07-01 21:51 UTC, kimkulak commented
> Please squash the fixup commit as per https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy

This sounds easy enough :^)

2023-07-01 21:57 UTC, linusg commented
Now it's saying `Update:` and some nonsensical commit message - please sort this out locally and carefully check before force pushing and requesting a review again.

2023-07-01 22:21 UTC, closed without merging

2023-07-02 13:36 UTC, circl-lastname commented
Guess they deleted the entire account and will try again? 🤔

2023-07-02 13:38 UTC, linusg commented
Welp, that escalated quickly. They did try again, and I merged it: https://github.com/SerenityOS/serenity/pull/19737