Ports: Add elfutils (and a bunch of other dependencies...)
SerenityOS/serenity pull request #19763
Opened 2023-07-02 20:00 UTC by supercomputer7

Relies on #19728.

2023-07-07 09:57 UTC, supercomputer7 commented
@timschumi Now here's the real deal - I've got this to work, but it is really clunky (some utilities need more testing) - we can't compile all of them so 5 of them are disabled for now. It seems like GNU binutils give us pretty much all we need, except for the DWARF code, so I'll give you the decision on whether to close this or continue working on this.

Either way, it was the hardest port I've ever pulled and managed to get into a working state, but it was quite fun too :)

2023-07-07 13:39 UTC, ADKaster commented on Ports/nnn/patches/0003-Disable-broken-features.patch
> ++O_NOX11 := 1  # disable X11 integration
surely we can set these with configopts or by passing an argument to `make`? `make NO_X11=1` or some such?

2023-07-07 13:39 UTC, ADKaster commented on Userland/Libraries/LibC/crt0.cpp
> +    program_invocation_short_name = argv[0];
This is not the same as argv[0]. 

https://man7.org/linux/man-pages/man3/program_invocation_name.3.html

It also belongs in `errno.h`, not in `stdio.h`

>  program_invocation_short_name contains the basename component of name that was used to invoke the calling program.  That is, it is the same value as program_invocation_name, with all text up to and including the final slash (/), if any, removed.

2023-07-09 16:24 UTC, timschumi commented on Ports/argp-standalone/package.sh
> +    run cmake "${configopts[@]}" .
No, configopts is empty by default. CMake-based ports need to add `CMAKE_TOOLCHAIN_FILE` manually.

\*Adds one to the tally mark for "remove configopts entirely"\*

2023-07-09 16:45 UTC, timschumi requested changes

2023-07-09 16:45 UTC, timschumi commented on Userland/Libraries/LibC/stdio.cpp
> +int putc_unlocked(int ch, FILE* stream)
This actually does have a POSIX manpage.

2023-07-09 16:45 UTC, timschumi commented on Userland/Libraries/LibC/err.h
> +     __attribute__ ((noreturn, __format__ (__printf__, 2, 0)));
Where is this copied from? Both the argument naming as well as the general formatting don't match what we usually use. :yakthonk:

2023-07-09 16:45 UTC, timschumi commented on Ports/argp-standalone/package.sh
> +files="https://github.com/tom42/argp-standalone/archive/refs/tags/v1.0.2.zip argp.zip 75b624a5e9e89d5e7527400a36c9b434e3f7eeaf3e8c19baf018ea4be3e250f9"
This could use `${version}`.

2023-07-09 16:45 UTC, timschumi commented on Ports/elfutils/package.sh
> +depends=('zlib' 'libfts' 'argp-standalone' 'musl-obstack' 'curl' 'libarchive' 'sqlite' 'gettext')
As usual, one line for each (and sorted).

2023-07-09 16:45 UTC, timschumi commented on Userland/Libraries/LibC/ar.h
> +   This file is part of the GNU C Library.
Just to note that down somewhere, writing our own version of ar.h should be trivial if the contents are not protectable (and if they are, doing something like this is out of the question anyways).

2023-07-09 16:45 UTC, timschumi commented on Userland/Libraries/LibC/stdio_locking_ext.h
> +#define FSETLOCKING_BYCALLER	FSETLOCKING_BYCALLER
Judging by the manpage on die.net, all of this should be in the normal `stdio_ext.h` file.

2023-07-09 16:45 UTC, timschumi commented on Ports/elfutils/package.sh
> +    run autoreconf
The tarball arrives preconfigured, so we should just patch the existing `configure` file. Everything else risks many more compatibility issues.

2023-09-11 01:47 UTC, closed without merging