Base: Render checksum man page synopsis using a multi-line code block
SerenityOS/serenity pull request #19830
Opened 2023-07-06 05:17 UTC by tcl3

This is consistent with other man pages and makes the synopsis render correctly in the terminal.

This doesn't fix the underlying rendering issue detailed in #19534. I've included an explanation of what I believe the underlying problem to be on that issue.

Before:
![checksum_rendering_before](https://github.com/SerenityOS/serenity/assets/2817754/5bba2bfb-434d-4dd7-8e61-d856c488fe70)

After:
![checksum_rendering_after](https://github.com/SerenityOS/serenity/assets/2817754/3ff55a84-3286-4ff1-bf03-2658a5607bf5)

2023-07-06 06:48 UTC, tcl3 commented
My latest push updates the PR to ensure that code blocks of the form
````
```**foo
This should be bold
``` 
````
are displayed with a bold font in the terminal. I didn't include any special behavior for italic styling, as our terminal doesn't currently support displaying italic text.

I also corrected a logic error in the HTML rendering of multi-line code blocks so that code blocks of the the following form are rendered correctly:
````
```*foo
This should be italic
``` 
````

and

````
```_foo
This should also be italic
``` 
````

2023-07-06 13:31 UTC, linusg requested changes

2023-08-04 05:42 UTC, tcl3 commented on Userland/Libraries/LibMarkdown/CodeBlock.cpp
> +    else if (m_style.length() == 1)
> Shouldn't `_**foo**_` (_**foo**_) be rendered as bold _and_ italic?

Yes, it should. This change only applies to our non-standard code-block-with-style extension I'm not sure it makes sense to change this without inline styles working correctly. I've reverted the PR to its original state, which only changes the format of the man page. I can open a separate PR for markdown formatting improvements.

2023-08-04 05:46 UTC, tcl3 commented
My latest push reverts this PR to its original form, which just modifies the formatting of the `checksum` man page. More work is needed to support styles correctly, which I can open a separate PR for.

2023-08-15 23:04 UTC, gmta approved these changes

2023-08-15 23:04 UTC, merged