LibDiff+patch: Add support for --strip, --directory, and add some tests
SerenityOS/serenity pull request #20007
Opened 2023-07-14 00:18 UTC by shannonbooth

Draft sitting on top of: https://github.com/SerenityOS/serenity/pull/19994

2023-07-19 07:16 UTC, shannonbooth commented
Thanks!

2023-07-29 13:28 UTC, AtkinsSJ requested changes
Code seems fine, just a couple of confusing sentences.

2023-07-29 13:28 UTC, AtkinsSJ commented on Userland/Utilities/patch.cpp
> +    args_parser.add_option(directory, "Change to the working directory to <directory> before applying the patch file", "directory", 'd', "directory");
Should this be "Change the working directory to..."?

2023-07-29 13:28 UTC, AtkinsSJ commented on Userland/Utilities/patch.cpp
> +    args_parser.add_option(strip_count, "Strip given of leading path components from file names (defaults as basename)", "strip", 'p', "count");
Should this be "String given number of..."?

2023-07-29 22:26 UTC, shannonbooth commented
pushed rebase now CI fix is merged in

2023-07-29 23:03 UTC, ADKaster approved these changes

2023-07-29 23:09 UTC, merged