LibWeb: Add basic MathML support
SerenityOS/serenity pull request #20269
Opened 2023-07-30 22:50 UTC by Epigenetic

We now can parse and generate MathML elements using the [MathML Core](https://w3c.github.io/mathml-core/#the-mathvariant-attribute) standard. We don't have any of the MathML CSS extensions yet though, so it looks a bit wonky most of the time.

2023-07-31 11:46 UTC, AtkinsSJ requested changes
Just nit picks really.

2023-07-31 11:46 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp
> +    TRY(MathML::TagNames::initialize_strings());
This list is alphabetical. :redlinus:

2023-07-31 11:46 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/DOM/ElementFactory.cpp
> +    auto const& local_name = FlyString::from_deprecated_fly_string(qualified_name.local_name()).release_value_but_fixme_should_propagate_errors();
You can propagate this error with `TRY_OR_THROW_OOM(realm.vm(), ...)`

2023-07-31 11:46 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/DOM/ElementFactory.cpp
> +    if (local_name == MathML::TagNames::annotation
Nit-pick: `local_name.is_one_of(...)` might be a little less verbose, but it's no big deal, so feel free to ignore this.

2023-08-09 11:19 UTC, AtkinsSJ commented
This needs some fixing up because of the recent error-propagation changes, but seems good otherwise.

2023-08-09 21:38 UTC, Epigenetic commented
> This needs some fixing up because of the recent error-propagation changes, but seems good otherwise.

The error prorogation changes should be all cleaned up now.

2023-08-10 20:05 UTC, AtkinsSJ commented
`Tests/LibWeb/Layout/input/css-namespace-tag-name-selector.html` also needs rebaselining, because your changes actually give the `<math>` element some style properties.

2023-08-11 10:02 UTC, AtkinsSJ commented
This is getting ridiculous, but this now has conflicts because of a cmake change. 😆

2023-08-11 22:57 UTC, Epigenetic commented
> This is getting ridiculous, but this now has conflicts because of a cmake change. 😆

Alright that's cleaned up now. Fingers crossed that nothing else breaks before the CI finishes running but with the luck this PR has had... well nothing would surprise me.

2023-08-12 06:59 UTC, merged

2023-08-12 06:59 UTC, AtkinsSJ commented
Against all the odds, it's merged! 🎉