LibWeb: Convert to pixels inside calculate_{min, max}_content_height
SerenityOS/serenity pull request #20541
Opened 2023-08-13 04:50 UTC by axgallo

Avoids losing max-content lengths due to unchecked conversion to pixels.

2023-08-13 10:48 UTC, kalenikaliaksandr requested changes
Changing `calculate_min_content_height()` and `calculate_max_content_height()` to accept CSSPixels instead of AvailableSize in https://github.com/SerenityOS/serenity/commit/e25b1f76e12965ef578de1f878078b8f783bd39e was on purpose. If some layout calculations currently rely on passing `max-content` width to produce valid results then they need to be rearranged in the way when they don't.

2023-08-13 11:19 UTC, axgallo commented
I see where you're coming from. However, we're deliberately injecting the `max-content` [here](https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibWeb/Layout/FormattingContext.cpp#L1344), via `InlineFormattingContext::dimension_box_on_line` and `FormattingContext::calculate_shrink_to_fit_widths` route, which looks to me like the right thing to do. Moreover, when we dimension the cells there has to be a way to know that they can take as much horizontal space as they need and thus not wrap for their outer max width.

It's unclear to me what other means do we have to communicate that to `TableFormattingContext`, except for a width constraint. We don't have any definite size to communicate since the table in question has an `auto` width. What would be your suggested approach here?

2023-08-13 11:24 UTC, kalenikaliaksandr commented
> It's unclear to me what other means do we have to communicate that to TableFormattingContext, except for a width constraint. We don't have any definite size to communicate since the table in question has an auto width. What would be your suggested approach here?

can we call `calculate_min_content_height()` and `calculate_max_content_height()` only once used width is known for a cell. it should be possible to find cell width without measuring cell height, right?

2023-08-13 11:33 UTC, axgallo commented
> > It's unclear to me what other means do we have to communicate that to TableFormattingContext, except for a width constraint. We don't have any definite size to communicate since the table in question has an auto width. What would be your suggested approach here?
> 
> can we call `calculate_min_content_height()` and `calculate_max_content_height()` only once used width is known for a cell. it should be possible to find cell width without measuring cell height, right?

The causality is reversed. We need a tentative width before coming up with the two height proposals and I don't think there's a way around that due to text wrapping being an option the layout algorithm can take.

2023-08-13 11:35 UTC, kalenikaliaksandr commented
> The causality is reversed. We need a tentative width before coming up with the two height proposals and I don't think there's a way around that due to text wrapping being an option the layout algorithm can take. By informing the cell that the constraint is max-content, we take wrapping off the table.

can we delay calculating height proposals until finite cell width is calculated?

2023-08-13 11:52 UTC, axgallo commented
> > The causality is reversed. We need a tentative width before coming up with the two height proposals and I don't think there's a way around that due to text wrapping being an option the layout algorithm can take. By informing the cell that the constraint is max-content, we take wrapping off the table.
> 
> can we delay calculating height proposals until finite cell width is calculated?

Are you saying that the (overall) available space should have no say in the cell measure computation? We would then compute the minimum height based on the calculated maximum width and the maximum height based on the calculated minimum width for the cells. I could buy that and I couldn't find definitive evidence in the standard for or against it. It feels a bit counter-intuitive, but not wrong.

2023-08-13 11:56 UTC, kalenikaliaksandr commented
> Are you saying that the (overall) available space should have no say in the cell measure computation?

available space of table container should not affect height proposals calculation for table cells, yes.

> We would then compute the minimum height based on the calculated maximum width and the maximum height based on the calculated minimum width for the cells.

making it work this way would make much more sense compared to how it is now.

2023-08-13 12:16 UTC, axgallo commented
I like the idea of not checking the available space of the table container in cell measures too. It shouldn't have any impact on impossible proposed space anyway, we'd just end up with `min-content` sized cells in that case anyway. I'm more worried about the rest of the cases (achievable, defined proposed width for the table container), not sure the remaining steps of the algorithm would make up for it. Let me think about it a bit more, hopefully my concerns are misplaced.

2023-08-13 15:57 UTC, kalenikaliaksandr commented
@axgallo you can also try to reason about why `available_space` of table container is currently used to measure heights of table cells and I hope you realise it doesn't make any sense. I see how `available_space` calculated individually for specific cell might make sense but, again, that means that width of a cell needs to be known before starting bothering about heights.

2023-08-14 07:19 UTC, axgallo commented
Ok, I'm pretty confident at this point we don't need the available size from the table container and updated the PR.

However, `calculate_max_content_width` returns a smaller width than we need when we have trailing whitespaces. We [trim](https://github.com/SerenityOS/serenity/blob/43b4e84d9c6f8a907c4b18d01086368c667f9ad2/Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp#L319) them when we generate line boxes, therefore when we call `calculate_min_content_height` with the max-width computed as such we could get additional line breaks and an inaccurate height. An input which proves the problem is:

```
<style>
	table {
		border-collapse: collapse
	}

	td {
		border: 1px solid black;
	}
</style>

<table>
	<tbody>
		<tr>
			<td style="width: 30%;">A
			</td>
			<td style="width: 40%;">
				B
				<br>C
			</td>
			<td style="width: 30%;">
				D
			</td>
		</tr>
	</tbody>
</table>
```

One way to fix this would be to compute the width and height at once (two computations in total: one for minimum content width, one for maximum content width), but I'd like to hear if there are better options before committing to it.

2023-08-14 09:06 UTC, kalenikaliaksandr approved these changes

2023-08-14 11:14 UTC, merged