Flood: Modernization
SerenityOS/serenity pull request #20552
Opened 2023-08-13 12:32 UTC by implicitfield

- Flood: Propagate errors when creating SettingsDialog
- Flood: Use the new GML compiler
- Flood: Replace usage of DeprecatedString

Contributes to #17128 and #20518.

2023-08-15 21:04 UTC, kleinesfilmroellchen requested changes
Only checked the GML compiler porting due to time constraints, but looks almost good

2023-08-15 21:04 UTC, kleinesfilmroellchen commented on Userland/Games/Flood/MainWidget.h
> +    C_OBJECT(MainWidget)
This can be C_OBJECT_ABSTRACT, since the auto-generated constructor functions shouldn't be used.

2023-08-15 21:04 UTC, kleinesfilmroellchen commented on Userland/Games/Flood/SettingsWidget.h
> +    C_OBJECT(SettingsWidget)
Same here

2023-08-18 15:26 UTC, kleinesfilmroellchen requested changes

2023-08-18 15:26 UTC, kleinesfilmroellchen commented on Userland/Games/Flood/SettingsDialog.h
> +    explicit SettingsDialog(NonnullRefPtr<GUI::Widget> settings_widget, GUI::Window* parent, size_t board_rows, size_t board_columns);
Doesn't have to be explicit since there's more than one argument

2023-08-18 15:26 UTC, kleinesfilmroellchen commented on Userland/Games/Flood/MainWidget.h
> +    MainWidget() = default;
The constructor shouldn't be public, only the try_create.

2023-08-18 15:26 UTC, kleinesfilmroellchen commented on Userland/Games/Flood/SettingsWidget.h
> +    SettingsWidget() = default;
Same here: not public

2023-08-21 11:25 UTC, kleinesfilmroellchen approved these changes

2023-08-23 11:28 UTC, timschumi approved these changes

2023-08-23 11:28 UTC, merged