Ports: Don't set `EDITOR` to empty string if it is not set
SerenityOS/serenity pull request #20636
Opened 2023-08-18 09:49 UTC by fdellwing

CC @timschumi

2023-08-18 09:56 UTC, timschumi requested changes
That's not what I imagined what you meant when saying that it leads to a lot of code duplication. :^)

Couldn't we do something like this:

```sh
environment_variables=(
    "SERENITY_STRIPPED_ENV=1"
    "HOME=${HOME}"
    "USER=${USER}"
    "TERM=${TERM}"
    "PATH=${PATH}"
)

# Repeat for all the other options that might be optional.
# Note: -n doesn't mean unset.
if [ -n "${EDITOR}" ]; then
    environment_variables+=("EDITOR=${EDITOR}")
fi

exec env -i "${environment_variables[@]}" "${@}"
```

2023-08-18 12:36 UTC, gmta commented
You can factor out the code duplication and check if the variable is actually set by using something like:

```bash
keep_environment_variables=(
    'EDITOR'
    'IN_SERENITY_PORT_DEV'
    'MAKEJOBS'
    'SERENITY_ARCH'
    'SERENITY_TOOLCHAIN'
)

for environment_variable_name in "${keep_environment_variables[@]}"; do
    if [ -v "${environment_variable_name}" ]; then
        environment_variables+=("${environment_variable_name}=${!environment_variable_name}")
    fi
done
```

2023-08-18 20:26 UTC, timschumi requested changes
One last small nitpick.

2023-08-18 20:26 UTC, timschumi commented on Ports/.strip_env.sh
> +)
While we are touching this anyways...

```suggestion
environment_variables=(
    "HOME=${HOME}"
    "PATH=${PATH}"
    "SERENITY_STRIPPED_ENV=1"
    "TERM=${TERM}"
    "USER=${USER}"
)
```

2023-08-19 13:48 UTC, timschumi approved these changes

2023-08-19 13:48 UTC, merged