Base: Add more emoji
SerenityOS/serenity pull request #20684
Opened 2023-08-20 16:20 UTC by segfaultdev

I have seen that most people-related emojis were not done, so I did them! As all commits do the same thing, just adding different emojis, here is a complete list of the added ones instead:

👨 - U+1F468 MAN
👨‍💻 - U+1F468 U+200D U+1F4BB MAN TECHNOLOGIST
👨‍💼 - U+1F468 U+200D U+1F4BC MAN OFFICE WORKER
👨‍🔧 - U+1F468 U+200D U+1F527 MAN MECHANIC
👨‍🔬 - U+1F468 U+200D U+1F52C MAN SCIENTIST
👨‍🚀 - U+1F468 U+200D U+1F680 MAN ASTRONAUT
👨‍🚒 - U+1F468 U+200D U+1F692 MAN FIREFIGHTER
👨‍🦰 - U+1F468 U+200D U+1F9B0 MAN RED HAIR
👨‍🦱 - U+1F468 U+200D U+1F9B1 MAN CURLY HAIR
👨‍🦲 - U+1F468 U+200D U+1F9B2 MAN BALD
👨‍🦳 - U+1F468 U+200D U+1F9B3 MAN WHITE HAIR
👨‍⚕️ - U+1F468 U+200D U+2695 U+FE0F MAN HEALTH WORKER
👨‍⚖️ - U+1F468 U+200D U+2696 U+FE0F MAN JUDGE
👩 - U+1F469 WOMAN
👩‍💻 - U+1F469 U+200D U+1F4BB WOMAN TECHNOLOGIST
👩‍💼 - U+1F469 U+200D U+1F4BC WOMAN OFFICE WORKER
👩‍🔧 - U+1F469 U+200D U+1F527 WOMAN MECHANIC
👩‍🔬 - U+1F469 U+200D U+1F52C WOMAN SCIENTIST
👩‍🚀 - U+1F469 U+200D U+1F680 WOMAN ASTRONAUT
👩‍🚒 - U+1F469 U+200D U+1F692 WOMAN FIREFIGHTER
👩‍🦰 - U+1F469 U+200D U+1F9B0 WOMAN RED HAIR
👩‍🦱 - U+1F469 U+200D U+1F9B1 WOMAN CURLY HAIR
👩‍🦲 - U+1F469 U+200D U+1F9B2 WOMAN BALD
👩‍🦳 - U+1F469 U+200D U+1F9B3 WOMAN WHITE HAIR
👩‍⚕️ - U+1F469 U+200D U+2695 U+FE0F WOMAN HEALTH WORKER
👩‍⚖️ - U+1F469 U+200D U+2696 U+FE0F WOMAN JUDGE
👱 - U+1F471 PERSON BLOND HAIR
👱‍♀️ - U+1F471 U+200D U+2640 U+FE0F WOMAN BLOND HAIR
👱‍♂️ - U+1F471 U+200D U+2642 U+FE0F MAN BLOND HAIR
👳 - U+1F473 PERSON WEARING TURBAN
👳‍♀️ - U+1F473 U+200D U+2640 U+FE0F WOMAN WEARING TURBAN
👳‍♂️ - U+1F473 U+200D U+2642 U+FE0F MAN WEARING TURBAN
💁 - U+1F481 PERSON TIPPING HAND
💁‍♀️ - U+1F481 U+200D U+2640 U+FE0F WOMAN TIPPING HAND
💁‍♂️ - U+1F481 U+200D U+2642 U+FE0F MAN TIPPING HAND
💆 - U+1F486 PERSON GETTING MASSAGE
💆‍♀️ - U+1F486 U+200D U+2640 U+FE0F WOMAN GETTING MASSAGE
💆‍♂️ - U+1F486 U+200D U+2642 U+FE0F MAN GETTING MASSAGE
💇 - U+1F487 PERSON GETTING HAIRCUT
💇‍♀️ - U+1F487 U+200D U+2640 U+FE0F WOMAN GETTING HAIRCUT
💇‍♂️ - U+1F487 U+200D U+2642 U+FE0F MAN GETTING HAIRCUT
🙅 - U+1F645 PERSON GESTURING NO
🙅‍♀️ - U+1F645 U+200D U+2640 U+FE0F WOMAN GESTURING NO
🙅‍♂️ - U+1F645 U+200D U+2642 U+FE0F MAN GESTURING NO
🙆 - U+1F646 PERSON GESTURING OK
🙆‍♀️ - U+1F646 U+200D U+2640 U+FE0F WOMAN GESTURING OK
🙆‍♂️ - U+1F646 U+200D U+2642 U+FE0F MAN GESTURING OK
🙇 - U+1F647 PERSON BOWING
🙇‍♀️ - U+1F647 U+200D U+2640 U+FE0F WOMAN BOWING
🙇‍♂️ - U+1F647 U+200D U+2642 U+FE0F MAN BOWING
🙋 - U+1F64B PERSON RAISING HAND
🙋‍♀️ - U+1F64B U+200D U+2640 U+FE0F WOMAN RAISING HAND
🙋‍♂️ - U+1F64B U+200D U+2642 U+FE0F MAN RAISING HAND
🧑 - U+1F9D1 PERSON
🧑‍💻 - U+1F9D1 U+200D U+1F4BB TECHNOLOGIST
🧑‍💼 - U+1F9D1 U+200D U+1F4BC OFFICE WORKER
🧑‍🔧 - U+1F9D1 U+200D U+1F527 MECHANIC
🧑‍🔬 - U+1F9D1 U+200D U+1F52C SCIENTIST
🧑‍🚀 - U+1F9D1 U+200D U+1F680 ASTRONAUT
🧑‍🦰 - U+1F9D1 U+200D U+1F9B0 PERSON RED HAIR
🧑‍🦱 - U+1F9D1 U+200D U+1F9B1 PERSON CURLY HAIR
🧑‍🦲 - U+1F9D1 U+200D U+1F9B2 PERSON BALD
🧑‍🦳 - U+1F9D1 U+200D U+1F9B3 PERSON WHITE HAIR
🧑‍⚕️ - U+1F9D1 U+200D U+2695 U+FE0F HEALTH WORKER
🧑‍⚖️ - U+1F9D1 U+200D U+2696 U+FE0F JUDGE

2023-08-20 16:24 UTC, segfaultdev commented
Shoot, did not know U+FE0F was not meant to be in the filenames...

2023-08-20 20:48 UTC, Xexxa commented
This is not a review(have to take a closer look while at the computer).

A couple of issues, commits containing corrections of other commits on the same PR should be squashed.

The list of "emoji - codepoint(d) name" has by tradition also been added to the commit messages. Not 100% sure what the rationale was for that, I can have a look to see if I can find any relevant discussion.

2023-08-21 00:10 UTC, segfaultdev commented
> This is not a review(have to take a closer look while at the computer).
> 
> A couple of issues, commits containing corrections of other commits on the same PR should be squashed.
> 
> The list of "emoji - codepoint(d) name" has by tradition also been added to the commit messages. Not 100% sure what the rationale was for that, I can have a look to see if I can find any relevant discussion.

I'm sorry, this was my first emoji PR here, but I managed to fix all that (I hope) after rebasing a bit (;

2023-08-21 05:35 UTC, Xexxa requested changes
Just to keep this PR updated on what's going on; I have requested changes in https://discord.com/channels/830522505605283862/927893781968191508/1142982013549297735, there is a few required and a few optional changes that I asked the author to do, mainly around reusing colours in clothes and hair. I'll do a complete review when this PR is updated. :-)

Overall this is already a great addition to our emoji and with some fine tuning it will be even better!

2023-08-23 11:12 UTC, AtkinsSJ commented
This has conflicts.

2023-08-24 05:26 UTC, Xexxa requested changes
Nice going changing the colours (https://github.com/SerenityOS/serenity/pull/20684#pullrequestreview-1586217897)

Just a few minor issues left:
I can't really see how "🧍‍♂️ - U+1F9CD U+200D U+2642 MAN STANDING" was updated? It seems to have the exact same colour as the earlier emoji, just a bit larger in size?

I think you can remove the left/right padding from the following emoji(if you don't have a good reason to keep it there):
👨‍🦲 - U+1F468 U+200D U+1F9B2 MAN: BALD
👩‍🦲 - U+1F469 U+200D U+1F9B2 WOMAN: BALD
🧑‍🦲 - U+1F9D1 U+200D U+1F9B2 PERSON: BALD

The conflicts are probably from https://github.com/SerenityOS/serenity/pull/20608, you could do some git ninja stuff(rebase? idk) or remove the following emoji from your PR to solve the conflict. 

🧑‍🔧 - U+1F9D1 U+200D U+1F527 MECHANIC
🧑‍🚀 - U+1F9D1 U+200D U+1F680 ASTRONAUT

2023-09-14 07:07 UTC, AtkinsSJ commented
Do you need help with fixing the conflicts?

2023-10-14 05:13 UTC, closed without merging