LibWeb: Slottables, slots, slot assignments, shadow trees, and finally: `<details>`
SerenityOS/serenity pull request #20965
Opened 2023-09-05 19:35 UTC by trflynn89

This implements the slot and slottable concepts from the DOM specs for use within the `<details>` element's shadow tree. These concepts are pretty beefy, but I've tried to break the implementation into understandable chunks.

https://github.com/SerenityOS/serenity/assets/5600524/4a02f75b-366c-411a-9af5-cd732d705572

This also makes `console.group` work as intended in the JS console (though we can certainly circle back and style this a bit better):

https://github.com/SerenityOS/serenity/assets/5600524/d2f99866-e536-493e-acb8-c290a4a16ce3

2023-09-06 05:29 UTC, shannonbooth commented on Userland/Libraries/LibWeb/HTML/ToggleEvent.idl
> +[Exposed=Window, UseNewAKString]
Can remove UseNewAKString

2023-09-06 05:30 UTC, shannonbooth commented
Nice on removing the `virtual` in `set_attribute` etc, that was in my git stash :P

2023-09-06 08:26 UTC, Lubrsi requested changes
Had a quick skim and noticed a couple issues, will have a closer look later :^)

2023-09-06 08:26 UTC, Lubrsi commented on Userland/Libraries/LibWeb/DOM/Slottable.cpp
> +        shadow->for_each_child_of_type<HTML::HTMLSlotElement>([&](auto& child) {
"descendants" here means the entire subtree
https://dom.spec.whatwg.org/#concept-tree-descendant

```suggestion
        shadow->for_each_in_subtree_of_type<HTML::HTMLSlotElement>([&](auto& child) {
```

2023-09-06 08:26 UTC, Lubrsi commented on Userland/Libraries/LibWeb/DOM/Slottable.cpp
> +    shadow->for_each_child_of_type<HTML::HTMLSlotElement>([&](auto& child) {
Ditto

2023-09-07 17:49 UTC, Lubrsi commented on Userland/Libraries/LibWeb/DOM/EventDispatcher.cpp
> +                if (is<Node>(*parent)) {
This is always true, given the assert on step 1.

2023-09-13 11:45 UTC, merged