LibWeb: Allow block level boxes to be floated and have clearance
SerenityOS/serenity pull request #21033
Opened 2023-09-11 18:49 UTC by kalenikaliaksandr

Before, we completely ignored clearance for block-level boxes if they were floated. This was incorrect because it is valid for a block-level box to be floated and still have clearance. However, unlike clearance on normal flow boxes, clearance on floating boxes does not affect the y-position of subsequent normal flow boxes. Instead, it pushes the box's position to the very beginning of an edge.

2023-09-11 18:54 UTC, awesomekling requested changes
Missing "Fixes #21023" :^)

2023-09-11 18:54 UTC, awesomekling commented on Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
>                  // One of two things happened:
One of *three* things happened :sweat_smile:

2023-09-11 19:20 UTC, kalenikaliaksandr commented
> Missing "Fixes https://github.com/SerenityOS/serenity/issues/21023" :^)

Actually, there are more issues to fix for reduction in #21023 😅

2023-09-11 19:34 UTC, awesomekling commented
> > Missing "Fixes #21023" :^)
> 
> Actually, there are more issues to fix for reduction in #21023 😅

Sure, then maybe just "Work towards #21023" is nice. So we can see where the test case originally came from :)

2023-09-11 19:36 UTC, kalenikaliaksandr commented
> Sure, then maybe just "Work towards https://github.com/SerenityOS/serenity/issues/21023" is nice. So we can see where the test case originally came from :)

yes, sure, I added this in the commit description.

2023-09-12 10:11 UTC, awesomekling commented
Sure okay :)

2023-09-12 10:11 UTC, merged