Minesweeper: port to GML compilation
SerenityOS/serenity pull request #21230
Opened 2023-09-25 17:49 UTC by tetektoza

This patch ports minesweeper to GML compilation, and introduces a few changes made to associated files. It contributes to https://github.com/SerenityOS/serenity/issues/20518

2023-10-01 12:40 UTC, gmta commented
Hi @tetektoza, welcome!

Could you please split up your commits so they individually contribute to either LibGUI or Minesweeper? Check [CONTRIBUTING.md](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy)'s bullet on atomic commits.

2023-10-01 12:49 UTC, tetektoza commented
Hi @gmta,

> Could you please split up your commits

Sure thing, should I also split up changes made to GMLCompiler (main.cpp file) to a separate commit? So that would be 3 separate commits.

2023-10-01 12:53 UTC, gmta commented
> should I also split up changes made to GMLCompiler (main.cpp file) to a separate commit? So that would be 3 separate commits.

Sounds sensible! Improvements to the GMLCompiler are separate from the Minesweeper changes imo.

2023-10-01 18:59 UTC, tetektoza commented
@gmta I think it should be fine now, you can check it out. All 3 commits are needed for the port to work, since some of the parameters specified in the .gml file weren't able to be converted implicitly. I need to split up my 2nd PR the same way but that will probably happen tomorrow.

2023-10-02 19:33 UTC, gmta commented
@tetektoza The order of your commits is not right; you should first commit the changes to LibGUI so the next commit can use that feature. As it stands now, compilation fails for the first commit.

2023-10-02 19:46 UTC, tetektoza commented
@gmta should be okay now, sorry for the mistake, now I get how it works :)

2023-10-24 09:43 UTC, timschumi requested changes
Looking good, just a few remaining style fixups.

2023-10-24 09:43 UTC, timschumi commented on Userland/Games/Minesweeper/CMakeLists.txt
> +    MainWidget.cpp
Same change here.

2023-10-24 09:43 UTC, timschumi commented on Userland/Games/Minesweeper/CustomGameDialog.cpp
> +                                       custom_game_widget,
That said, `CustomGameDialog` should probably be moved into the `Minesweeper` namespace as well, which alleviates the issue with too long type names.

2023-10-24 18:37 UTC, tetektoza commented on Userland/Games/Minesweeper/CMakeLists.txt
> +    MainWidget.cpp
Done.

2023-10-24 18:37 UTC, tetektoza commented on Userland/Games/Minesweeper/CMakeLists.txt
>      main.cpp
Done.

2023-10-24 19:47 UTC, timschumi approved these changes

2023-10-24 19:47 UTC, merged