LibGfx/JPEGWriter: Fix crash on macOS when csize coefficient is 0
SerenityOS/serenity pull request #21352
Opened 2023-10-06 09:57 UTC by warpdesign

This fixes #21108

2023-10-06 11:00 UTC, bplaat requested changes
Can you uncomment this test: https://github.com/SerenityOS/serenity/blob/master/Tests/LibWeb/Text/input/canvas/export.html#L16

The file https://github.com/SerenityOS/serenity/blob/master/Tests/LibWeb/Text/expected/canvas/export.txt becomes then: 
```
1. "image/png"
2. "image/jpeg"
```

2023-10-06 11:15 UTC, gmta commented on Userland/Libraries/LibGfx/ImageFormats/JPEGWriter.cpp
> +        return (u8)floor(log2(abs(coefficient))) + 1;
```suggestion
        return static_cast<u8>(floor(log2(abs(coefficient)))) + 1;
```

2023-10-06 13:39 UTC, LucasChollet commented
If we go this way I would really like more explanations in the commit message. Like explicitly say that you're casting `-inf` to a `u8` (I'm so surprised that it's not UB 😅).

But anyway I don't think that it's a good way to solve that issue. The spec defines `csize` for a determined set of input and zero is not a part of it. IMO, if there is anything to do in this function is to `VERIFY` that the input is not null. There is definitely an issue upstream, let's not extend the spec to workaround one of our issues.

2023-10-06 14:33 UTC, warpdesign commented
> If we go this way I would really like more explanations in the commit message. Like explicitly say that you're casting `-inf` to a `u8` (I'm so surprised that it's not UB 😅).
> 
> But anyway I don't think that it's a good way to solve that issue. The spec defines `csize` for a determined set of input and zero is not a part of it. IMO, if there is anything to do in this function is to `VERIFY` that the input is not null. There is definitely an issue upstream, let's not extend the spec to workaround one of our issues.

Problem is that coefficient is `0` so log2(abs(coefficient)) returns `-inf`.

In Linux & macOS we both have 0, difference is that the cast to `u8` appears to be needed on macOS, not on Linux, but both have the sale problem in that this function is called with `0` and that will yield to `-inf`.

2023-10-06 14:43 UTC, Hendiadyoin1 commented
Would a simple
```cpp
if (coefficient == 0)
    return 0;
```
Not do the job?

2023-10-06 14:47 UTC, warpdesign commented
> Would a simple
> ```cpp
> if (coefficient == 0)
>     return 0;
> ```
> Not do the job?

I guess this would do it but according to @LucasChollet `coefficient` should not be 0 in the first place.

2023-10-06 15:08 UTC, LucasChollet commented
I will check that in details this weekend, but IIRC AC coefficient with a value of 0 are encoded differently. So I'm quite doubtful that this patch solves the issue, it doesn't crash anymore but is the output a properly encoded JPEG?

Also, sharing the bitmap that causes the issue would be useful.

2023-10-09 07:56 UTC, warpdesign commented
> I will check that in details this weekend, but IIRC AC coefficient with a value of 0 are encoded differently. So I'm quite doubtful that this patch solves the issue, it doesn't crash anymore but is the output a properly encoded JPEG?
> 
> Also, sharing the bitmap that causes the issue would be useful.

I updated my test page to use the generated jpeg dataUrl as src for an image element and it doesn't seem to be correct: it seems to be a valid jpeg file, but not the expected one.

Chrome output:

![image](https://github.com/SerenityOS/serenity/assets/199648/446c6f51-914a-47c5-87ed-6f1f3284c818)


Ladybird output (macOS):

![image](https://github.com/SerenityOS/serenity/assets/199648/20e22c91-2d88-4968-9682-f1000681cc63)

2023-10-09 08:54 UTC, warpdesign commented
This patch (as suggested by @Hendiadyoin1) appears to correctly fix the problem and the generated jpeg seems to be correct:

> return coefficient == 0.0 ? 0 : floor(log2(abs(coefficient))) + 1;

2023-10-09 18:35 UTC, LucasChollet commented
I thought that the issue was caused by AC coefficients, as `csize` is defined for AC coefficients in the spec. But the spec is not super clear on how to encode these DC parameters (you have to come up with the algorithm, only the output is described). And I ended up reusing this `csize` function, without checking the result for a null input.

So let's get your fix in! I think that I prefer Hendiadyoin's version though. Enough things are already going on over this line, no need to add a ternary operator. And no need to check for equality with `0.0`, `coefficient` is a `i16` so 0 is fine.

2023-10-09 19:25 UTC, LucasChollet approved these changes

2023-10-10 03:46 UTC, awesomekling commented
This is failing the lint check. Please run clang-format before uploading code :)

2023-10-10 10:15 UTC, BertalanD commented
Does the JPEG that's generated when the new early return is hit pass validation?

2023-11-02 17:06 UTC, warpdesign commented
> Does the JPEG that's generated when the new early return is hit pass validation?

How can I check JPEG validation? I tried converting the base64 text to a file and it can be opened without any problem with image viewers I have tried.

2023-11-09 14:45 UTC, bplaat approved these changes
Looks good to me

2023-11-09 15:07 UTC, merged