LibWeb: Support Object-position CSS property
SerenityOS/serenity pull request #21461
Opened 2023-10-16 12:00 UTC by TobyAsE

This PR add support for the object-position property.
As I recently built the object-fit property, this seemed like a logical next step.
With object-position you can tell your image how you want to paint it, very useful in combination with the object-fit!

I introduced the object-position property and a "Position Identifier", which can hold the different identifiers that are valid for the property. The rendering is then just a sea of pain with offsets and pixel-math.
This implementation looks the same in Ladybird and Firefox :^)

![image](https://github.com/SerenityOS/serenity/assets/6002167/bbf52f28-7c22-40ae-920b-3fb4556600be)
![image](https://github.com/SerenityOS/serenity/assets/6002167/94dff79f-62ec-47ec-9396-ed1ad3620570)

2023-10-16 15:14 UTC, AtkinsSJ requested changes
I think this wants to work a bit differently:
- Allow `"valid-types": [ "position" ]` in the JSON. (That means renaming the `position` enum we have to something else unfortunately.) It should parse as a `PositionStyleValue`, which we already have. `<position>` is a general type in VALUES-4 so we should allow it as such.
- Then, we can just say "object-fit takes a position" and won't need to decode things in `StyleProperties::object_position()`.

Otherwise, `StyleProperties::object_position()` is basically just doing parsing but not in the parser. :^)

Also, am I right in thinking that ObjectPosition could just hold LengthPercentages? `left` and `top` should be equivalent to `0%`, `right` and `bottom` to `100%`, and `center` to `50%` if I'm understanding correctly. That would make the logic simpler in a few places.

2023-10-27 15:23 UTC, TobyAsE commented on Userland/Libraries/LibWeb/CSS/Properties.json
> +  "object-position": {
That's embarrassing :^)

2023-10-27 15:24 UTC, TobyAsE commented on Userland/Libraries/LibWeb/Painting/ImagePaintable.cpp
> +            auto offset_x = 0;
They get casted to int further down anyway because of the intrect that is the draw_rect

2023-10-27 15:25 UTC, TobyAsE commented
@AtkinsSJ 
Thank you, you of course had the correct idea!
I changed the PR to incorporate your suggestions.

2023-10-30 09:14 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/CSS/Properties.json
> +  "object-position": {
Commit title still says it! :laughing:

2023-10-30 09:21 UTC, AtkinsSJ requested changes
Looks good now except the commit title. :wink: 

We shouldn't need a position enum, but I see why we do at the moment because of how `background-position` parsing works. I'll make a note to untangle that a bit later. :sweat_smile:

2023-10-30 09:44 UTC, TobyAsE commented
The title, of course!
All fixed now :^)
Has your yakstack already reached the moon?

2023-10-30 10:40 UTC, merged

2023-10-30 10:41 UTC, AtkinsSJ commented
> Has your yakstack already reached the moon?

I can neither confirm or deny the existence of the Yak Space Program.