ls: use indicator for sockets and pipes
SerenityOS/serenity pull request #21717
Opened 2023-10-31 16:58 UTC by LevitatingBusinessMan

Most implementations of ls have an indicator for pipes and sockets, namely `|` and `=`.
I added these indicators. I also gave pipes a yellow color like similar special files.

I am not sure how to write tests for this yet.
If someone could guide me in the right direction?

2023-10-31 23:58 UTC, LevitatingBusinessMan commented
Amended with capital word in commit message

2023-11-04 14:28 UTC, BertalanD requested changes
Hi and welcome to SerenityOS!

I have a tiny stylistic comment, but otherwise, this looks good to me!

Don't worry about tests, testing interactive utilities is currently not a priority – and we don't have a way to do it automatically.

2023-11-04 14:28 UTC, BertalanD commented on Userland/Utilities/ls.cpp
> +    Sock = 1 << 4,
We try to avoid unnecessary abbreviations in identifiers, please name it `Socket`.

2023-11-04 21:08 UTC, BertalanD approved these changes

2023-11-04 21:08 UTC, merged