JSSpecCompiler: Work on the `-xspec` parser (and a test for it!)
SerenityOS/serenity pull request #22794
Opened 2024-01-16 05:31 UTC by DanShaders

2024-01-16 06:33 UTC, DanShaders commented
Actually, I lied in the 3th commit description -- we can't parse any. But with an additional 2 line fix, the count goes up to 17 (and their AST look correct on the first glance)!

2024-01-19 00:40 UTC, ADKaster requested changes
Seems overall good progress, but I'm skeptical on the architecture of the DiagnosticEngine. 

- Does it really need to be a singleton? It's owned by the current TU, and needs to be scoped as such.
- The with() function to change the instance seems awkward to use


Is the DiagnosticEngine really the right level to be creating a global state? I think clang has like a SourceManager or some such, which at least makes it obvious that you're reaching into per-TU data.

2024-01-19 00:40 UTC, ADKaster commented on Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/DiagnosticEngine.cpp
> +thread_local DiagnosticEngine* DiagnosticEngine::m_instance = nullptr;
Does this really need to be thread_local? Or are you intending to multi-thread this thing and have different diagnostics per thread?

2024-01-19 00:40 UTC, ADKaster commented on Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Function.h
> +    DiagnosticEngine diagnostic_engine;
If the translation unit owns the Diagnostic engine, why does it need to be globally accessible? Can't the parser just do translation_unit->diag().fatal_error() or some such?

2024-01-19 00:40 UTC, ADKaster commented on Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/Parser/ParseError.h
>      static NonnullRefPtr<ParseError> create(ErrorOr<String> message, XML::Node const* node);
perhaps we should be asking the Diagnostic engine to create our errors for us? Then we wouldn't need the "Current file" concept.

2024-01-19 00:40 UTC, ADKaster commented on Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/DiagnosticEngine.h
> +    static DiagnosticEngine& instance();
we use the() for singletons, if this really needs to be one.

2024-01-19 00:40 UTC, ADKaster commented on Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/DiagnosticEngine.h
> +    size_t line = 0, column = 0;
one declaration per line, please

2024-01-19 00:40 UTC, ADKaster commented on Meta/Lagom/Tools/CodeGenerators/JSSpecCompiler/DiagnosticEngine.h
> +    friend Location;
If the only thing we need from the DiagnosticEngine is the current file, I would prefer a public "filename()" getter to friendship.

2024-01-19 02:29 UTC, DanShaders commented
@ADKaster Questions in comments are not applicable anymore :) I've redesigned the whole thing so that `DiagnosticEngine` is now fully owned by TU and `Location`s are only created by `SpecificationParsingContext` which I pass around as a second argument.

2024-01-21 21:56 UTC, ADKaster approved these changes

2024-01-21 21:57 UTC, ADKaster commented
Very nice! I like the context-based approach better than the global  that gets swapped out all the time approach much better.

2024-01-21 21:57 UTC, merged