LibC: Separate arch dependent fenv functions
SerenityOS/serenity pull request #22888
Opened 2024-01-21 14:12 UTC by TomFinet

Remove all functions with platform #if's from fenv, and add arch dependent implementations instead. 
The build system now selects the implementation based on the platform.

This PR addresses #22657.

2024-01-21 22:38 UTC, ADKaster requested changes
Thanks for taking a crack at this issue! The new files seem much cleaner, thanks. I have a few comments about the copyright lines, and then we should be good to go on this.

2024-01-21 22:38 UTC, ADKaster commented on Userland/Libraries/LibC/arch/x86_64/fenv.cpp
> + * Copyright (c) 2021, Mițca Dumitru <dumitru0mitca@gmail.com>
Could you update the year here to `2021-2024`

2024-01-21 22:38 UTC, ADKaster commented on Userland/Libraries/LibC/arch/aarch64/fenv.cpp
> + * Copyright (c) 2021, Mițca Dumitru <dumitru0mitca@gmail.com>
The aarch64 and riscv files seems different enough that you can put either your own copyright line, or, if you don't feel comfortable doing that (but you should feel comfortable :) ), the generic 'the SerenityOS Developers` line.

the year for these new files should just be 2024.

2024-01-22 13:43 UTC, kleinesfilmroellchen requested changes
Thanks for doing this, even though I'm going to have a lot of fun rebasing the RISC-V implementation on top of this... just a small thing that slipped through.

2024-01-22 13:43 UTC, kleinesfilmroellchen commented on Userland/Libraries/LibC/arch/aarch64/fenv.cpp
> +    TODO_RISCV64();
TODO_AARCH64

2024-01-23 03:06 UTC, ADKaster approved these changes

2024-01-23 03:06 UTC, merged