AK: References in Tuple and structured binding
SerenityOS/serenity pull request #23403
Opened 2024-02-29 14:54 UTC by Hendiadyoin1

### AK: Allow structured bindings of AK::Tuple

The plumbing was already in place, we only needed to add the std::*
overloads

### AK: Allow using references in Tuple

This also tests them by checking if assignment through them works.

2024-02-29 19:18 UTC, ADKaster requested changes
The two cases where you enabled structured bindings for Tuple should be re-written to use a struct with named items, not a Tuple.

2024-02-29 19:18 UTC, ADKaster commented on AK/Tuple.h
> +}
It's not legal to forward declare these...

If the stdlib is libc++, these will actually be declared in `_LIBCPP_NAMESPACE_STD` which defaults to `namespace std { inline namespace __v1 {`, or other names on weird platforms like Android where there's a 'system' libc++ and a 'user' libc++ in different ABI namespaces.

What happens if you compile a source file that includes both `AK/Tuple.h` and `<tuple>` ? with both libc++ and libstdc++. 

Have a look here: https://godbolt.org/z/9c78dE6EY

2024-02-29 19:19 UTC, ADKaster commented on AK/Tuple.h
> +    {
I'd rather not add logic to allow using references in Tuple without a real use case in user/library code that needs it

2024-03-01 13:28 UTC, nico commented
The LibPDF commit in here looks good to me.

2024-03-01 21:05 UTC, ADKaster approved these changes

2024-03-01 21:05 UTC, merged