LibWeb: Allow selecting select options without value
SerenityOS/serenity pull request #23511
Opened 2024-03-07 18:11 UTC by bplaat

Currently the `<select>` dropdown ipc uses the option value attr to find which option is selected. This won't work when options don't have values or when multiple options have the same value. Also the `SelectItem` contained so weird recursive structures that are imposible to create with HTML. So I refactored `SelectItem` as a variant, and gave the options a unique id. That id is send back to `HTMLSelectElement` so it can find out exactly which option element is selected.

So now you can select the items in this select for example:
```html
<select>
    <option value="">Lorem ipsum dolor sit amet.</option>
    <option value="">Beatae minus sunt quae dolor.</option>
    <option value="">Inventore nulla doloremque corrupti in?</option>
    <option value="">Laudantium, error. Beatae, itaque sit!</option>
    <option value="">Adipisci a harum dolores molestiae!</option>
</select>
```

I also updated the styling of a `<option>` in a `<optgroup>` a bit by giving the label some indent like other browsers do. And I fixed a bug where the `disabled` attr was ignored.

2024-04-01 10:48 UTC, bplaat commented
Sorry to tag you but this pr has been sitting here for a long time unreviewed so, @trflynn89 or @ADKaster can you please look at this?

2024-04-02 16:16 UTC, trflynn89 requested changes
A couple higher level notes:
* Please put some of the PR description in the commit description too, with typos/grammar fixed
* Please use more atomic commits, instead of doing everything in one commit:
> I also updated the styling of a <option> in a <optgroup> a bit by giving the label some indent like other browsers do. And I fixed a bug where the disabled attr was ignored.

Each of those should be separate commits.

2024-04-02 16:16 UTC, trflynn89 commented on Userland/Libraries/LibWeb/HTML/SelectItem.cpp
> +template<>
newlines between functions please, here and below

2024-04-02 16:16 UTC, trflynn89 commented on Userland/Libraries/LibWeb/HTML/SelectItem.h
> +    u32 id;
Initialize primitive types in structs: `u32 id { 0 };`

2024-04-02 16:16 UTC, trflynn89 commented on Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp
> +void HTMLSelectElement::did_select_item(Optional<u32> id)
Seems like this can be `Optional<u32> const& id`

2024-04-02 16:16 UTC, trflynn89 commented on Userland/Libraries/LibWebView/ViewImplementation.cpp
> +void ViewImplementation::select_dropdown_closed(Optional<u32> selected_item_id)
Same re: `Optional<u32> const&`

2024-04-02 16:16 UTC, trflynn89 commented on Userland/Services/WebContent/PageClient.cpp
> +void PageClient::select_dropdown_closed(Optional<u32> selected_item_id)
Same re: `Optional<u32> const&`

2024-04-02 16:16 UTC, trflynn89 commented on Userland/Libraries/LibWeb/HTML/SelectItem.h
> +    JS::Handle<HTMLOptionElement> option_element = {};
Does this need to be a handle? Or can it just be a `GCPtr` / `NonnullGCPtr` that we visit in `visit_edges`?

2024-04-03 17:28 UTC, bplaat commented
Thanks for the review, good remarks. I know that I need to work on creating smaller commits 😄. I have fixed all your issues

2024-04-05 19:55 UTC, trflynn89 reviewed
Just missing a visit

2024-04-05 19:55 UTC, trflynn89 commented on Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp
> +            visitor.visit(item.get<SelectItemOption>().option_element);
If the item contains `SelectItemOptionGroup`, you will also need to visit each `option_element` in the `Vector<SelectItemOption>` list.

2024-04-05 19:55 UTC, trflynn89 commented on Userland/Libraries/LibWeb/Page/Page.cpp
> +            select_element.did_select_item(move(selected_item_id));
nit: you can drop the `move`

2024-04-08 21:24 UTC, merged