LibPDF+PDFViewer+MacPDF: Don't draw hidden text by default
SerenityOS/serenity pull request #23593
Opened 2024-03-15 01:30 UTC by nico

Text can be rendered in various ways in PDFs: Filled, stroked, both filled and stroked, set as clipping path, hidden, or some combinations thereof.

We don't implement any of this at the moment except "filled".

Hidden text is used in scanned documents: The image of the scan is drawn in the background, and then OCRd text is "drawn" as hidden on top of the scanned bitmap. That way, the (hidden) text can be selected and copied, and it looks like you're selecting text from the scanned bitmap. Find-in-page also works similarly. (We currently have neither text selection nor find-in-page, but one day we will.)

Now that we have pretty good support for CCITT and are growing some support for JBIG2, we now draw both the scanned background image as well as the foreground text. They're not always perfectly aligned.

This change makes it so that we don't render text that's marked as hidden. (We still do most of the coordinate math, which will probably come in handy at some point when we implement text selection.)

This makes these scanned documents appear as they're supposed to appear (at least in documents where we manage to decode the background bitmap).

This also adds a debug option to force rendering of hidden text.

2024-03-15 01:30 UTC, nico commented
Before:

<img width="919" alt="Screenshot 2024-03-14 at 9 24 01 PM" src="https://github.com/SerenityOS/serenity/assets/3487/2c55ba81-36d5-4814-9ec9-7057c9c718be">

After:

<img width="919" alt="Screenshot 2024-03-14 at 9 23 56 PM" src="https://github.com/SerenityOS/serenity/assets/3487/742e39a8-d382-4ad7-8ee7-cf1212190c92">

2024-03-16 13:23 UTC, trflynn89 requested changes

2024-03-16 13:23 UTC, trflynn89 commented on Userland/Applications/PDFViewer/PDFViewer.cpp
> +    m_rendering_preferences.show_hidden_text = Config::read_bool("PDFViewer"sv, "Rendering"sv, "ShowHiddenTexte"sv, false);
Typo - `ShowHiddenTexte`

2024-03-16 15:47 UTC, nico commented on Userland/Applications/PDFViewer/PDFViewer.cpp
> +    m_rendering_preferences.show_hidden_text = Config::read_bool("PDFViewer"sv, "Rendering"sv, "ShowHiddenTexte"sv, false);
Whoops, thanks for catching this!

2024-03-16 17:10 UTC, merged

2025-07-03 20:46 UTC, nico commented
Zombie remark: Since text for OCR'd docs isn't visible anyways and is only used for selecting and copying, some PDFs (eg created by Google Books) don't use a real font for hidden text, but one with dummy glyphs (for file size reasons, presumably). Here's e.g. paradise lost with hidden text hidden:

<img width="795" alt="Paradise Lost_p22_after" src="https://github.com/user-attachments/assets/363a7261-1d4a-4b7a-8bcc-fa0b11b0bf2f" />

And here it is with it shown, via the debug option:

<img width="795" alt="Paradise Lost_p22_before" src="https://github.com/user-attachments/assets/2e80326b-5491-457f-9aae-0ed66097f7ca" />