LibJS: Separate validation of roundingIncrement option
SerenityOS/serenity pull request #23656
Opened 2024-03-20 18:22 UTC by dlarocque

This is an editorial change in the temporal spec.

See: https://github.com/tc39/proposal-temporal/commit/712c449

Ticks off a box in https://github.com/SerenityOS/serenity/issues/15525

2024-03-21 16:45 UTC, shannonbooth requested changes
I've run this MR on [libjs-test262](https://github.com/SerenityOS/libjs-test262). Unfortunately it looks like the test `test/built-ins/Temporal/PlainTime/prototype/round/roundingincrement-invalid.js` failed after these changes (it previously passed).

One of the example assertion failures is:
```js
const plainTime = Temporal.PlainTime.from("08:22:36.123456789");
assert.throws(RangeError, () => plainTime.round({ smallestUnit: "minutes", roundingIncrement: 60 }));
```

2024-03-21 22:39 UTC, dlarocque commented
> I've run this MR on [libjs-test262](https://github.com/SerenityOS/libjs-test262). Unfortunately it looks like the test `test/built-ins/Temporal/PlainTime/prototype/round/roundingincrement-invalid.js` failed after these changes (it previously passed).
> 
> One of the example assertion failures is:
> 
> ```js
> const plainTime = Temporal.PlainTime.from("08:22:36.123456789");
> assert.throws(RangeError, () => plainTime.round({ smallestUnit: "minutes", roundingIncrement: 60 }));
> ```

Seems like I passed the wrong value of `inclusive` to one of the calls to `validate_temporal_rounding_increment`- this test should be passing now :+1: 

Aside: Is there a convenient way to check which tests fail that previously passed?

2024-03-21 22:45 UTC, shannonbooth commented
> > I've run this MR on [libjs-test262](https://github.com/SerenityOS/libjs-test262). Unfortunately it looks like the test `test/built-ins/Temporal/PlainTime/prototype/round/roundingincrement-invalid.js` failed after these changes (it previously passed).
> > One of the example assertion failures is:
> > ```js
> > const plainTime = Temporal.PlainTime.from("08:22:36.123456789");
> > assert.throws(RangeError, () => plainTime.round({ smallestUnit: "minutes", roundingIncrement: 60 }));
> > ```
> 
> Seems like I passed the wrong value of `inclusive` to one of the calls to `validate_temporal_rounding_increment`- this test should be passing now 👍
> 
> Aside: Is there a convenient way to check which tests fail that previously passed?

Nice! Could you please add a local `test-js` test to cover the regression?


In terms of getting the test results - first, you can establish a baseline (before any changes):

```
python3 main.py --libjs-test262-runner ./Build/bin/test262-runner --test262-root ./test262/ --per-file old
```

Then rebuild with your changes, get latest results:

```
python3 main.py --libjs-test262-runner ./Build/bin/test262-runner --test262-root ./test262/ --per-file new
```

Diff the results:
```
./per_file_result_diff.py -o old -n new
```

2024-03-21 23:25 UTC, dlarocque commented
> Nice! Could you please add a local `test-js` test to cover the regression?
> 
> In terms of getting the test results - first, you can establish a baseline (before any changes):
> 
> ```
> python3 main.py --libjs-test262-runner ./Build/bin/test262-runner --test262-root ./test262/ --per-file old
> ```
> 
> Then rebuild with your changes, get latest results:
> 
> ```
> python3 main.py --libjs-test262-runner ./Build/bin/test262-runner --test262-root ./test262/ --per-file new
> ```
> 
> Diff the results:
> 
> ```
> ./per_file_result_diff.py -o old -n new
> ```

Thanks! I'll use that before submitting the PR next time :sweat_smile: 

I've added some tests to cover the regression

2024-03-22 02:54 UTC, dlarocque commented on Userland/Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
> +    if (static_cast<u64>(dividend) % floored_increment != 0) {
Updated 👍

2024-03-22 09:06 UTC, shannonbooth approved these changes

2024-03-23 12:45 UTC, merged