Ports: Update rvvm to 0.6
SerenityOS/serenity pull request #23673
Opened 2024-03-22 08:28 UTC by LekKit

- New upstream stable version is available
- Networking is now fully stable and enabled by default
- SDL2 backend is now available alongside SDL1, so switch to it on Serenity
- Fixed a name collision of PAGE_SIZE identifier with Serenity libc headers
- Much faster serial IO (Terminal) on Serenity
- Many other changes and fixes
- See https://github.com/LekKit/RVVM/releases/tag/v0.6 for EFI firmware and demo images

Note: Due to sloppy scheduler/threading behavior on Serenity, threaded IO is disabled in this port for now. Otherwise U-Boot randomly fails to read data from NVMe, or fails to initialize NVMe altogether, along with other IO issues in guests - all due to threaded tasks being randomly delayed for very long.

I am not an expert on how scheduler works in Serenity, so I am unable to fix it yet. This problem was also visible in previous v0.5 version of this port, but back then I thought it's some kind of a temporary problem. Couldn't reproduce this on any other host OS.

Screenshots (Maybe for https://ports.serenityos.net/rvvm):

![serenity_rvvm_0 6_1](https://github.com/SerenityOS/serenity/assets/50500857/f1d32f1b-0cc5-4de3-a7ac-983124e112c3)

![serenity_rvvm_0 6_doom](https://github.com/SerenityOS/serenity/assets/50500857/bda41af6-b203-4413-8524-378be141d853)

2024-03-22 09:56 UTC, LekKit commented
CI seems to fail due to upstream LibWeb.

2024-03-23 10:32 UTC, timschumi requested changes

2024-03-23 10:32 UTC, timschumi commented on Ports/rvvm/package.sh
> +
We usually don't do `Maintainer` tags like this. If someone wants to maintain the port, they can do so without this comment, and all others are also free to create PRs that touch this file.

2024-03-23 10:32 UTC, timschumi commented on Ports/rvvm/patches/disable-threaded-io.patch
> +
This does not follow the proper patch format. Please move the patch and readme somewhere safe, and use `./package.sh dev` to create a commit with the desired changes, title, and description (which will then be automatically exported to the correct patch format on exit).

2024-03-23 12:00 UTC, timschumi approved these changes

2024-03-23 12:00 UTC, merged