Kernel: Add FATFS write support
SerenityOS/serenity pull request #23907
Opened 2024-04-09 20:42 UTC by implicitfield

This continues where #22852 left off, so the majority of the commits here are based on those in that PR. I've tested the write support on all the FAT variants we support, and `fsck_msdos` on macOS comes up with no errors when checking a filesystem that has been modified by this driver.

2024-04-09 21:16 UTC, Hendiadyoin1 commented on Kernel/FileSystem/FATFS/Inode.cpp
> +            TRY(block_list.try_append(BlockBasedFileSystem::BlockIndex { first_block_and_length.start_block.value() + i }));
Using `Better` as a verb is stretching it, but I'll allow it
(`Kernel/FATFS: Better error propagation in FATInode`)

2024-04-12 18:03 UTC, cqundefine reviewed
One small thing I noticed

2024-04-16 00:20 UTC, timschumi requested changes
Looking good so far, mainly a bunch of smaller nitpicks.

2024-04-16 00:20 UTC, timschumi commented on Kernel/FileSystem/FATFS/Inode.cpp
> +    auto blocks = TRY(read_block_list());
Maybe one of these two could use a better name.

2024-04-16 00:20 UTC, timschumi commented on Kernel/FileSystem/FATFS/Inode.cpp
> +        current_directory.first_cluster_high = entry.first_cluster_high;
Does this need to be guarded with a FAT32 check?

2024-04-16 00:20 UTC, timschumi commented on Kernel/FileSystem/FATFS/Inode.cpp
> +                    entry_first_cluster = (static_cast<u32>(entry->first_cluster_high) << 16) | entry->first_cluster_low;
```suggestion
                    entry_first_cluster |= (static_cast<u32>(entry->first_cluster_high) << 16);
```

2024-04-16 01:12 UTC, nico commented on Kernel/FileSystem/FATFS/FileSystem.cpp
> +            dbgln_if(FAT_DEBUG, "FATFS: FSInfo signature3: {}, expected: {}", m_fs_info.trailing_signature, fs_info_signature_3);
(Use `{:#x}` instead of `{}` to do that.)

2024-04-19 20:37 UTC, timschumi reviewed
Preliminary "LGTM", I'll give it a test run tomorrow. If you want to add your "Co-Authored-By" anywhere, now is the time. :^)

2024-04-20 17:52 UTC, timschumi commented
FAT images (all types) are exhibiting weird behavior for me now, even without writing anything. The attached images ([fat60.zip](https://github.com/SerenityOS/serenity/files/15049249/fat60.zip)) were created using `mkfs.fat` and populated under Linux, but stall very for very long while working on them under Serenity (FAT12 even when just listing the root directory, the others when trying to read the large bin file).

2024-04-21 13:34 UTC, timschumi approved these changes
Still a bit on the slow side with the new commits, but at least it can be worked with. :^)

2024-04-21 13:34 UTC, merged