Kernel/Ext2FS: Allocate blocks lazily + support writing holes
SerenityOS/serenity pull request #24149
Opened 2024-04-28 15:18 UTC by implicitfield

... and also do a thorough refactor to be able to accomplish that, because the old implementation was extremely dependent on all blocks being sequential. There's a fairly long explanation of that in the relevant commit message.

This also accidentally fixes various situations where the filesystem would get slightly corrupted, such as when running the second of the following two commands:
```
dd if=/usr/lib/libweb.so.serenity of=foo.bin bs=1M count=50
truncate -s 35M foo.bin
```

Here's a more complete script that I used to test the correctness of this PR:
```
# test direct + singly indirect + doubly indirect blocks
dd status=none if=/usr/lib/libweb.so.serenity of=foo.bin bs=1M count=50
dd status=none if=/usr/lib/libweb.so.serenity of=/tmp/foo.bin bs=1M count=50
sha512sum /tmp/foo.bin | sed 's,/tmp/,,' | sha512sum -c

rm /tmp/*.bin

# test doubly indirect + triply indirect blocks
dd status=none if=/usr/lib/libweb.so.serenity of=bar.bin bs=1M count=50 seek=4096
dd status=none if=bar.bin bs=1M skip=4000 of=/tmp/bar.bin
dd status=none if=/usr/lib/libweb.so.serenity of=/tmp/foo.bin bs=1M count=50 seek=96
sha512sum /tmp/foo.bin | sed 's,foo,bar,' | sha512sum -c
```
Closes #6236.

2024-04-28 16:55 UTC, Hendiadyoin1 commented on Kernel/FileSystem/Ext2FS/Inode.cpp
> +            return {};
With a `Span` you could use either `contains_slow` or `AK::any_of` to make this a bit more concise

2024-04-28 16:55 UTC, Hendiadyoin1 commented on Kernel/FileSystem/Ext2FS/Inode.cpp
> +    auto singly_indirect_block_buffer = UserOrKernelBuffer::for_kernel_buffer((u8*)singly_indirect_block_contents);
See above

2024-04-28 16:55 UTC, Hendiadyoin1 commented on Kernel/FileSystem/Ext2FS/Inode.cpp
> +    }
please prefer structured bindings, as `block.key` and `block.value` dont mean much to people glancing at the code

2024-04-28 16:55 UTC, Hendiadyoin1 commented on Kernel/FileSystem/Ext2FS/Inode.cpp
> +    m_raw_inode.i_blocks = (m_block_list.size() + meta_blocks.size()) * (fs().logical_block_size() / 512);
is the 512 a meaningful number or just 512?

2024-04-28 19:17 UTC, Hendiadyoin1 commented on Kernel/FileSystem/Ext2FS/Inode.cpp
> +    m_raw_inode.i_blocks = (m_block_list.size() + meta_blocks.size()) * (fs().logical_block_size() / 512);
Was mainly confused why there's a magic number here, fine by me then I guess

2024-06-23 12:01 UTC, timschumi requested changes

2024-06-24 18:02 UTC, timschumi commented on Kernel/FileSystem/Ext2FS/Inode.cpp
> +        return 0;
That much I got, I just want to make sure that 0 won't ever actually be in the block list.

2024-06-29 17:15 UTC, timschumi approved these changes
```
#include <std_disclaimer.h>
/*
* Your warranty is now void.
*
* I am not responsible for bricked devices, dead SD cards,
* thermonuclear war, or you getting fired because the alarm app failed. Please
* do some research if you have any concerns about features included in this ROM
* before flashing it! YOU are choosing to make these modifications, and if
* you point the finger at me for messing up your device, I will laugh at you.
*/
```

2024-06-29 17:16 UTC, merged