LibWeb: Do not consume scroll event in PaintableBox without overflow
SerenityOS/serenity pull request #24228
Opened 2024-05-05 22:31 UTC by matjojo

Specifically, without scrollable overflow.

This fixes the bug that on old reddit with an expando open you could not scroll when having the cursor over the expando. Behaviour is now the same as on chromium and firefox.

The issue minimized to the following code:
```html
<!DOCTYPE html>
<body>
   <div style="overflow: auto; height: 250px; width: 250px; background-color: blue;"></div>
   <div style="height: 1080px; width: 50px; background-color: black;"></div>
</body>

</html>
```

A process question:
My commit title is less then 70 characters as the pre commit hook required. Would it be okay to expand the github title to longer to include the extra context that this is about scrollable overflow in the title here even if it goes past the 70 character view?

2024-05-06 01:09 UTC, kalenikaliaksandr commented
Could you add a text-test for this change please. the test will have to use `internals.wheel()` to hit changed function, you can use https://github.com/SerenityOS/serenity/blob/master/Tests/LibWeb/Ref/scroll-using-mousewheel-event.html as an example.

Also could you check if the change solve https://github.com/SerenityOS/serenity/issues/24009 ? if so, please mention the issue in the commit description.

2024-05-06 09:24 UTC, matjojo commented
@kalenikaliaksandr 

I created a test showing the expected behaviour and added the "fixes #24009" text to the commit text and the GitHub pull request text.

2024-05-07 00:40 UTC, kalenikaliaksandr requested changes

2024-05-07 00:40 UTC, kalenikaliaksandr commented on Tests/LibWeb/Ref/do-not-scroll-overflow.html
> +<!DOCTYPE html>
`do-not-scroll-overflow.html` test name sounds a bit confusing. could it be more descriptive, like `box-without-scrollable-overflow-should-not-consume-events.html`?

2024-05-07 14:04 UTC, merged