Prekernel: Make the prekernel stage more elegant and debuggable
SerenityOS/serenity pull request #24430
Opened 2024-05-24 05:27 UTC by supercomputer7

I realized recently that we could use the `FixedStringBuffer` class to perform string formatting without doing any memory allocations, which suits the use-case of the prekernel stage quite elegantly.
Therefore, I add a way to print debug logs (to serial console currently, and to bochs serial debug as well), and by doing so, we can actually see now debug prints during assertion failed scenarios, which is very nice imho :)

cc @ADKaster @timschumi

2024-05-25 21:33 UTC, spholz commented on Kernel/Prekernel/DebugOutput.cpp
> +    for (size_t i = 0; i < str.length(); ++i) {
You should be able to use `for (u8 c : str.bytes())` here.

2024-05-25 21:33 UTC, spholz commented on Kernel/Prekernel/StdLib.cpp
> +void halt()
StdLib.cpp seems like the wrong file name for a halt() function IMO,
but I can't think of a good name either

2024-05-27 18:13 UTC, supercomputer7 commented on AK/Format.cpp
> -#ifdef KERNEL
I don't think I understand your suggestion. what are you trying to achieve here?

2024-06-22 23:06 UTC, timschumi requested changes

2024-06-29 17:55 UTC, timschumi approved these changes

2024-06-29 17:56 UTC, timschumi commented on AK/Format.cpp
> -#ifdef KERNEL
Let's keep it as-is for now, judging by discussion on Discord it isn't as trivial to implement nicely. We can always add more improvements later.

2024-06-29 17:56 UTC, merged