Ports: Add Schism Tracker
SerenityOS/serenity pull request #24508
Opened 2024-06-01 08:27 UTC by OzzelotCZ

Add schismtracker port (so far, with flac support patched out).

2024-06-01 10:01 UTC, kennethmyhra requested changes
Welcome to the project!

First of, install the commit hooks that will make it easier for you to figure out locally if this will pass on CI: https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#commit-hooks

Use `./package.sh dev` to start a devlopment session, when you exit the development sessions after added your patches it will autogenerate a Readme file for the mentioned patches.

The commit hooks will also tell you that you are missing an entry for Schism Tracker in AvailablePorts.md

2024-06-01 10:51 UTC, timschumi requested changes

2024-06-01 10:51 UTC, timschumi commented on Ports/schismtracker/package.sh
> +    "https://github.com/schismtracker/schismtracker/archive/$version.tar.gz#73c475b3344c460cbc543878f8c728af3c62fba11211604834d880c0a41a506e"
Please use the official source code tarball instead of the GitHub-generated one. That allows us to not depend on `autotools` on the build host.

2024-06-01 10:51 UTC, timschumi commented on Ports/schismtracker/package.sh
> +configopts=("--host=x86_64-pc-serenity")
This is already implicitly passed to the configure script.

2024-06-01 15:28 UTC, timschumi commented
Please make sure to squash the commits properly and to mark comments as "resolved" once you have taken care of the feedback.

2024-06-15 10:25 UTC, timschumi requested changes

2024-06-15 10:25 UTC, timschumi commented on Ports/schismtracker/package.sh
> +useconfigure=true
```suggestion
port='schismtracker'
version='20240523'
useconfigure='true'
```

2024-06-15 10:25 UTC, timschumi commented on Ports/schismtracker/package.sh
> +configopts="--without-flac"
```suggestion
depends=(
    'SDL2'
)
launcher_name='SchismTracker'
launcher_category='&Media'
launcher_command='/usr/local/bin/schismtracker'
configopts=(
    '--without-flac'
)
```

2024-06-15 20:59 UTC, timschumi approved these changes

2024-06-15 20:59 UTC, merged