Kernel/Memory: Make mmap objects track dirty and clean pages
SerenityOS/serenity pull request #24561
Opened 2024-06-12 16:34 UTC by brody-qq

This PR fixes this issue https://github.com/SerenityOS/serenity/issues/15951

* Pages of file mmap regions with no writes to them are marked as clean
* Writing to a clean page will mark the page as dirty
* When msync() is called:
    * Only dirty pages are flushed to storage
    * The flushed pages are now synced with storage, so they are marked clean and remapped
    * NOTE: This only applies to SharedInodeVMObjects
* When purge() is called, only clean pages are evicted from memory

This PR also adds a few more test cases for private and shared file mmaps

2024-06-12 16:38 UTC, brody-qq commented
A lot of my testing was done by running the following 2 programs in userspace and checking the debug logs for anything unusual:
* https://github.com/brody-qq/serenity/blob/debug-mmap-dirty-pages/Userland/Utilities/test_mmap_dirty_pages.cpp
* https://github.com/brody-qq/serenity/blob/debug-mmap-dirty-pages/Userland/Utilities/test_mmap_dirty_pages_parallel.cpp

If anyone has advice on better ways to test this I would appreciate it!

2024-06-20 03:18 UTC, brody-qq commented
I updated this to remove a FIXME comment that is fixed by this PR

```
--- a/Kernel/Memory/Region.cpp
+++ b/Kernel/Memory/Region.cpp
@@ -56,10 +56,8 @@ Region::Region(VirtualRange const& range, NonnullLockRefPtr<VMObject> vmobject,
 
 Region::~Region()
 {
-    if (is_writable() && vmobject().is_shared_inode()) {
-        // FIXME: This is very aggressive. Find a way to do less work!
+    if (is_writable() && vmobject().is_shared_inode())
         (void)static_cast<SharedInodeVMObject&>(vmobject()).sync_before_destroying();
-    }
 
     m_vmobject->remove_region(*this);

```

2024-07-06 21:09 UTC, timschumi requested changes
Minor nitpicks, everything else looks great.

2024-07-07 16:24 UTC, timschumi approved these changes
LGTM, waiting on CI (although I don't expect anything to have broken due to the requested changes).

EDIT: Am idiot, CI already passed before I managed to write this comment.

2024-07-07 16:25 UTC, merged