Net: Implement SO_LINGER support in TCPSocket close behavior
SerenityOS/serenity pull request #25037
Opened 2024-09-22 21:48 UTC by logkos

This simple option lets us change behavior of close() on connection-oriented protocols so we can close a socket without TCP shenanigans.
This feature is used in dropbear and libuv ports and allows some other advanced socket operations too.

2024-09-26 22:31 UTC, nico commented on Kernel/Net/TCPSocket.cpp
> +        TRY(send_tcp_packet(TCPFlags::FIN | TCPFlags::ACK));
is the TRY() change right? we now don't do a bunch of teardown work on failing send that we did do before. In any case, it seems unrelated to the rest of this PR.

2024-09-27 17:40 UTC, nico commented
(looks like the updated commit description has lines longer than 72 chars, making CI unhappy.)

2024-09-28 01:31 UTC, nico commented
Looks like you also need to use "Kernel/Net: " instead of "Net: " as prefix in the commit title.

2024-10-02 03:05 UTC, DanShaders commented
Nice work! This was one of the (many) blockers needed to make my asynchronous sockets work on Serenity. I would love to see a test for this though, something like: create a TCP socket pair, make one of the ends non-blocking with 0/x second lingering, sends a ton of data to overflow receive/send buffers, close that end, poll the other end and see how fast POLLERR arrives.

2024-10-07 22:29 UTC, kleinesfilmroellchen requested changes
In general, I’m not even sure whether data can be properly acked int the background while the socket is almost closed (you never change the state after linger was detected), so... the TCP logic here is very dubious.

2024-10-07 22:29 UTC, kleinesfilmroellchen commented on Kernel/Net/TCPSocket.cpp
> +            (void)send_tcp_packet(TCPFlags::RST);
where are these reset packets coming from, that doesn’t look very state-machine correct? see the code below that follows TCP state machine behavior.

2024-10-07 22:29 UTC, kleinesfilmroellchen commented on Kernel/Net/TCPSocket.cpp
> +            if (has_unacked_data) {
you never re-check the unacked data, meaning this variable will likely not correctly reflect the current state of things at this point (likely, most data was acked by now, but that’s not checked).

2024-10-07 22:29 UTC, kleinesfilmroellchen commented on Kernel/Net/TCPSocket.cpp
> +                    break;
this check seems pointless and can just be part of the while instead

2024-10-07 22:29 UTC, kleinesfilmroellchen commented on Kernel/Net/TCPSocket.cpp
> +                (void)send_tcp_packet(TCPFlags::RST);
I’m also not sure whether this is state-machine-correct behavior? are we not supposed to send just a FIN in this case?

2024-11-16 16:18 UTC, closed without merging