Browser: Port browser to GML compilation
SerenityOS/serenity pull request #25399
Opened 2024-11-15 15:33 UTC by overriden-sfdd

This PR contributes to #20518
It ports Browser. I'm open for suggestions regarding refactoring of BrowserTabWidget. It's quite puzzling. I'm not sure the way I did it is the best. Please review carefully.
Additionally, I got confused with all the different initialization functions like `try_create`, `initialize`, and `setup`. Do we prefer `initialize` over `setup` now?

2024-11-15 15:39 UTC, overriden-sfdd commented
Oh yes, one more thing to add that felt kinda wrong. The GML compiler works in a way that prevents forward declaration in widget headers. I wonder if there's anything we can do about that and if that's intended. Widget headers become quite huge because of that.

2024-11-28 02:21 UTC, nico commented
Looks like this needs rebasing now, sorry!

As for the questions, iirc @kleinesfilmroellchen wrote the GML compiler. Film, do you know what we do about forward declarations? Just not worry about it?

2025-03-02 12:32 UTC, timschumi requested changes
First round of feedback, will take a closer look after most of the visual noise has been taken care of.

2025-03-02 12:32 UTC, timschumi commented on Userland/Applications/Browser/StorageWidget.cpp
> +    return widget;
Please do not invent any new ways of running fallible initialization (or any kind of initialization). The GML compiler has [a set method signature](https://github.com/SerenityOS/serenity/blob/master/Base/usr/share/man/man5/GML/Usage.md#initialize-pattern) that gets invoked automatically if available.

2025-03-02 12:32 UTC, timschumi commented on Userland/Applications/Browser/Tab.cpp
> +        if (auto storage_widget = StorageWidget::create(); !storage_widget.is_error()) {
Are we sure that this window should just be empty if the widget fails to initialize?

2025-03-02 12:32 UTC, timschumi commented on Userland/Applications/Browser/History/HistoryModel.h
> +
Was this caused by `clang-format`?

2025-03-02 12:32 UTC, timschumi commented on Userland/Applications/Browser/History/HistoryWidget.cpp
> +ErrorOr<void> HistoryWidget::setup()
Same here regarding the initialization function.

2025-03-02 12:32 UTC, timschumi commented on Userland/Applications/Browser/Tab.cpp
> +        if (auto history_widget = History::HistoryWidget::create(); !history_widget.is_error()) {
And same here regarding the empty window.

2025-03-02 12:32 UTC, timschumi commented on Userland/Applications/Browser/History/HistoryWidget.cpp
>   */
Commit message nitpick: Title got duplicated into the body.

2025-03-02 12:32 UTC, timschumi commented on Userland/Applications/Browser/BookmarksBarWidget.cpp
> + * Copyright (c) 2024, the SerenityOS developers
Please do not remove other contributors' copyright.

2025-03-02 12:32 UTC, timschumi commented on Userland/Applications/Browser/BookmarksBarWidget.cpp
> +#include "EditBookmarkDialog.h"
This should most likely be an include of the format `<Applications/Browser/...>`.

2025-03-02 12:32 UTC, timschumi commented on Userland/Applications/Browser/BookmarksBarWidget.cpp
> +BookmarksBarWidget::BookmarksBarWidget(ByteString const& bookmarks_file, bool const enabled)
This (and most of the changes in this commit) don't seem to be related to GML compilation. Please split them out into a separate commit or drop them completely.

2025-03-02 12:32 UTC, timschumi commented on Userland/Applications/Browser/BookmarksBarWidget.cpp
> + * Copyright (c) 2023, Cameron Youell <cameronyouell@gmail.com>
Disregard the previous comment regarding copyrights, these additions just need to be moved to the previous commit.

2025-03-02 12:32 UTC, timschumi commented on Userland/Applications/Browser/EditBookmarkDialog.h
> +enum class PerformEditOn {
Regarding the whole commit: Please make sure that `clang-format` runs properly after each individual commit, and drop the all-in-one fix that has been attached at the end.

2025-03-02 14:11 UTC, nico reviewed
(since timschumi is reviewing, here are some draft comments i made when i this was new; then i realized i didn't have time to see it through and didn't send them. apologies if they're dupes!)

2025-04-01 05:22 UTC, closed without merging