Base: Soms cleanups by moving /res folders to /usr/share and removing some useless config files
SerenityOS/serenity pull request #25606
Opened 2024-12-30 19:45 UTC by bplaat

These commits clean up the `/res` and `/home/anon/.config` folders a bit.

All application specific non graphic files need to exist in `/usr/share` and not in `/res` so I moved them. Only `/res/ladybird` remains but that folder is special in the build system and would require a larger refactor.

Also where there some all default config files which could easily be removed, they are created on the fly when settings are changed.

Some files in `/home/anon/.config` to be moved to a more global dir, for better multi user support but I'll look into that in the future.

2024-12-31 00:07 UTC, alimpfard commented
I'm not entirely sure about the motivation here, but leaving that bit aside, I personally like having config files that specify the default behaviour instead of having them hidden in the code.

2024-12-31 10:42 UTC, bplaat commented
The default values must are already be in the code, so the files are not needed. In the end we need to move all the files out of the anon home folder because it won't work when creating other users.

2025-02-01 13:24 UTC, timschumi requested changes
Not actually changes required on this PR, but we shouldn't merge this until the Discord bot is updated.

2025-02-01 13:24 UTC, timschumi commented on Userland/Games/MasterWord/WordGame.cpp
> +        auto response = TRY(Core::File::open("/usr/share/MasterWord/words.txt"sv, Core::File::OpenMode::Read));
I thought we had some other use for `words.txt` (that is not `MasterWord` specific), but apparently not (or it was just planned).

2025-02-01 13:24 UTC, timschumi commented on Userland/Utilities/fortune.cpp
> -    StringView path = "/res/fortunes.json"sv;
Doing this will also require an update to the [Discord bot](https://github.com/SerenityOS/discord-bot/blob/649643dd08efa2ee03f7b31ff7244da2ad8d6bcd/src/apis/githubAPI.ts#L62).

2025-02-01 13:34 UTC, bplaat commented
Ah good point, when I've time I'll look into it

2025-03-01 20:42 UTC, closed without merging

2025-09-02 17:04 UTC, bplaat commented on Userland/Utilities/fortune.cpp
> -    StringView path = "/res/fortunes.json"sv;
I've created https://github.com/SerenityOS/discord-bot/pull/1081

2025-09-25 11:03 UTC, timschumi approved these changes