AK:IDAllocator seed random generator to prevent sequence regeneration
SerenityOS/serenity pull request #3192
Opened 2020-08-17 16:32 UTC by tryfinally

2020-08-17 16:38 UTC, awesomekling commented
What bug is this fixing? Please explain why you are doing things, that's what commit messages (and PR descriptions) are for :)

2020-08-18 07:42 UTC, bgianfo commented
Is there a reason why the IdAllocator is a HashSet? It seems like a bitmap would be more fitting, faster, and smaller size.

2020-08-26 23:32 UTC, BenWiederhake requested changes

2020-08-26 23:32 UTC, BenWiederhake commented on AK/IDAllocator.h
> -                ++allocated_id;
This part doesn't make sense to me. What if `r` happens to be `4294967296-i` or slightly lower? Then `r+i` will be `0`. In fact, `i=0` is not a special case at all.

It should take at least 65536 allocated IDs until this loop actually running more than once or twice (see: birthday paradox, and `int` is 32 bit`). Let's not over-optimize this too early. Or do you profile something and IDAllocator was the culprit?

2020-08-26 23:35 UTC, BenWiederhake commented
> It seems like a bitmap would be more fitting, it's faster, and will consume less memory.

Are you sure about that? The IDs are effectively randomly picked `int`s, if we can trust `rand()`. So a bitset shouldn't be able to help.

2020-08-26 23:36 UTC, BenWiederhake commented on AK/IDAllocator.h
> +    IDAllocator() { srand(time(0)); }
Calling `srand` means we change global state. What if a program wants to be reproducible and intentionally called `srand(MAGIC_BUT_CONSTANT_NUMBER)` initially? Do we care about such "weird" setups?

2020-10-31 12:35 UTC, closed without merging