Pixel paint saving
SerenityOS/serenity pull request #3792
Opened 2020-10-18 16:56 UTC by BenJilks

This adds a few features to do with saving and loading in PixelPaint. It also fixes some issues with base64 decoding. In order to export the image to BMP, I had to create the BMPDumper class, to go along-side BMPLoader.

2020-10-18 17:06 UTC, linusg requested changes

2020-10-18 17:06 UTC, linusg commented on Applications/PixelPaint/CreateNewImageDialog.cpp
> +#include "CreateNewImageDialog.h"
Missing license header, causing CI to fail

2020-10-18 17:06 UTC, linusg commented on Applications/PixelPaint/CreateNewImageDialog.h
> +#pragma once
Missing license header

2020-10-18 17:08 UTC, awesomekling commented
`BMPDumper` is a bit of a sad name.. how about we call it `BMPWriter` (and maybe rename `BMPLoader` to `BMPReader` as well)?

2020-10-18 19:31 UTC, alimpfard commented
I have a feeling (from just skimming the code) that applying filters does not report "did complete action"?

2020-10-18 19:33 UTC, BenJilks commented
@alimpfard You're right there, I forgot about them. I'll add them as actions.

2020-10-19 09:42 UTC, awesomekling commented on Applications/PixelPaint/History.h
> +class History {
Please use `GUI::UndoStack` and `GUI::Command` instead of inventing something new :)
(they are modeled after Qt's `QUndoStack` and `QCommand`)

2020-11-07 23:40 UTC, danboid commented
It will be good to see this get finished and merged. I'm surprised pixelpaint and serenity have got this far with no image encoding/saving function.

See if you can get it done before GIMP 3.0 gets released!

2020-11-13 13:37 UTC, danboid commented
Can't wait to test this out with my latest masterpiece!

2020-11-14 09:24 UTC, awesomekling commented
This breaks undo in TextEditor (try opening it, typing something, and pressing Ctrl+Z)

2020-11-20 20:31 UTC, danboid commented
Whatchya tink Mr K?

2020-11-22 15:07 UTC, merged

2020-11-22 15:07 UTC, awesomekling commented
Spicy! 🌶️