NotificationServer: Add a configurable notification timeout
SerenityOS/serenity pull request #4373
Opened 2020-12-09 21:41 UTC by metalvoidzz

2020-12-09 21:55 UTC, linusg requested changes

2020-12-09 21:55 UTC, linusg commented on Services/NotificationServer/NotificationWindow.cpp
> +    if (icon.is_valid() && config->read_num_entry("Window", "ShowIcons", true)) {
```suggestion
    if (icon.is_valid() && config->read_bool_entry("Window", "ShowIcons", true)) {
```

2020-12-09 21:58 UTC, metalvoidzz commented on Services/NotificationServer/NotificationWindow.cpp
> +    if (icon.is_valid() && config->read_num_entry("Window", "ShowIcons", true)) {
Thanks, overlooked that one

2020-12-10 10:04 UTC, awesomekling commented
This doesn't seem like a good default behavior to me.
If I went away from my computer for more than seconds, I still want to see my notifications when I return.

2020-12-10 10:13 UTC, metalvoidzz commented
Right, maybe we should have some kind of notification history applet, similar to clipboard history. It could change icons to tell you about unread notifications.

2020-12-15 05:30 UTC, bcoles commented
> 
> 
> Right, maybe we should have some kind of notification history applet, similar to clipboard history. It could change icons to tell you about unread notifications.

I like the idea of some sort of notification log. I also like the idea of having notifications disappear automatically.

Perhaps a notification applet icon could be displayed, with different icons depending on whether there are "new" notifications.

2021-04-14 22:47 UTC, linusg commented
@metalvoidzz do you still intend to make any changes here? Also, the PR has some merge conflicts that need to be resolved.

2021-04-16 06:48 UTC, closed without merging