LibJS: Implement String.prototype.endsWith()
SerenityOS/serenity pull request #4507
Opened 2020-12-23 06:15 UTC by XavierCooney

The relevant spec: https://tc39.es/ecma262/#sec-string.prototype.endswith.

2020-12-23 13:46 UTC, linusg requested changes
If you don't want to implement steps 3 and 4, please at least add a FIXME comment. :)

2020-12-23 13:46 UTC, linusg commented on Libraries/LibJS/Runtime/StringPrototype.cpp
> +    if (!vm.argument_count())
This is not part of the spec and therefore incorrect.

2020-12-23 13:48 UTC, linusg commented on Libraries/LibJS/Runtime/StringPrototype.cpp
> +    if (vm.argument_count() > 1) {
This is differently in the spec, there's a difference between argument is undefined and argument doesn't exist

2020-12-23 13:49 UTC, linusg commented on Libraries/LibJS/Runtime/StringPrototype.cpp
> +        end = min(string_length, number.to_size_t(global_object));
Please do not use to_size_t anymore, it's not part of the spec - use the function that's actually being used instead :)

2020-12-24 03:31 UTC, XavierCooney commented
Thanks, things should be corrected now, and I've added a few more tests for the cases I got wrong :).

2020-12-24 11:51 UTC, linusg reviewed
Hey, this looks great! I got a couple more suggestions, but well done :)

2020-12-24 11:51 UTC, linusg commented on Libraries/LibJS/Runtime/StringPrototype.cpp
> +        return !matcher.to_boolean();
When the spec says "If matcher is not undefined, return ! ToBoolean(matcher).", the "!" just means the operation cannot throw, and not exception check is needed (yes, it's a confusing way to express this):

https://tc39.es/ecma262/#sec-returnifabrupt-shorthands

> Similarly, prefix ! is used to indicate that the following invocation of an abstract or syntax-directed operation will never return an abrupt completion and that the resulting Completion Record's [[Value]] field should be used in place of the return value of the operation.

So:

```suggestion
        return matcher.to_boolean();
```

2020-12-24 11:51 UTC, linusg commented on Libraries/LibJS/Runtime/StringPrototype.cpp
> +    }
We already checked that `possible_regexp` is an object, so we can use `as_object()` and don't need an exception check:

```suggestion
    if (possible_regexp.as_object(global_object).is_regexp_object())
        return true;
```

2020-12-24 11:51 UTC, linusg commented on Libraries/LibJS/Runtime/StringPrototype.cpp
> +        return {};
No need for an exception check here :)

```suggestion
    auto search_string_value = vm.argument(0);
```

2020-12-24 11:51 UTC, linusg commented on Libraries/LibJS/Runtime/StringPrototype.cpp
> +    auto search_string = vm.argument(0).to_string(global_object);
```suggestion
    auto search_string = search_string_value.to_string(global_object);
```

2020-12-24 11:51 UTC, linusg commented on Libraries/LibJS/Runtime/StringPrototype.cpp
> +    }
Not mandatory, but you can skip the curly braces here:

```suggestion
    if (search_string_length == 0)
        return Value(true);
    if (pos < search_string_length)
        return Value(false);
```

2020-12-24 11:51 UTC, linusg commented on Libraries/LibJS/Runtime/StringPrototype.cpp
> +static bool is_regexp(VM& vm, GlobalObject& global_object, Value possible_regexp)
It [looks like the `RegExp` constructor will use this as well](https://tc39.es/ecma262/#sec-regexp-pattern-flags), so let's move it to `Value.cpp`/`Value.h`, next to all the other `is_*` functions (even though those don't take a vm and GlobalObject).

2020-12-25 13:20 UTC, linusg approved these changes
Awesome!

2020-12-26 00:09 UTC, merged