TextEditor: Added GML preview checkbox under 'View' and GML Preview
SerenityOS/serenity pull request #4587
Opened 2020-12-27 23:58 UTC by nanoproductions

Not a major change, basically took existing HTML/Markdown code written and modified to work with GML.

2020-12-28 11:22 UTC, danboid commented
Sounds v.cool!

2020-12-28 12:12 UTC, awesomekling requested changes

2020-12-28 12:12 UTC, awesomekling commented on Applications/TextEditor/TextEditorWidget.cpp
> +    m_page_view->load_from_gml(m_editor->text());
`m_page_view` is a web view, we should not be inserting random children into it.
This should be done with an empty `GUI::Widget` at the same level as `m_page_view`, possibly with both in a `GUI::StackWidget`.

2020-12-28 12:12 UTC, awesomekling commented on Applications/TextEditor/TextEditorWidget.h
> +    void update_GML_preview();
`update_gml_preview()`

2021-01-12 15:16 UTC, awesomekling commented
I don't believe this feature is useful, since we already have a dedicated program (GML Playground) for editing GML. This seems like it would only result in having two instances of the same functionality, and this one always being weaker than what's available in GML Playground.

2021-01-12 15:18 UTC, closed without merging