Line number integration through URL query
SerenityOS/serenity pull request #5593
Opened 2021-03-01 21:14 UTC by ElDonad

Hi there ! 
This small PR aims to allow files to be open from the terminal at a specific line number. I tried to do it by making use of the URL query functionnality, since it is not usable in a traditionnal file path. That's probably a bad idea, but I wanted to give it a try. 

I also implemented the integration for the small `bt` utility, since it's what motivated me to do it in the first place. 

(_I'd like to take this opportunity to thank you guys, and @awesomekling for your brillant work on this operating system. I'm a long time follower and enjoyer of the youtube coding sessions, and always wanted to add my little brick of my own, within the boundaries of my capacities...)_

2021-03-02 09:18 UTC, ElDonad commented
Also, food for tough, if this proof of concept doesn't seems unreasonable : 

- The URL parsing probably should be deferred to the software itself. This way we could scale the concept more easily to other file formats (maybe a page_number for a word document, or a function_name for a js file ? dunno)
- My main concern is that this would be in essence a parallel system to the traditionnal launch arguments, albeit associated with a file type instead of a specific application. Maybe a bad idea in itself. Or we could come up with some kind of mapping between url query parameters and CLI parameters...

2021-03-08 18:15 UTC, linusg requested changes

2021-03-08 18:15 UTC, linusg commented on Userland/Services/LaunchServer/Launcher.cpp
> +        if (pair[0] == "line_number") {
```suggestion
        if (pair.size() == 2 && pair[0] == "line_number") {
```

otherwise this would crash with something like "?line_number="

2021-03-08 18:15 UTC, linusg commented on Userland/Services/LaunchServer/Launcher.cpp
> +                additional_parameters.prepend(String::format("-l%i", *line));
Please use `String::formatted()` in new code, also I think `value()` is more clear than `operator*()` here

```suggestion
                additional_parameters.prepend(String::formatted("-l {}", line.value()));
```

2021-03-15 08:12 UTC, ElDonad commented
Thanks for the review ! Sorry for the long wait, I didn't see notice it happened until this morning (still quite new at github collaboration). So, namespace mention dropped, const references where possible, and explicit function names over overloaded operators. Will try to remember that for the next time !

2021-03-15 09:11 UTC, linusg approved these changes

2021-03-15 15:08 UTC, merged