LibGUI: Fix TextEditor crash when double clicking an empty line.
SerenityOS/serenity pull request #5997
Opened 2021-03-28 13:14 UTC by Kubiisek

I also reduced the number of calls to `TextEditor::did_update_selection` - not sure if I should make a second PR.

2021-03-28 21:08 UTC, linusg commented
@Kubiisek you have a typo in the description, #5997 is this PR itself and should be #5995.

2021-03-29 07:11 UTC, awesomekling commented
Please wrap your commit messages at 72 characters.

2021-03-29 10:03 UTC, Kubiisek commented
My bad, it looked like the IDE did it for me. Anyway it's fixed.

2021-03-30 09:37 UTC, Kubiisek commented
Any other feedback?

2021-03-31 22:02 UTC, awesomekling requested changes

2021-03-31 22:02 UTC, awesomekling commented on Userland/Libraries/LibGUI/TextEditor.cpp
> +    dbgln("select_all");
This seems accidental :)

2021-03-31 22:02 UTC, awesomekling commented on Userland/Libraries/LibGUI/TextEditor.cpp
> + * Copyright (c) 2018-2021, Andreas Kling <kling@serenityos.org>
Please don't modify other people's copyright lines. Feel free to add your own instead :)

2021-03-31 22:02 UTC, awesomekling commented on Userland/Libraries/LibGUI/TextDocument.cpp
> +            return String("");
The idiomatic way to get an empty `String` is usually `String::empty()` :)

2021-04-01 11:43 UTC, Kubiisek commented
Thanks, I fixed all of your issues :+1:

2021-04-02 21:17 UTC, awesomekling requested changes
Please observe the [contribution guidelines](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md), specifically
>Squash your commits when making revisions after a patch review.

2021-04-02 21:17 UTC, awesomekling commented on Userland/Libraries/LibGUI/TextEditor.cpp
> + * 2021, the SerenityOS developers
Please use the same format as other files in the project:

```
 * Copyright (c) 2018-2020, Andreas Kling <kling@serenityos.org>
 * Copyright (c) 2021, the SerenityOS developers
```

2021-04-04 08:06 UTC, Kubiisek commented
I'm really sorry for the force pushes. Thank you for your patience with me.

2021-04-21 22:17 UTC, linusg commented
Already fixed by #6537.

2021-04-21 22:17 UTC, closed without merging