HackStudio: Actions on project tree selections improved
SerenityOS/serenity pull request #6034
Opened 2021-03-31 01:08 UTC by AlgotAxelzon

Creating a file while having a file or directory selected will now
create the file in the selected directory, or in same directory as
a selected file.
Creating directories works the same way.

Right click -> Open on selected files will now open the selected files.

Deleting selected files will now delete the selected files.

As suggested by sagefarrenholz this was accomplished by adding a private
function HackStudioWidget::selected_file_paths() that returns a
Vector<LexicalPath> of the current project tree selection.

(Fixes #5935)

This is my first contribution so there is probably something that is in need
of change!

2021-04-03 05:59 UTC, itamar8910 requested changes
Thank you for contributing and improving HackStudio!
Please see my comments.

Also, a small nitpick regarding the commit message, we prefer to use imperative language in commit messages. So a more appropriate title for the commit message would be: `HackStudio: Make actions with project tree selections work as expected `

2021-04-03 05:59 UTC, itamar8910 commented on Userland/DevTools/HackStudio/HackStudioWidget.h
> +    Vector<LexicalPath> selected_file_paths() const;
`LexcialPath` is meant to be used as a utility class for parsing & validation paths, not really as a storage class for paths.
For simply storing paths & passing them around, please prefer to use a simple `String` class.

2021-04-03 05:59 UTC, itamar8910 commented on Userland/DevTools/HackStudio/HackStudioWidget.h
> +    Vector<LexicalPath> selected_file_paths() const;
Also, after adding `selected_file_paths`, it seems that `selected_file_names` is no longer used. If this is the case, we can delete it.

2021-04-03 05:59 UTC, itamar8910 commented on Userland/DevTools/HackStudio/HackStudioWidget.cpp
> +            path_from_parent.appendff("{}/{}", parent_or_invalid.data().as_string(), sub_path);
Instead of using a `StringBuilder` here, we can simply use `String::formatted`

2021-04-03 05:59 UTC, itamar8910 commented on Userland/DevTools/HackStudio/HackStudioWidget.cpp
> +        StringView sub_path_sv(sub_path);
`StringView` can be implicitly constructed from a `String`, so there's no need to create the `sub_path_sv` local variable, you can simply do `LexicalPath path(sub_path)`

2021-04-03 05:59 UTC, itamar8910 commented on Userland/DevTools/HackStudio/HackStudioWidget.cpp
> +            builder.appendff("{}/{}", dir_path, directory_name);
We can use `String::formatted` here

2021-04-07 20:01 UTC, AlgotAxelzon commented
Thanks a lot for the feedback, it made me learn a few things!
I have made changes related to your comments; using less StringBuilders, using Strings to pass around paths, and removed unused functions.

After a bit of struggling I also managed to make the git history look decent 😉 

Please tell me if there is something more that is needed to be done.

2021-04-09 05:07 UTC, itamar8910 approved these changes
Okay, looks good to me :+1:

2021-04-09 07:32 UTC, merged