LibCore: add StandardPaths::documents_directory
SerenityOS/serenity pull request #6268
Opened 2021-04-12 14:14 UTC by ZikiFlicky

2021-04-12 15:47 UTC, awesomekling requested changes
This is not used by anything? Please don't add dead code. Instead, add this in a PR that uses it for something.

2021-04-12 15:59 UTC, ZikiFlicky commented
I was planning to add a Documents shortcut in the left toolbar in the FilePicker widget that will use the method, but I wasn't sure if it belongs in this pull request. Sorry for not mentioning it 😬

2021-04-13 09:10 UTC, ZikiFlicky commented
I added Documents and Downloads folders to FilePicker. can you review the changes?

2021-04-13 11:48 UTC, Dexesttp commented on Userland/Libraries/LibGUI/FilePicker.cpp
> +            documents_button.set_checked(true);
You will need to uncheck these buttons when another path is selected, which is done right below :) Just add the `downloads_button.set_checked(false);` and `documents_button.set_checked(false);` to the else branch.

2021-04-17 18:16 UTC, closed without merging