Kernel: Added sysexits.h
SerenityOS/serenity pull request #6435
Opened 2021-04-18 02:12 UTC by panos

Created for compatibility purposes with programs primarily designed for BSD-like systems.

For example, **imgcat** (see: #6412), which currently doesn't work on the system, uses these exit codes.

2021-04-18 02:27 UTC, panos commented
Gah, my text editor keeps fooling me.

2021-04-18 03:45 UTC, panos commented
`clang-format` seems to think it's okay. I also added my own copyright notice, as the CONTRIBUTING.md file recommended.

Based on my experience with porting software for the Haiku operating system, porting software to Serenity will eventually require adding some BSD compatibility stuff, bigger or smaller, sooner or later, alongside with potentially pushing patches upstream. I'll reiterate that the header file was modeled after documentation in the FreeBSD man pages.

2021-04-18 08:50 UTC, awesomekling requested changes
If you want this to be accessible to userspace, it needs to be in `Userland/Libraries/LibC/`, not `Kernel`.

Also headers should have `#pragma once`

2021-04-18 09:30 UTC, panos commented
> If you want this to be accessible to userspace, it needs to be in `Userland/Libraries/LibC/`, not `Kernel`.
> 
> Also headers should have `#pragma once`

Understood, expected that to be a bit incorrect, thanks for the guidance!

2021-04-18 09:33 UTC, panos commented
> Also headers should have `#pragma once`

I'm a bit way too accustomed to C and I just assumed that all I had to do was do away with the `#ifndef` conditions, still learning!

2021-04-19 10:26 UTC, emanuele6 requested changes

2021-04-19 10:26 UTC, emanuele6 commented on Userland/Libraries/LibC/sysexits.h
> +
```
Running Meta/check-newlines-at-eof.py... 
Files that have blank lines at the end: Userland/Libraries/LibC/sysexits.h
[FAIL]: Meta/check-newlines-at-eof.py
```

2021-04-19 10:31 UTC, emanuele6 commented
This is a LibC change; why is your commit prefixed with `Kernel: `?

2021-04-19 15:14 UTC, panos commented
> oh, you must have forgot to change it.

Yeah... I'm juggling around with a lot of pull requests, I'll get right on it.

2021-04-19 16:27 UTC, merged