HackStudio: Detection of externally deleted files
SerenityOS/serenity pull request #6708
Opened 2021-04-28 14:03 UTC by iCristalrope

Each time the window of Hackstudio becomes active, Hackstudio will check
if the files in `m_open_files_vector` or in the editors have been deleted.
If so, the deleted files will be removed from the open files list and
editors that showed those files will instead show another open file or
show a default editor.

Closes SerenityOS#6632

2021-04-28 17:59 UTC, awesomekling requested changes
This sort of thing should be done lazily using file watchers, not forcibly every time we activate the HackStudio window.

2021-04-30 13:34 UTC, itamar8910 requested changes
Thanks for working on this. Please a comment i left.

2021-04-30 13:37 UTC, itamar8910 commented on Userland/DevTools/HackStudio/HackStudioWidget.cpp
> +    }
Let's do the `lstat` check before calling `handle_external_file_deletion`.
Currently `handle_external_file_deletion` gets called whenever a file changes.

2021-04-30 13:39 UTC, itamar8910 commented on Userland/DevTools/HackStudio/HackStudioWidget.cpp
> +    }
Also, let's explicitly check if `errno` is `ENOENT` to determine that the file was deleted.

2021-05-01 10:55 UTC, itamar8910 approved these changes
Okay, looking good.

2021-05-01 11:39 UTC, merged