Grep fixes
SerenityOS/serenity pull request #6738
Opened 2021-04-29 17:33 UTC by r-paiva

Fixes #5907.

Two issues are fixed with this commit.

1. When grep reads from stdin, it discarded the last character of a line. b3f6313 

- On lines with \n, this worked fine.
- On lines without \n, it discarded the last character of that line, which caused grep to fail to match.

2. When grep searches recursevely, it uses IODevice to buffer the data in. f2bd874

- IODevice::can_read_line only buffers 1024 bytes at a time 
    - If a line is bigger than 1024 (with or without a \n) can_read_line would return false.
- IODevice::can_read_line At eof it only returns true if data has a \n
    - if a line at the end of a file does  not have a \n, can_read_line would return false, which I don't think was the intended behaviour.

  Changed IODevice::can_read_line to buffer data 1024 bytes at time until it either finds a \n in the buffered data, or,
  EOF is reached.

before and after:

![bad png](https://user-images.githubusercontent.com/82210061/116593379-edde2500-a918-11eb-8185-ffc96705a91f.png)
![good png](https://user-images.githubusercontent.com/82210061/116593382-ee76bb80-a918-11eb-9c60-b3e542d746c6.png)

I've never written anything in C++ before, and it's my first time contributing, so I might be missing something.
Thanks!

2021-05-09 16:36 UTC, linusg requested changes
- The addition of `contains_in_range` should be in its own commit. Please also add a test case in `TestVector.cpp`.
- Please treat spelling and punctuation more care - see https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#human-language-policy. Specifically:
  - `if a line` -> `If a line`
  - `ended wihtout` -> `ended without`
  - `eof` -> `EOF`
  - `fixes` -> `Fixes`
- Please follow the existing pattern for commit message pefixes - instead of `Libraries-IODevice`, do something like `LibCore: Let IODevice::can_read_line() buffer until \n or EOF`

2021-05-09 16:36 UTC, linusg commented on Userland/Libraries/LibCore/IODevice.cpp
> +        // populate buffer until a \n is found or we reach eof.
Comments should be complete sentences:

```suggestion
        // Populate buffer until a newline is found or we reach EOF.
```

2021-05-09 16:36 UTC, linusg commented on Userland/Libraries/LibCore/IODevice.cpp
> +        // search new data for a \n
This done doesn't add any value.

```suggestion
```

2021-05-10 22:18 UTC, r-paiva commented on Userland/Libraries/LibCore/IODevice.cpp
> +        // populate buffer until a \n is found or we reach eof.
done

2021-05-20 21:50 UTC, alimpfard approved these changes
This seems okay.
I'd personally have switched the backing buffer mechanism to `AK::DuplexMemoryStream` to avoid allocating possibly a really big contiguous buffer, but perhaps that can be another commit/PR since it doesn't really have anything to do with fixing line buffering.

2021-05-20 21:53 UTC, merged