[WIP] LibVT: Color scheme support
SerenityOS/serenity pull request #7525
Opened 2021-05-28 14:59 UTC by BertalanD

This PR introduces support for various terminal color schemes. In order to implement it, the following things need to be done:

- [x] Add a `Color` class that lets us store the various color types (RGB, 8-bit indexed color, ANSI named color)
- [ ] Add color state to `TerminalWidget`
- [ ] Add some color themes to `/res/terminal_colors` (I'm open to suggestions for a nicer name of the directory)
- [ ] Add a GUI color scheme switcher to `/bin/Terminal`.

2021-05-28 20:01 UTC, BertalanD commented
Functionally, this should be ready to go, but there is an annoying UI bug. The combo box renders underneath the window.

![image](https://user-images.githubusercontent.com/25866827/120036238-56d7bc00-bfef-11eb-8ba5-43e888d7eed0.png)

2021-06-02 13:58 UTC, BertalanD commented
Can I get a merge on this? 

I'm not sure about why the combo box is buggy, but that's probably not related to any of the code I modified.

Currently, only the default color scheme is included, but I could commit the Solarized and Gruvbox dark themes that I have on my computer. They are under MIT license, so we can pull them in with proper attribution.

2021-06-02 19:26 UTC, linusg commented
> Can I get a merge on this?

The title still says WIP, and those PRs usually don't get reviewed. :)

2021-06-02 20:53 UTC, BertalanD commented
Can't believe I left it in the title. Thanks for still noticing the comment.

2021-06-02 21:48 UTC, linusg requested changes
That's pretty cool, nice work!

2021-06-02 21:48 UTC, linusg commented on Userland/Libraries/LibVT/TerminalWidget.cpp
> +    if (name.contains('\\')) {
Pretty sure you can have a backslash in Unix filenames, this ain't Windows :)
Probably meant to use a forward slash here?

2021-06-02 21:48 UTC, linusg commented on Userland/Libraries/LibVT/TerminalWidget.cpp
> +    auto color_config = Core::ConfigFile::open(String::formatted("/res/terminal_colors/{}.ini", name));
Let's not use an underscore in the path here, that seems pretty uncommon across the system. `terminal-colors` looks less out of place.

2021-06-03 16:49 UTC, linusg commented on Userland/Libraries/LibVT/Color.h
> +            return *this;
Please add curly braces to all branches if at least one needs them.

2021-06-04 08:02 UTC, merged