LibJS: Add the Number.{MAX, MIN}_VALUE constants
SerenityOS/serenity pull request #7796
Opened 2021-06-04 21:59 UTC by IdanHo

This makes 53 new test262 test cases pass.

2021-06-04 22:05 UTC, Hendiadyoin1 commented
Is the Numer.min value supposed to be -Max or essentially Epsilon?

Make sure You use the correct one, last time I checked, the names of the floatingpoint numeric limits were confusing

2021-06-04 22:09 UTC, IdanHo commented
> Is the Numer.MIN_VALUE supposed to be -Max or essentially Epsilon?

`The value of Number.MIN_VALUE is the smallest positive value of the Number type, which is approximately 5 × 10-324.`

2021-06-04 22:33 UTC, Hendiadyoin1 commented
Ok then never MINd

2021-06-05 00:52 UTC, linusg requested changes

2021-06-05 00:52 UTC, linusg commented on Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
>      P(MIN_SAFE_INTEGER)                      \
```suggestion
    P(MAX_VALUE)                             \
    P(MIN_SAFE_INTEGER)                      \
    P(MIN_VALUE)                             \
```

2021-06-05 00:56 UTC, IdanHo commented on Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
>      P(MIN_SAFE_INTEGER)                      \
whoops, fixed!

2021-06-05 01:38 UTC, merged