LibJS: Add support for `break` opcodes
SerenityOS/serenity pull request #7915
Opened 2021-06-08 12:24 UTC by ryangjchandler

Adds support for `break` statements inside of `do/while`, `while` and `for`.

There is a slight issue when breaking inside of `if` statements, e.g.

```js
i = 0;

while (true) {
    i += 1;

    if (i > 2) {
        break;
    }
}
```

The `break` here doesn't work right now, but I'll investigate this separately (or somebody else can).

2021-06-08 16:56 UTC, alimpfard commented
If you feel like cheating (lol), you can take a look at https://github.com/alimpfard/serenity/commits/foob
The first two commits there fix your `if` problem, and the last one fixes another (irrelevant) issue :P

2021-06-08 17:12 UTC, ryangjchandler commented
@alimpfard Will take a look shortly.

2021-06-08 17:41 UTC, ryangjchandler commented
Okay, I've made some extra changes with thanks to @alimpfard. The issue with `break` / `continue` inside of an empty `if` statement is now resolved.

2021-06-08 17:48 UTC, linusg requested changes
Please squash the fixup commits.

2021-06-08 17:52 UTC, ryangjchandler commented
@linusg Done.

2021-06-08 18:44 UTC, linusg commented
> Done

The second commit fixes something introduced in the first commit. Those should not be separate.

2021-06-08 18:48 UTC, linusg commented on Userland/Libraries/LibJS/Bytecode/Generator.cpp
> +#include <LibJS/Bytecode/Register.h>
This include is added in the first commit and then ordered properly in the fourth, please avoid changes like these across commits.

2021-06-08 19:10 UTC, ryangjchandler commented
Okay, haven't got time to sort this out tonight. Will sort tomorrow.

2021-06-09 09:47 UTC, ryangjchandler commented
Since #7934 has been merged, it's going to be easier to re-implement this from `master`. I won't have much time to do this today so if somebody else wants to take it, feel free.

2021-06-09 09:47 UTC, closed without merging