LibJS: Add the Set built-in object
SerenityOS/serenity pull request #7928
Opened 2021-06-08 21:21 UTC by IdanHo

This fixes 175 test262 test cases :^)

2021-06-08 22:06 UTC, linusg requested changes

2021-06-08 23:37 UTC, IdanHo commented on Userland/Libraries/LibJS/Runtime/SetIteratorPrototype.cpp
> +        vm.throw_exception<TypeError>(global_object, ErrorType::NotAn, "Set Iterator");
fixed

2021-06-09 08:03 UTC, linusg commented
@IdanHo conflicts...

2021-06-09 09:40 UTC, IdanHo commented
> @IdanHo conflicts...

sorry, fixed.

2021-06-09 10:48 UTC, merged