Meta: ConfigureComponents utility for CMake command generation
SerenityOS/serenity pull request #8168
Opened 2021-06-20 13:17 UTC by MaxWipfli

This adds a utility program called `ConfigureComponents`. It can be used to easily configure which system components should be built. It is in essence a CMake command generator. It uses `whiptail(1)` for user interaction.

First, it allows you to specify which base configuration to use:
* Required
* Recommended
* Full
* Current (the configuration currently in use)

All of those can then be customized by manually adding or removing single components. In the end, the CMake command will be generated and shown to the user, after which it is executed. At the end, the program will run `ninja clean` and `rm -rf Root` to remove old build artifacts from components which may not be built anymore.

Due to the limitations of `whiptail(1)`, required components can still be manually unchecked, although they are marked with `[required]` and will be built anyway. A warning about this will be shown to the user if they deselect any required components.

A custom target has been added to `CMakeLists.txt`, which means that `ninja configure-components` will build and run the utility.

In the second commit, documentation has been added for the utilities in the build instructions.

This builds on top of #8066, which added support for the component configuration in the first place.

**Note:** I have no idea if this is a sensible workflow, and if I chose the correct CMake commands to specify all of this. Feedback welcome!

2021-06-20 14:36 UTC, gunnarbeutner requested changes

2021-06-20 14:36 UTC, gunnarbeutner commented on Meta/CMake/ConfigureComponents/main.cpp
> +            warnln("\e[31mError:\e[0m Could not exectue 'whiptail', maybe it isn't installed.");
```suggestion
            warnln("\e[31mError:\e[0m Could not execute 'whiptail', maybe it isn't installed.");
```

2021-07-02 20:28 UTC, IdanHo commented on Meta/CMake/ConfigureComponents/main.cpp
> +    if (!current_working_directory->ends_with("Build/i686")) {
Any chance we can make this non-i686 specific?

2021-07-06 17:28 UTC, gunnarbeutner requested changes
Ideally we'd also have support for non-i686 architectures, but that can wait until another PR. :)

2021-07-06 17:28 UTC, gunnarbeutner commented on Meta/CMake/ConfigureComponents/main.cpp
> +    delete cwd;
```suggestion
    free(cwd);
```

2021-07-06 17:59 UTC, MaxWipfli commented
> Ideally we'd also have support for non-i686 architectures, but that can wait until another PR. :)

I removed the hardcoded `Build/i686`, it now just expects `Build/*`.

2021-07-06 19:54 UTC, merged