KeyboardSettings+Kernel: Setting to enable Num Lock on login
SerenityOS/serenity pull request #8417
Opened 2021-07-03 23:49 UTC by ForLoveOfCats

It was bothering me having to enable the Num Lock on every boot in order to use the number pad to input numerals so this is intended to address that :^)

Adds a new setting to KeyboardSettings which toggles whether or not the Num Lock is enabled on login. By default it is set to true and the number pad will input numerals. This config file is stored per-user in the user's `.config` directory under the KeyboardSettings' app name.

I'm not entirely happy with this having its own dedicated syscall to modify the Num Lock status but I'm not sure if there is another way for a userland application to ask the KeyboardDevice to change the status. One alternative may be to move the on-login logic into the kernel?

2021-07-04 08:26 UTC, gunnarbeutner requested changes

2021-07-04 08:26 UTC, gunnarbeutner commented on Userland/Services/KeyboardPreferenceLoader/main.cpp
> +    syscall(SC_set_num_lock_on, enable_num_lock);
Can you add a syscall wrapper for this to `LibC/serenity.{h,cpp}`?

2021-07-04 08:26 UTC, gunnarbeutner commented on Kernel/Syscalls/num_lock.cpp
> +KResultOr<FlatPtr> Process::sys$set_num_lock_on(bool on)
Maybe this should just be called `sys$set_num_lock`.

2021-07-04 08:26 UTC, gunnarbeutner commented on Userland/Applications/KeyboardSettings/main.cpp
> +    auto& num_lock_checkbox = root_widget.add<GUI::CheckBox>("Enable Num Lock on login:");
```suggestion
    auto& num_lock_checkbox = root_widget.add<GUI::CheckBox>("Enable Num Lock on login");
```

2021-07-05 02:21 UTC, ForLoveOfCats commented on Userland/Applications/KeyboardSettings/main.cpp
> +    auto& num_lock_checkbox = root_widget.add<GUI::CheckBox>("Enable Num Lock on login:");
Woops :sweat_smile:

2021-07-05 04:19 UTC, merged

2021-07-05 11:22 UTC, bugaevc commented
Why a whole separate syscall, and not a file in `/proc` / `/sys`?