Tests: EnumBits has_flags should require all flags present
SerenityOS/serenity pull request #8724
Opened 2021-07-13 15:20 UTC by timmot

2021-07-13 22:01 UTC, bgianfo approved these changes
Nice catch, thanks for fixing this!

2021-07-13 22:48 UTC, bgianfo commented
As discussed on discord, it looks like this now fails the test: 

```
$  ./Meta/Lagom/TestEnumBits_lagom
...
Running test 'has_flag'.
FAIL: ../../Tests/AK/TestEnumBits.cpp:67: EXPECT(has_flag(intro, VideoIntro::Friends)) failed
FAIL: ../../Tests/AK/TestEnumBits.cpp:68: EXPECT(!has_flag(intro, VideoIntro::Well)) failed
FAIL: ../../Tests/AK/TestEnumBits.cpp:69: EXPECT(!has_flag(intro, VideoIntro::CompleteIntro)) failed
Failed test 'has_flag' in 0ms
Finished 8 tests and 0 benchmarks in 0ms (0ms tests, 0ms benchmarks, 0ms other).
Out of 8 tests, 7 passed and 1 failed.
```

That's probably why the state machine generator is now failing in the build 😄

2021-07-13 22:55 UTC, bgianfo requested changes

2021-07-13 22:55 UTC, bgianfo commented on AK/EnumBits.h
> +        return static_cast<Type>(value & mask) != static_cast<Type>(mask); \
As discussed on discord, this should be: 

```suggestion
        return static_cast<Type>(value & mask) == static_cast<Type>(mask); \
```

2021-07-13 23:00 UTC, timmot commented
It appears that more things are dependent on the previous functionality, on boot we get the grey wallpaper and mouse but no windows, icons, or the taskbar.

2021-07-14 06:26 UTC, kleinesfilmroellchen approved these changes

2021-07-14 11:41 UTC, awesomekling commented
The commit messages are very confusing, they seem to be describing a problem(?)
"EnumBits has_flag should require all flags present" doesn't tell us what the commit is actually doing.

2021-07-14 12:09 UTC, timmot commented
I have updated the commit messages, let me know if you'd like more clarity.

2021-07-16 09:49 UTC, merged