LibJS: Optimise source_location_hint and add max hint length
SerenityOS/serenity pull request #8839
Opened 2021-07-17 19:37 UTC by ElectrodeYT

This replaces the "replace" calls in source_location_hint with a GenericLexer. It also adds a maximum size of 80, which if reached will cause it to return nothing.

While I did not measure it extremely accurately, it decreases the load time of Github (to a first visible change in the window from white) by about 30-50% (depending on exactly when i started the profiler)

2021-07-18 16:23 UTC, linusg requested changes
> It also adds a maximum size of 80, which if reached will cause it to return nothing.

So if I have a syntax error in column 81 it won't show me? That seems like a major downgrade, we're not doing that.

2021-07-18 16:28 UTC, ElectrodeYT commented
> > It also adds a maximum size of 80, which if reached will cause it to return nothing.
> 
> So if I have a syntax error in column 81 it won't show me? That seems like a major downgrade, we're not doing that.

A reasonable alternative would be a flag that disables or limits the error hints. This is slowing the browser down significantly, despite that, most of the time, this is being put straight into /dev/null.

2021-07-18 16:31 UTC, ElectrodeYT commented
By the way, this only affects the hint. The error would still be shown, with line and column.

2021-07-18 16:34 UTC, linusg commented
> A reasonable alternative would be a flag that disables or limits the error hints. This is slowing the browser down significantly, despite that, most of the time, this is being put straight into /dev/null.

Sure, but the browser is only use case - the standalone js REPL/interpreter should not suffer from this change. Optionally (fully) disabling hints seems useful.

> By the way, this only affects the hint. The error would still be shown, with line and column.

I know, but the hint is useful. :^)

2021-07-18 16:36 UTC, ElectrodeYT commented
I know its useful, but (correct me if I'm wrong - I have never really coded much JS) I don't think that, aside from minified scripts, lines get this long.

> Optionally (fully) disabling hints seems useful.

Honestly, I would just disable the hint if it's too long instead of completely disabling it, although that could maybe also be a config option (maybe also with maximum length?)

2021-07-18 16:46 UTC, ElectrodeYT commented
Converted to draft as I'm rewriting the the function again and will try to add a flag for the browser to disable hints

2021-07-19 16:06 UTC, ElectrodeYT commented
This should only disable hints for LibWeb - other applications that don't use LibWeb should not be affected.
The algorithm itself is better and does shave off a few seconds of the load time of GitHub, but with this, the load time was about halfed.

2021-07-19 17:12 UTC, ElectrodeYT commented
That should be correct now

2021-07-19 17:22 UTC, linusg commented
In the title, yep, but it's still wrong in the body. Please be just as careful with writing commits messages as you are with writing code :)

2021-07-19 17:24 UTC, ElectrodeYT commented
Didn't notice that. I might be slightly stupid... Should be fixed there now.

I wonder if i missed it somewhere else as well?

2021-07-19 17:25 UTC, linusg approved these changes
Thanks!

2021-07-19 17:40 UTC, ElectrodeYT commented
Check failure is a time out

2021-07-20 14:21 UTC, merged

2021-07-20 15:41 UTC, trflynn89 commented on Userland/Libraries/LibJS/Parser.h
> +            GenericLexer lexer(source_string);
I know this was already merged, but is there a reason this can't avoid a string creation?
```c++
GenericLexer lexer(source);
```