AK+LibJS+Meta: Implement and use Unicode case folding
SerenityOS/serenity pull request #8985
Opened 2021-07-24 18:15 UTC by trflynn89

This adds a Lagom utility to `Meta/Unicode` for parsing [UnicodeData.txt](https://www.unicode.org/Public/13.0.0/ucd/UnicodeData.txt) and generating C++ to hold parsed data.

UnicodeData.txt is a pretty large file. So rather than committing that file to git and generating the C++ into `Build/i686/AK`, this utility is meant to be run manually to generate the C++ directly into `AK` on an as-needed basis. But if we want to commit UnicodeData.txt to git, then running this utility could be part of the normal build process.

A regex/JS feature I'm hoping to get from this process is Unicode property escapes - there's about 550 test262 tests up for grabs there :)

2021-07-24 18:18 UTC, alimpfard commented
Let's...not include the generated file perhaps?
you could make cmake download the unicode data file and generate the file?

2021-07-24 18:19 UTC, linusg commented
> But if we want to commit UnicodeData.txt to git, then running this utility could be part of the normal build process.

I'm strongly against adding any large/external files to the repo, that can (and should) be downloaded (or copied into the build dir manually if working offline) as part of the build process. Related: #5627

2021-07-24 18:22 UTC, linusg requested changes
Let's generate `AK/UnicodeData.cpp` at build time and remove the committed file.

2021-07-24 18:32 UTC, IdanHo reviewed
Great work on this, this will make adding more unicode support to LibJS and LibGfx much easier :) As linus and ali already suggested, UnicodeData.txt should be downloaded and cached on compile time similarly to PCI/USB IDs, and the source files should be generated at that point as well similarly to IPC or LibWeb bindings.

2021-07-24 18:32 UTC, IdanHo commented on Meta/Unicode/main.cpp
> +    generator.set("size", String::formatted("{}", unicode_data.code_point_data.size()));
`String::number()` would be nicer here

2021-07-25 19:20 UTC, trflynn89 commented
Closing in favor of #9004 (was easier to just start over on a fresh branch) :)

2021-07-25 19:20 UTC, closed without merging