LibChess: Early check of legal move
SerenityOS/serenity pull request #8995
Opened 2021-07-24 22:50 UTC by blishko

One of the conditions for legal move is that the target square is not
occupied by a piece of the same color as the moving piece.

Instead of checking this for each piece separately at the end, we can
check this at the beginning and avoid more expensive checks.

2021-07-25 15:01 UTC, Petelliott requested changes

2021-07-25 16:22 UTC, blishko commented on Userland/Libraries/LibChess/Chess.cpp
> +        // attempted move to a square occupied by a piece of the same color
Fixed. I was copying the style of the comments above the change, did not realize it was not the correct one.

2021-07-25 16:23 UTC, Petelliott approved these changes

2021-07-25 16:26 UTC, blishko commented on Userland/Libraries/LibChess/Chess.cpp
> +    if (piece.color == get_piece(move.to).color)
True, good point. I have moved the check for castling move above the new check in order to still allow this style of castling.

2021-07-26 16:36 UTC, blishko commented
I had to rebase because some unrelated test timed out in CI.

2021-07-26 21:53 UTC, merged