Update README to 64bit
SerenityOS/serenity pull request #9137
Opened 2021-07-31 20:26 UTC by GamingCrafthd

Since Serenity supports x64 now, I made a PR to update the README accordingly.

2021-07-31 21:02 UTC, yegor-github approved these changes

2021-07-31 22:02 UTC, ADKaster commented
You'll need to amend your commit and force push it with a fixed title (and hopefully description) In order for the CI linter to approve of the change.

something like:
```
git commit --amend
< change commit tile to something like : Meta: Add x86_64 to supported architectures in README >
git push -f my-remote
```

Note that you can't do this from the GitHub website UI.

2021-08-01 09:54 UTC, awesomekling commented
Please use x86_64 consistently instead of mixing x64 and x86_64

2021-08-01 23:06 UTC, awesomekling commented
Please observe the [contributing guidelines](https://github.com/SerenityOS/serenity/blob/3dd40535c1488e6437923fa5e90f73d3eeb9e108/CONTRIBUTING.md#code-submission-policy), specifically:
> Squash your commits when making revisions after a patch review.

2021-08-02 15:18 UTC, awesomekling requested changes
When squashing commits, please edit the resulting commit message so it looks good and doesn't repeat itself.

There is no reason to keep both of the commit messages after doing a squash.

2021-08-02 15:18 UTC, awesomekling commented on README.md
> +Graphical Unix-like operating system for x86 and x86_64 computers.
This change is not necessary. "x86 computers" includes both 32-bit and 64-bit CPUs.

2021-08-03 10:24 UTC, merged