HackStudio: Fix issues with retaining state of previous project after opening a different one
SerenityOS/serenity pull request #9185
Opened 2021-08-02 23:35 UTC by donaghylennon

Previously when a you opened a different project or created a new one, many of the widgets within HackStudio would not update to reflect this. This pull request fixes many of these issues, as well as fixing a bug with GitWidget in particular, which would cause HackStudio to crash when trying to create a git repository after switching to a different project.

2021-08-03 00:00 UTC, ADKaster commented
Haven't looked at these changes but, what is the behavior when you have unsaved changes and you open a different project?

I think the desired behavior would be it prompts you to  save the file(s) with a dialog, and if you cancel we don't open the new project.

2021-08-03 00:23 UTC, donaghylennon commented
It currently just silently opens the new project without warning, it also does this when you close HackStudio. I just checked and there is some code to do this, it's used when you have unsaved changes and try to build. It looks like it'd be pretty easy to use that for both these cases, would it make sense to include them in this pull request?

2021-08-03 03:46 UTC, ADKaster commented
If you wanna add it then go for it, otherwise we can open an issue to track it for another PR

2021-08-03 08:07 UTC, donaghylennon commented
I did a bit of digging and it turns out it's supposed to warn if you have unsaved changes before closing HackStudio as well as before building, but for some reason this code is never called, it seems like this got broken at some point (before my changes). Looks like this will need to be fixed before I try to use it myself, I'll try to get to the bottom of it.

2021-08-03 20:08 UTC, donaghylennon commented
@ADKaster I figured out what it was, the editor's on_change callback was being overwritten so that the GML preview could be updated every time you changed something. The best way I could see to fix this right now was to make it update the preview when you save instead, but I'm sure this could be improved on, maybe doing something similar to how the ToDo entries are updated.

2021-08-14 14:59 UTC, itamar8910 requested changes
These are some really solid improvements :+1: 
Please see my comments.

2021-08-14 14:59 UTC, itamar8910 commented on Userland/DevTools/HackStudio/HackStudioWidget.cpp
> +        [&filename](const String& element) { return element == filename; });
Please use east const

2021-08-14 14:59 UTC, itamar8910 commented on Userland/DevTools/HackStudio/HackStudioWidget.cpp
> +void HackStudioWidget::close_file(const String& filename)
Perhaps `close_file_in_all_editors` would be a better name?

2021-08-14 14:59 UTC, itamar8910 commented on Userland/DevTools/HackStudio/Git/GitWidget.h
> +    void change_repo(const LexicalPath& repo_root);
Please use east const

2021-08-14 14:59 UTC, itamar8910 commented on Userland/DevTools/HackStudio/HackStudioWidget.cpp
> -    current_editor().on_change = [this] { update_gml_preview(); };
IMO updating the GML preview on every change is a feature we want to have.

How about changing the API of the `EditorWrapper` and allow registering a callback function
that would get called on every editor change?
Then `EditorWrapper` could still internally take care of marking the document as dirty, and `update_gml_preview()` can get called regardless.

2021-08-14 17:24 UTC, donaghylennon commented
@itamar8910 I made the changes you asked for, now the GML preview updates on every change and the document is correctly marked as dirty :)

2021-08-20 07:05 UTC, itamar8910 approved these changes
LGTM :)

2021-08-22 08:30 UTC, merged