LibGUI: Add a modifier filter to disable Action shortcuts
SerenityOS/serenity pull request #9300
Opened 2021-08-09 12:38 UTC by metmo

This allows a widget to disable actions with certain modifiers while the widget is focused. The main use is TextEditor which previously would miss <Key> & Shift+<Key> keypresses when an action used the respective keys as shortcuts.
Exceptions can be added for keys we always need to trigger actions, like F1 or Del.

2021-08-09 19:04 UTC, awesomekling commented
Can we instead simply process key events *before* looking for an action?
Events have an `accepted` flag that tells us if some widget used it.
If event processing concludes with the event still unaccepted, we look for an action *then*.
Or maybe I am missing something here?

2021-08-09 19:46 UTC, metmo commented
I think I follow along, the reason I put the processing _after_ looking for an action was to reduce the number of lookups and only check for matches when an action _would_ be triggered, since most of the key events won't trigger an action.
Are you suggesting moving the triggering of the action down the event loop?

2021-08-09 19:52 UTC, metmo commented
Or are you suggesting sending the key event to `Widget::key_down_event()` for the focused widget before looking for an action?

2021-08-09 20:47 UTC, awesomekling commented
> Or are you suggesting sending the key event to `Widget::event()` for the focused widget before looking for an action?

Yes, exactly :)

2021-08-10 21:17 UTC, awesomekling requested changes

2021-08-10 21:17 UTC, awesomekling commented on Userland/Applications/PixelPaint/ImageEditor.cpp
> +    event.ignore();
I think we should let the active tool decide if the event is accepted.

2021-08-10 21:17 UTC, awesomekling commented on Userland/Games/Solitaire/Game.cpp
> +    event.ignore();
I think this should be in an `else` branch. "Accepted" means that the widget did something meaningful with the event and no further processing is needed.

2021-08-10 21:17 UTC, awesomekling commented on Userland/Libraries/LibGUI/TextEditor.cpp
>      }
These are so weird. Why does text editor not handle `Key_Delete` itself in the first place? 🤔

2021-08-10 21:17 UTC, awesomekling commented on Userland/Libraries/LibVT/TerminalWidget.cpp
> +    event.ignore();
This feels too broad, if we did something with the event, we should accept it, not just pass it up the chain.

2021-08-10 21:17 UTC, awesomekling commented on Userland/Libraries/LibWeb/InProcessWebView.cpp
> +    event.ignore();
This seems at odds with `page_accepted_event` above. If the page accepted the event, we shouldn't call `ignore()` on it.

2021-08-10 21:17 UTC, awesomekling commented on Userland/Libraries/LibWeb/OutOfProcessWebView.cpp
> +    event.ignore();
Oh frick this is a really tricky one.. What does this mean for out-of-process browser engines..
We will now send all key events to the web content, even stuff that's potentially UI actions, like Ctrl+T ("open new tab") will become a JavaScript event despite the user *most likely* wanting to open a new tab..

2021-08-11 19:28 UTC, metmo reviewed
Third iteration of this one with, hopefully, more clear logic and flow

2021-08-11 19:28 UTC, metmo commented on Userland/Libraries/LibGUI/Widget.cpp
> +
Breaking this out to allow Widgets to trigger actions before other events. I'll admit returning a bool here isn't the best looking solution, if anyone has a better idea I'm open for it!

2021-09-13 09:17 UTC, closed without merging