Ports: fix configure to use target toolchain instead of host toolchain in ed
SerenityOS/serenity pull request #9306
Opened 2021-08-09 16:38 UTC by roytam1

2021-08-09 16:51 UTC, linusg requested changes
Please put more effort into your commit messages. From https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#code-submission-policy:

> Write your commit messages in proper English, with care and punctuation.

2021-08-09 23:10 UTC, roytam1 commented
> Please put more effort into your commit messages.

I tried my best to do so since English is not my primary language.

2021-08-10 01:06 UTC, alimpfard commented
Here's a commit message suggestion:
`Ports/ed: Make the configure script use the target toolchain`

2021-08-10 01:11 UTC, roytam1 commented
> Ports/ed: Make the configure script use the target toolchain

Thanks!

2021-08-11 06:41 UTC, merged