LibGL: Implement `glColorMask`
SerenityOS/serenity pull request #9381
Opened 2021-08-13 12:05 UTC by Quaker762

This function masks off certain colour channels from being written to in the colour buffer. For example, calling `glColorMask(false, false, true, true)` results in the following output:

![image](https://user-images.githubusercontent.com/4768900/129354586-0bc0fd57-0714-467d-8ea1-3fe5e2ac2b07.png)

cc @sunverwerth @alimpfard

2021-08-13 12:05 UTC, Quaker762 commented
Implements a function in #7062

2021-08-13 12:53 UTC, sunverwerth requested changes

2021-08-13 12:53 UTC, sunverwerth commented on Userland/Libraries/LibGL/SoftwareGLContext.cpp
> +    u32 mask = m_rasterizer.color_mask();
Please use `m_rasterizer.options()` and `m_rasterizer.set_options()` instead. This pattern is already used in different parts of the library.

2021-08-13 12:53 UTC, sunverwerth commented on Userland/Libraries/LibGL/SoftwareGLContext.cpp
> +    m_rasterizer.color_mask(mask);
See above

2021-08-13 12:53 UTC, sunverwerth commented on Userland/Libraries/LibGL/SoftwareRasterizer.h
> +    u32 color_mask() const { return m_options.color_mask; }
These two methods are not needed.

2021-08-13 12:59 UTC, sunverwerth requested changes

2021-08-13 12:59 UTC, sunverwerth commented on Userland/Libraries/LibGL/SoftwareRasterizer.cpp
> +                        *dst &= options.color_mask;
This is not correct. We don't want to completely black out color components in the render target. instead we want to mask out the write itself, so the original content of the color channel remains unmodified in the render target.

2021-08-15 04:24 UTC, Quaker762 commented
@sunverwerth Alright let's see how we go with this :P

2021-08-15 08:43 UTC, sunverwerth requested changes

2021-08-15 08:43 UTC, sunverwerth commented on Userland/Libraries/LibGL/SoftwareRasterizer.cpp
> +                        *dst &= options.color_mask;
```suggestion
```

Please remove

2021-08-15 09:26 UTC, Quaker762 commented on Userland/Libraries/LibGL/SoftwareRasterizer.cpp
> +                        *dst &= options.color_mask;
Bad rebase, whoops...

2021-08-15 11:07 UTC, sunverwerth requested changes

2021-08-15 11:07 UTC, sunverwerth commented on Userland/Libraries/LibGL/SoftwareRasterizer.cpp
>                          *dst = to_rgba32(*src);
There's still one line too many :D
```suggestion
```

2021-08-15 11:41 UTC, Quaker762 commented on Userland/Libraries/LibGL/SoftwareRasterizer.cpp
>                          *dst = to_rgba32(*src);
Third time's the charm...

2021-08-15 12:05 UTC, sunverwerth approved these changes
lgtm!

2021-08-15 14:07 UTC, Quaker762 commented
@alimpfard Looks like running a test failed?!?! CI issue?

2021-08-15 15:03 UTC, alimpfard commented
Something flaky, I've seen it happen quite a bit lately

2021-08-15 18:04 UTC, merged