LibGL: Implement `glPolygonMode`
SerenityOS/serenity pull request #9513
Opened 2021-08-19 11:41 UTC by Quaker762

Currently just sets the renderer option for what polygon mode we
want the rasterizer to draw in. GLQuake only uses `GL_FRONT_AND_BACK`
with `GL_FILL` )which implies both back and front facing triangles
are to be filled completely by the rasterizer), so keeping this as
a small stub is perfectly fine for now.

2021-08-19 11:42 UTC, Quaker762 commented
cc @sunverwerth One more function to cross off the "GLQuake Ready" list

2021-08-19 22:19 UTC, sunverwerth requested changes

2021-08-19 22:19 UTC, sunverwerth commented on Userland/Libraries/LibGL/SoftwareGLContext.cpp
> +    RETURN_WITH_ERROR_IF(mode != GL_POINT || mode != GL_LINE || mode != GL_FILL, GL_INVALID_ENUM);
```suggestion
    RETURN_WITH_ERROR_IF(!(face == GL_BACK || face == GL_FRONT || face == GL_FRONT_AND_BACK), GL_INVALID_ENUM);
    RETURN_WITH_ERROR_IF(!(mode == GL_POINT || mode == GL_LINE || mode == GL_FILL), GL_INVALID_ENUM);
```

2021-08-20 13:52 UTC, sunverwerth commented
lgtm

2021-08-20 13:52 UTC, sunverwerth approved these changes

2021-08-20 15:34 UTC, merged