PixelPaint: Shift-key for squares and circles
SerenityOS/serenity pull request #9609
Opened 2021-08-25 21:20 UTC by ZyperPL

PR adds method for changing point's one coordinate (X or Y) to make X and Y difference with other point's X and Y equal to the maximum difference. In short: it makes abs(X2 - X1) == abs(Y2 - Y1). 

Method is used in Rectangle Tool for making squares and Ellipse Tool for making circles

2021-08-28 07:23 UTC, linusg requested changes
Please reword the commit messages to use imperative mood.

2021-08-28 07:23 UTC, linusg commented on Userland/Applications/PixelPaint/EllipseTool.cpp
> +        m_ellipse_end_position = m_ellipse_start_position.end_point_for_square_aspect_ratio(event.layer_event().position());
Seems odd to write the value twice in the shift case, how about:

```suggestion
    if (event.layer_event().shift())
        m_ellipse_end_position = m_ellipse_start_position.end_point_for_square_aspect_ratio(event.layer_event().position());
    else
        m_ellipse_end_position = event.layer_event().position();
```

2021-08-28 11:38 UTC, linusg approved these changes

2021-09-08 06:49 UTC, mustafaquraish commented
If you're adding a helper to get the other end point for an aspect ratio anyway, maybe it would make sense to have the function take in an arbitrary aspect ratio and compute the endpoint for that, instead of just hard-coding it to be only for squares? I'm imagining it would be useful if we want to restrict the drawing of shapes to some configurable aspect ratio as well, in the future.

2021-09-08 08:03 UTC, TobyAsE commented
@mustafaquraish this is a good idea, however I think let's put it into a future pr ;)

2021-09-15 00:10 UTC, bgianfo approved these changes
LGTM! 🔲 ⚪ 🖌️

2021-09-15 00:10 UTC, merged