PixelPaint: Fix layer dragging bug
SerenityOS/serenity pull request #9767
Opened 2021-09-03 00:28 UTC by mustafaquraish

A previous commit I made broke layer dragging (oops) since the hole_index
was always being computed with respect to the top of the layer list
widget, however we were now drawing layers from the bottom. When
you didn't have enough layers to fill up the full height, dragging
them around would be weird.

This patch computes the hole index correctly using the same offset
we start drawing from, and fixes the behaviour. This commit should
have been squashed with 0c56f06, but I didn't catch the mistake in time  :(

2021-09-03 00:33 UTC, awesomekling requested changes

2021-09-03 00:33 UTC, awesomekling commented on Userland/Applications/PixelPaint/LayerListWidget.h
> +    int m_total_gadget_height;
Please initialize primitive variables explicitly. :)

2021-09-03 01:11 UTC, mustafaquraish commented on Userland/Applications/PixelPaint/LayerListWidget.h
> +    int m_total_gadget_height;
Oops, fixed!

2021-09-06 01:07 UTC, mustafaquraish commented
@awesomekling Can you have a second look at this when you get some time? I've been working on PixelPaint a bunch and this layer bug is driving me a bit nuts :^(

2021-09-06 22:48 UTC, merged