Pixel Paint: Added pixel paint file types icons
SerenityOS/serenity pull request #9883
Opened 2021-09-07 22:25 UTC by jackdelahunt

This pr adds icons for the .pp filetype which is the file pixel paint creates. Both the 16x16 and the 32x32 are included.

2021-09-07 23:04 UTC, linusg requested changes
Please call it `pixelpaint` without the dash, and use `Base` as the commit prefix.

2021-09-08 09:21 UTC, jackdelahunt commented
Addressed the changes requested, everything should be okay now.

2021-09-08 17:46 UTC, Granddave commented
LGTM :+1:

2021-09-08 19:14 UTC, linusg approved these changes

2021-09-08 19:15 UTC, merged